libjobs: jobs::counter_handle Class Reference
jobs::counter_handle Class Reference
Represents an instance of an counter that has been created by the scheduler.
#include <jobs_counter.h>
Public Member Functions
counter_handle ()
counter_handle (const counter_handle &other)
Copy constructor.
~counter_handle ()
result wait_for (size_t value, timeout in_timeout=timeout::infinite)
Waits for this counter to reach a specific value.
result add (size_t value)
Adds a given value to this counter.
result remove (size_t value, timeout in_timeout=timeout::infinite)
Removes the given value from this counter.
result get (size_t &output)
Gets the current value of this counter.
result set (size_t value)
Sets the current value of this counter.
counter_handle & operator= (const counter_handle &other)
Assignment operator.
bool operator== (const counter_handle &rhs) const
Equality operator.
bool operator!= (const counter_handle &rhs) const
Inequality operator.
bool is_valid () const
Returns true if this handle points to a valid counter instance.
Protected Member Functions
counter_handle (scheduler *scheduler, size_t index)
Constructor.
void increase_ref ()
void decrease_ref ()
Private Member Functions
bool modify_value (size_t new_value, bool absolute, bool subtract=false, bool lock_required=true)
Attempts to modify the value held by the counter.
void notify_value_changed (size_t new_value, bool lock_required=true)
Wakes up any jobs that are waiting for the given value.
bool add_to_wait_list (internal::job_definition *job_def)
Adds the given job to our wait list.
void remove_from_wait_list (internal::job_definition *job_def)
Removes the given job from our wait list.
Private Attributes
scheduler * m_scheduler = nullptr
size_t m_index = 0
Friends
class scheduler
Detailed Description
Represents an instance of an counter that has been created by the scheduler.
Events data is owned by the scheduler, be careful accessing handles if the scheduler has been destroyed.
Counters represent an atomic integer value that can be never be negative. Counters can be added to, and removed from. If a removal would result in a negative value, the counter waits until enough has been added that the value can be removed. Counters also support the ability to get/set values directly as well as wait for specific values to be set.
The functionality of counters is straight-forward but incredibly flexible, and can be used in a multitude of ways to syncronize jobs.
Implementation wise this is fairly similar to a semaphore, just with more control over the internal signal count.
Definition at line 99 of file jobs_counter.h.
Constructor & Destructor Documentation
counter_handle() [1/3]
jobs::counter_handle::counter_handle (scheduler * scheduler, size_t index) protected
Constructor.
Parameters
scheduler Scheduler that owns this counter.
index Index into the scheduler's counter pool where this counters data is held.
Definition at line 49 of file jobs_counter.cpp.
References increase_ref().
     : m_scheduler(scheduler)
     , m_index(index)
 {
     increase_ref();
 }
counter_handle() [2/3]
jobs::counter_handle::counter_handle ()
Constructor
Definition at line 56 of file jobs_counter.cpp.
Referenced by add_to_wait_list(), remove(), and wait_for().
     : m_scheduler(nullptr)
     , m_index(0)
 {
 }
counter_handle() [3/3]
jobs::counter_handle::counter_handle (const counter_handle & other)
Copy constructor.
Parameters
other Object to copy.
Definition at line 62 of file jobs_counter.cpp.
References increase_ref(), m_index, and m_scheduler.
 {
     m_scheduler = other.m_scheduler;
     m_index = other.m_index;
     increase_ref();
 }
~counter_handle()
jobs::counter_handle::~counter_handle ()
Destructor
Definition at line 70 of file jobs_counter.cpp.
References decrease_ref().
 {
     decrease_ref();
 }
Member Function Documentation
add()
result jobs::counter_handle::add (size_t value)
Adds a given value to this counter.
Causes any waiting jobs to be readied if the resulting value is equal to the value they are waiting for.
Parameters
value Value to add to the counter.
Returns
Value indicating the success of this function.
Definition at line 371 of file jobs_counter.cpp.
References modify_value(), and jobs::success.
Referenced by jobs::scheduler::complete_job().
 {
     modify_value(value, false);
     return result::success;
 }
add_to_wait_list()
bool jobs::counter_handle::add_to_wait_list (internal::job_definition * job_def) private
Adds the given job to our wait list.
Parameters
job_def Definition of job to add to our wait list.
Returns
True if added to wait list, false if wait criteria was met while attempting operation and did not need to be added to list.
Definition at line 422 of file jobs_counter.cpp.
References counter_handle(), jobs::fiber, jobs::scheduler::get_counter_definition(), jobs_profile_scope, m_index, m_scheduler, modify_value(), jobs::internal::pending, jobs::internal::job_definition::status, jobs::internal::counter_definition::value, jobs::internal::job_definition::wait_counter, jobs::internal::job_definition::wait_counter_list_link, jobs::internal::job_definition::wait_counter_remove_value, jobs::internal::job_definition::wait_counter_value, and jobs::internal::counter_definition::wait_list.
Referenced by remove(), and wait_for().
 {
     jobs_profile_scope(profile_scope_type::fiber, "counter::add_to_wait_list", m_scheduler);
     internal::counter_definition& def = m_scheduler->get_counter_definition(m_index);
     if (job_def->wait_counter_remove_value)
     {
         internal::optional_lock<internal::spinwait_mutex> lock(def.wait_list.get_mutex());
         // Value high enough to remove? We don't need to wait.
         if (modify_value(job_def->wait_counter_value, false, true, false))
         {
             job_def->status = internal::job_status::pending;
             job_def->wait_counter = counter_handle();
             return false;
         }
         job_def->wait_counter_list_link.value = job_def;
         def.wait_list.add(&job_def->wait_counter_list_link, false);
     }
     else
     {
         internal::optional_shared_lock<internal::spinwait_mutex> lock(def.wait_list.get_mutex());
         // Is value equal? We don't need to wait.
         if (def.value == job_def->wait_counter_value)
         {
             job_def->status = internal::job_status::pending;
             job_def->wait_counter = counter_handle();
             return false;
         }
         job_def->wait_counter_list_link.value = job_def;
         def.wait_list.add(&job_def->wait_counter_list_link, false);
     }
     return true;
 }
decrease_ref()
void jobs::counter_handle::decrease_ref () protected
Decreases the reference count of this counter. When it reaches zero, it will be disposed of.
Definition at line 98 of file jobs_counter.cpp.
References jobs::scheduler::decrease_counter_ref_count(), m_index, and m_scheduler.
Referenced by ~counter_handle().
 {
     if (m_scheduler != nullptr)
     {
         m_scheduler->decrease_counter_ref_count(m_index);
     }
 }
get()
result jobs::counter_handle::get (size_t & output)
Gets the current value of this counter.
Parameters
output Reference to location to store value in.
Returns
Value indicating the success of this function.
Definition at line 360 of file jobs_counter.cpp.
References jobs::fiber, jobs::scheduler::get_counter_definition(), jobs_profile_scope, m_index, m_scheduler, jobs::success, and jobs::internal::counter_definition::value.
 {
     jobs_profile_scope(profile_scope_type::fiber, "counter::get", m_scheduler);
     internal::counter_definition& def = m_scheduler->get_counter_definition(m_index);
     output = def.value;
     return result::success;
 }
increase_ref()
void jobs::counter_handle::increase_ref () protected
Increases the reference count of this counter.
Definition at line 90 of file jobs_counter.cpp.
References jobs::scheduler::increase_counter_ref_count(), m_index, and m_scheduler.
Referenced by counter_handle(), and operator=().
 {
     if (m_scheduler != nullptr)
     {
         m_scheduler->increase_counter_ref_count(m_index);
     }
 }
is_valid()
bool jobs::counter_handle::is_valid () const
Returns true if this handle points to a valid counter instance.
Returns
True if handle is valid.
Definition at line 85 of file jobs_counter.cpp.
References m_scheduler.
Referenced by jobs::scheduler::complete_job().
 {
     return (m_scheduler != nullptr);
 }
modify_value()
bool jobs::counter_handle::modify_value (size_t new_value, bool absolute, bool subtract = false, bool lock_required = true) private
Attempts to modify the value held by the counter.
Parameters
new_value Value that counter should be modified to.
absolute If true the value should be modified absolutely, otherwise its relative to its current value.
subtract If true the value should be subtracted not added.
lock_required If true a mutex lock needs to be acquired for our wait list. If false its assumed that the lock is held further up the callstack.
Returns
True if value was modified, false if unable to because it would result in a negative number.
Definition at line 383 of file jobs_counter.cpp.
References jobs::fiber, jobs::scheduler::get_counter_definition(), jobs_profile_scope, m_index, m_scheduler, notify_value_changed(), jobs::internal::counter_definition::value, and jobs::internal::counter_definition::wait_list.
Referenced by add(), add_to_wait_list(), notify_value_changed(), and set().
 {
     jobs_profile_scope(profile_scope_type::fiber, "counter::modify_value", m_scheduler);
     internal::counter_definition& def = m_scheduler->get_counter_definition(m_index);
     {
         internal::optional_shared_lock<internal::spinwait_mutex> lock(def.wait_list.get_mutex(), lock_required);
         size_t changed_value = 0;
         if (absolute)
         {
             changed_value = (def.value = new_value);
         }
         else
         {
             if (subtract)
             {
                 if (def.value >= new_value)
                 {
                     changed_value = (def.value -= new_value);
                 }
                 else
                 {
                     return false;
                 }
             }
             else
             {
                 changed_value = (def.value += new_value);
             }
         }
         notify_value_changed(changed_value, false);
     }
     return true;
 }
notify_value_changed()
void jobs::counter_handle::notify_value_changed (size_t new_value, bool lock_required = true) private
Wakes up any jobs that are waiting for the given value.
Parameters
new_value Value that jobs should be waiting for to be woken up.
lock_required If true a mutex lock needs to be acquired for our wait list. If false its assumed that the lock is held further up the callstack.
Returns
True if added to wait list, false if wait criteria was met while attempting operation and did not need to be added to list.
Definition at line 473 of file jobs_counter.cpp.
References jobs::fiber, jobs::scheduler::get_counter_definition(), jobs::internal::job_definition::index, jobs_profile_scope, m_index, m_scheduler, modify_value(), jobs::scheduler::notify_job_available(), jobs::internal::pending, jobs::internal::multiple_writer_single_reader_list< data_type >::iterator::remove(), jobs::scheduler::requeue_job(), jobs::internal::job_definition::status, jobs::internal::multiple_writer_single_reader_list< data_type >::iterator::value(), jobs::internal::counter_definition::value_cvar, jobs::internal::counter_definition::value_cvar_mutex, jobs::internal::job_definition::wait_counter_do_not_requeue, jobs::internal::job_definition::wait_counter_remove_value, jobs::internal::job_definition::wait_counter_value, jobs::internal::counter_definition::wait_list, and jobs::internal::waiting_on_counter.
Referenced by modify_value().
 {
     jobs_profile_scope(profile_scope_type::fiber, "counter::notify_value_changed", m_scheduler);
     internal::counter_definition& def = m_scheduler->get_counter_definition(m_index);
     // Go through wait list and mark all jobs as ready to resume if their criteria is met.
     size_t signalled_job_count = 0;
     size_t signalled_no_requeue_job_count = 0;
     {
         jobs_profile_scope(profile_scope_type::fiber, "wake up waiting", m_scheduler);
         internal::multiple_writer_single_reader_list<internal::job_definition*>::iterator iter;
         for (def.wait_list.iterate(iter, lock_required); iter; )
         {
             bool signal = false;
             internal::job_definition* job_def = iter.value();
             if (job_def->wait_counter_remove_value)
             {
                 signal = modify_value(job_def->wait_counter_value, false, true, false);
             }
             else
             {
                 signal = (new_value == job_def->wait_counter_value);
             }
             if (signal)
             {
                 internal::job_status expected = internal::job_status::waiting_on_counter;
                 if (job_def->status.compare_exchange_strong(expected, internal::job_status::pending))
                 {
                     if (!job_def->wait_counter_do_not_requeue)
                     {
                         m_scheduler->requeue_job(job_def->index);
                         signalled_job_count++;
                     }
                     else
                     {
                         signalled_no_requeue_job_count++;
                     }
                     iter.remove();
                     continue;
                 }
             }
             iter++;
         }
     }
     if (signalled_job_count > 0)
     {
         jobs_profile_scope(profile_scope_type::fiber, "signal worker threads", m_scheduler);
         m_scheduler->notify_job_available(signalled_job_count);
     }
     if (signalled_no_requeue_job_count > 0)
     {
         jobs_profile_scope(profile_scope_type::fiber, "signal waiting threads", m_scheduler);
         std::unique_lock<std::mutex> lock(def.value_cvar_mutex);
         def.value_cvar.notify_all();
     }
 }
operator!=()
bool jobs::counter_handle::operator!= (const counter_handle & rhs) const
Inequality operator.
Parameters
rhs Object to compare against.
Returns
True if objects are inequal.
Definition at line 546 of file jobs_counter.cpp.
 {
     return !(*this == rhs);
 }
operator=()
counter_handle & jobs::counter_handle::operator= (const counter_handle & other)
Assignment operator.
Parameters
other Object to assign.
Returns
Reference to this object.
Definition at line 75 of file jobs_counter.cpp.
References increase_ref(), m_index, and m_scheduler.
 {
     m_scheduler = other.m_scheduler;
     m_index = other.m_index;
     increase_ref();
     return *this;
 }
operator==()
bool jobs::counter_handle::operator== (const counter_handle & rhs) const
Equality operator.
Parameters
rhs Object to compare against.
Returns
True if objects are equal.
Definition at line 541 of file jobs_counter.cpp.
References m_index, and m_scheduler.
 {
     return (m_scheduler == rhs.m_scheduler && m_index == rhs.m_index);
 }
remove()
result jobs::counter_handle::remove (size_t value, timeout in_timeout = timeout::infinite)
Removes the given value from this counter.
Values of counters can never be negative. If this operation would make the value go negative, the job will be queued for execution (or the thread blocked if called from a non-job) until the counter has a value high enough that this operation would not cause a negative.
Causes any waiting jobs to be readied if the resulting value is equal to the value they are waiting for.
Parameters
value Value to remove from counter.
in_timeout If provided, this function will wait a maximum of this time. If the function returns due to a timeout the result provided will be result::timeout.
Returns
Value indicating the success of this function.
Definition at line 232 of file jobs_counter.cpp.
References add_to_wait_list(), jobs::internal::callback_scheduler::cancel(), counter_handle(), jobs::timeout::duration, jobs::fiber, jobs::scheduler::get_active_job_context(), jobs::scheduler::get_counter_definition(), jobs::internal::stopwatch::get_elapsed_ms(), jobs::scheduler::get_worker_job_context(), jobs::internal::job_definition::index, jobs::timeout::is_infinite(), jobs::internal::job_context::job_def, jobs_profile_scope, jobs::scheduler::m_callback_scheduler, m_index, m_scheduler, jobs::internal::pending, remove_from_wait_list(), jobs::scheduler::requeue_job(), jobs::scheduler::return_to_worker(), jobs::internal::callback_scheduler::schedule(), jobs::internal::stopwatch::start(), jobs::internal::job_definition::status, jobs::success, jobs::timeout, jobs::internal::counter_definition::value_cvar, jobs::internal::counter_definition::value_cvar_mutex, jobs::internal::job_definition::wait_counter, jobs::internal::job_definition::wait_counter_do_not_requeue, jobs::internal::job_definition::wait_counter_remove_value, jobs::internal::job_definition::wait_counter_value, and jobs::internal::waiting_on_counter.
Referenced by jobs::event_handle::wait().
 {
     jobs_profile_scope(profile_scope_type::fiber, "counter::remove", m_scheduler);
     internal::counter_definition& def = m_scheduler->get_counter_definition(m_index);
     // Grab the current job context.
     internal::job_context* context = m_scheduler->get_active_job_context();
     internal::job_context* worker_context = m_scheduler->get_worker_job_context();
     // If we have a job context, go to sleep waiting on the value.
     if (context != nullptr)
     {
         assert(worker_context != nullptr);
         volatile bool timeout_called = false;
         // Put job to sleep.
         {
             context->job_def->status = internal::job_status::waiting_on_counter;
             context->job_def->wait_counter = *this;
             context->job_def->wait_counter_value = value;
             context->job_def->wait_counter_remove_value = true;
             context->job_def->wait_counter_do_not_requeue = false;
             if (!add_to_wait_list(context->job_def))
             {
                 return result::success;
             }
         }
         // Queue a wakeup.
         size_t schedule_handle;
         if (!in_timeout.is_infinite())
         {
             result res = m_scheduler->m_callback_scheduler.schedule(in_timeout, schedule_handle, [&]() {
                 // Do this atomatically to make sure we don't set it to pending after the scheduler
                 // has already done that due to this event being signalled.
                 internal::job_status expected = internal::job_status::waiting_on_counter;
                 if (context->job_def->status.compare_exchange_strong(expected, internal::job_status::pending))
                 {
                     timeout_called = true;
                     m_scheduler->requeue_job(context->job_def->index);
                 }
             });
             // Failed to schedule a wakeup? Abort.
             if (res != result::success)
             {
                 remove_from_wait_list(context->job_def);
                 context->job_def->status = internal::job_status::pending;
                 return res;
             }
         }
         // Supress requeueing the job, and return to worker, we will do this when the callback returns.
         m_scheduler->return_to_worker(*worker_context, true);
         // Cleanup
         context->job_def->wait_counter = counter_handle();
         // If we timed out, just escape here.
         if (timeout_called)
         {
             return result::timeout;
         }
         // Cancel callback and clear our job handle.
         if (!in_timeout.is_infinite())
         {
             m_scheduler->m_callback_scheduler.cancel(schedule_handle);
         }
         return result::success;
     }
     // If no job-context we have to do a blocking wait.
     else
     {
         internal::stopwatch timer;
         timer.start();
         size_t changed_value = 0;
         {
             std::unique_lock<std::mutex> lock(def.value_cvar_mutex);
             // Allocate a fake job to be waited on.
             internal::job_definition fake_job(UINT32_MAX);
             fake_job.status = internal::job_status::waiting_on_counter;
             fake_job.wait_counter = *this;
             fake_job.wait_counter_value = value;
             fake_job.wait_counter_remove_value = true;
             fake_job.wait_counter_do_not_requeue = true;
             if (!add_to_wait_list(&fake_job))
             {
                 return result::success;
             }
             // Keep looping until we manage to decrease the value.
             while (fake_job.status == internal::job_status::waiting_on_counter)
             {
                 if (in_timeout.is_infinite())
                 {
                     def.value_cvar.wait(lock);
                 }
                 else
                 {
                     size_t ms_remaining = in_timeout.duration - timer.get_elapsed_ms();
                     if (ms_remaining > 0)
                     {
                         def.value_cvar.wait_for(lock, std::chrono::milliseconds(ms_remaining));
                     }
                     else
                     {
                         return result::timeout;
                     }
                 }
             }
         }
     }
     return result::success;
 }
remove_from_wait_list()
void jobs::counter_handle::remove_from_wait_list (internal::job_definition * job_def) private
Removes the given job from our wait list.
Parameters
job_def Definition of job to remove from our wait list.
Definition at line 464 of file jobs_counter.cpp.
References jobs::fiber, jobs::scheduler::get_counter_definition(), jobs_profile_scope, m_index, m_scheduler, jobs::internal::job_definition::wait_counter_list_link, and jobs::internal::counter_definition::wait_list.
Referenced by remove(), and wait_for().
 {
     jobs_profile_scope(profile_scope_type::fiber, "counter::remove_from_wait_list", m_scheduler);
     internal::counter_definition& def = m_scheduler->get_counter_definition(m_index);
     def.wait_list.remove(&job_def->wait_counter_list_link);
 }
set()
result jobs::counter_handle::set (size_t value)
Sets the current value of this counter.
Causes any waiting jobs to be readied if the resulting value is equal to the value they are waiting for.
Parameters
value Value to set counter to.
Returns
Value indicating the success of this function.
Definition at line 377 of file jobs_counter.cpp.
References modify_value(), and jobs::success.
Referenced by jobs::event_handle::reset(), and jobs::event_handle::signal().
 {
     modify_value(value, true);
     return result::success;
 }
wait_for()
result jobs::counter_handle::wait_for (size_t value, timeout in_timeout = timeout::infinite)
Waits for this counter to reach a specific value.
If called from a job this is non-blocking, and will queue the job for execution after the counter reaches the given value. If called from any other place, it will block.
Parameters
value Value counter needs to reach to continue.
in_timeout If provided, this function will wait a maximum of this time. If the function returns due to a timeout the result provided will be result::timeout.
Returns
Value indicating the success of this function.
Definition at line 106 of file jobs_counter.cpp.
References add_to_wait_list(), jobs::internal::callback_scheduler::cancel(), counter_handle(), jobs::timeout::duration, jobs::fiber, jobs::scheduler::get_active_job_context(), jobs::scheduler::get_counter_definition(), jobs::internal::stopwatch::get_elapsed_ms(), jobs::scheduler::get_worker_job_context(), jobs::internal::job_definition::index, jobs::timeout::is_infinite(), jobs::internal::job_context::job_def, jobs_profile_scope, jobs::scheduler::m_callback_scheduler, m_index, m_scheduler, jobs::internal::pending, remove_from_wait_list(), jobs::scheduler::requeue_job(), jobs::scheduler::return_to_worker(), jobs::internal::callback_scheduler::schedule(), jobs::internal::stopwatch::start(), jobs::internal::job_definition::status, jobs::success, jobs::timeout, jobs::internal::counter_definition::value_cvar, jobs::internal::counter_definition::value_cvar_mutex, jobs::internal::job_definition::wait_counter, jobs::internal::job_definition::wait_counter_do_not_requeue, jobs::internal::job_definition::wait_counter_remove_value, jobs::internal::job_definition::wait_counter_value, and jobs::internal::waiting_on_counter.
Referenced by jobs::event_handle::wait().
 {
     jobs_profile_scope(profile_scope_type::fiber, "counter::wait_for", m_scheduler);
     internal::counter_definition& def = m_scheduler->get_counter_definition(m_index);
     // Grab the current job context.
     internal::job_context* context = m_scheduler->get_active_job_context();
     internal::job_context* worker_context = m_scheduler->get_worker_job_context();
     // If we have a job context, go to sleep waiting on the value.
     if (context != nullptr)
     {
         assert(worker_context != nullptr);
         volatile bool timeout_called = false;
         // Put job to sleep.
         {
             context->job_def->status = internal::job_status::waiting_on_counter;
             context->job_def->wait_counter = *this;
             context->job_def->wait_counter_value = value;
             context->job_def->wait_counter_remove_value = false;
             context->job_def->wait_counter_do_not_requeue = false;
             if (!add_to_wait_list(context->job_def))
             {
                 return result::success;
             }
         }
         // Queue a wakeup.
         size_t schedule_handle;
         if (!in_timeout.is_infinite())
         {
             result res = m_scheduler->m_callback_scheduler.schedule(in_timeout, schedule_handle, [&]() {
                 // Do this atomatically to make sure we don't set it to pending after the scheduler
                 // has already done that due to this event being signalled.
                 internal::job_status expected = internal::job_status::waiting_on_counter;
                 if (context->job_def->status.compare_exchange_strong(expected, internal::job_status::pending))
                 {
                     timeout_called = true;
                     m_scheduler->requeue_job(context->job_def->index);
                 }
             });
             // Failed to schedule a wakeup? Abort.
             if (res != result::success)
             {
                 remove_from_wait_list(context->job_def);
                 context->job_def->status = internal::job_status::pending;
                 return res;
             }
         }
         // Supress requeueing the job, and return to worker, we will do this when the callback returns.
         m_scheduler->return_to_worker(*worker_context, true);
         // Cleanup
         context->job_def->wait_counter = counter_handle();
         // If we timed out, just escape here.
         if (timeout_called)
         {
             return result::timeout;
         }
         // Cancel callback and clear our job handle.
         if (!in_timeout.is_infinite())
         {
             m_scheduler->m_callback_scheduler.cancel(schedule_handle);
         }
         return result::success;
     }
     // If no job-context we have to do a blocking wait.
     else
     {
         internal::stopwatch timer;
         timer.start();
         {
             std::unique_lock<std::mutex> lock(def.value_cvar_mutex);
             // Allocate a fake job to be waited on.
             internal::job_definition fake_job(UINT32_MAX);
             fake_job.status = internal::job_status::waiting_on_counter;
             fake_job.wait_counter = *this;
             fake_job.wait_counter_value = value;
             fake_job.wait_counter_remove_value = false;
             fake_job.wait_counter_do_not_requeue = true;
             if (!add_to_wait_list(&fake_job))
             {
                 return result::success;
             }
             // Keep looping until we manage to decrease the value.
             while (fake_job.status == internal::job_status::waiting_on_counter)
             {
                 if (in_timeout.is_infinite())
                 {
                     def.value_cvar.wait(lock);
                 }
                 else
                 {
                     size_t ms_remaining = in_timeout.duration - timer.get_elapsed_ms();
                     if (ms_remaining > 0)
                     {
                         def.value_cvar.wait_for(lock, std::chrono::milliseconds(ms_remaining));
                     }
                     else
                     {
                         return result::timeout;
                     }
                 }
             }
         }
     }
     return result::success;
 }
Friends And Related Function Documentation
scheduler
friend class scheduler friend
Definition at line 103 of file jobs_counter.h.
Field Documentation
m_index
size_t jobs::counter_handle::m_index = 0 private
Index into the scheduler's counter pool where this counters data is held.
Definition at line 284 of file jobs_counter.h.
Referenced by add_to_wait_list(), counter_handle(), decrease_ref(), get(), increase_ref(), modify_value(), notify_value_changed(), operator=(), operator==(), remove(), remove_from_wait_list(), and wait_for().
m_scheduler
scheduler* jobs::counter_handle::m_scheduler = nullptr private
Pointer to the owning scheduler of this handle.
Definition at line 281 of file jobs_counter.h.
Referenced by add_to_wait_list(), counter_handle(), decrease_ref(), get(), increase_ref(), is_valid(), modify_value(), notify_value_changed(), operator=(), operator==(), remove(), remove_from_wait_list(), and wait_for().
The documentation for this class was generated from the following files:
C:/Projects/libjobs/inc/jobs_counter.h
C:/Projects/libjobs/src/jobs_counter.cpp