libjobs: jobs::internal::profile_scope_internal Class Reference
jobs::internal::profile_scope_internal Class Reference
#include <jobs_job.h>
Public Member Functions
profile_scope_internal (jobs::profile_scope_type type, const char *tag, jobs::scheduler *scheduler=nullptr)
Constructor.
~profile_scope_internal ()
Private Attributes
jobs::internal::job_context * m_context = nullptr
jobs::scheduler * m_scheduler = nullptr
Detailed Description
Simple RAII type that enters a profile scope on construction and exits it on destruction.
Definition at line 545 of file jobs_job.h.
Constructor & Destructor Documentation
profile_scope_internal()
jobs::internal::profile_scope_internal::profile_scope_internal (jobs::profile_scope_type type, const char * tag, jobs::scheduler * scheduler = nullptr)
Constructor.
Parameters
type Semantic type of code this profile marker is enclosing.
tag Descriptive tag.
scheduler Scheduler that owns this profile scope. If nullptr, static value will be used.
Definition at line 157 of file jobs_job.cpp.
References jobs::profile_functions::enter_scope, jobs::internal::job_context::enter_scope(), jobs::scheduler::get_active_job_context(), jobs::scheduler::is_profiling_active(), jobs::scheduler::m_profile_functions, and jobs::internal::job_context::scheduler.
 {
     if (!scheduler::is_profiling_active())
     {
         return;
     }
     internal::job_context* context = scheduler::get_active_job_context();
     if (context != nullptr)
     {
         context->enter_scope(type, true, tag);
     }
     else if (scheduler != nullptr)
     {
         scheduler->m_profile_functions.enter_scope(type, tag);
     }
     m_scheduler = scheduler;
     m_context = context;
 }
~profile_scope_internal()
jobs::internal::profile_scope_internal::~profile_scope_internal ()
Destructor
Definition at line 178 of file jobs_job.cpp.
References jobs::scheduler::get_active_job_context(), jobs::scheduler::is_profiling_active(), and jobs::internal::job_context::leave_scope().
 {
     if (!scheduler::is_profiling_active())
     {
         return;
     }
     internal::job_context* context = scheduler::get_active_job_context();
     // Not sure if this situation is even possible, but make sure we always
     // leave on the same context we enter on.
     assert(context == m_context);
     if (context != nullptr)
     {
         context->leave_scope();
     }
     else if (m_scheduler != nullptr)
     {
         m_scheduler->m_profile_functions.leave_scope();
     }
 }
Field Documentation
m_context
jobs::internal::job_context* jobs::internal::profile_scope_internal::m_context = nullptr private
Job context this scope is inside of.
Definition at line 564 of file jobs_job.h.
m_scheduler
jobs::scheduler* jobs::internal::profile_scope_internal::m_scheduler = nullptr private
Scheduler that owns this profile scope.
Definition at line 567 of file jobs_job.h.
The documentation for this class was generated from the following files:
C:/Projects/libjobs/inc/jobs_job.h
C:/Projects/libjobs/src/jobs_job.cpp