libjobs: jobs::internal::thread Class Reference
jobs::internal::thread Class Reference
#include <jobs_thread.h>
Public Member Functions
thread (const memory_functions &memory_functions)
~thread ()
result init (const thread_entry_point &entry_point, const char *name, size_t core_affinity)
Initializes this thread of execution and begins running the thread.
void join ()
Blocks until thread completes execution.
Private Attributes
memory_functions m_memory_functions
std::thread m_thread
Detailed Description
Encapsulates a thread of execution on the base platform.
Definition at line 51 of file jobs_thread.h.
Constructor & Destructor Documentation
thread()
jobs::internal::thread::thread (const memory_functions & memory_functions)
Constructor.
Parameters
memory_functions Scheduler defined memory functions used to override default memory allocation behaviour.
Definition at line 38 of file jobs_thread.cpp.
     : m_memory_functions(memory_functions)
 {
 }
~thread()
jobs::internal::thread::~thread ()
Destructor.
Definition at line 43 of file jobs_thread.cpp.
References join().
 {
     join();
 }
Member Function Documentation
init()
result jobs::internal::thread::init (const thread_entry_point & entry_point, const char * name, size_t core_affinity)
Initializes this thread of execution and begins running the thread.
Parameters
entry_point Function that should be run when the thread starts.
name Contextual name of this thread to show in debugger.
core_affinity Mask of which cores this thread can execute on.
Returns
Value indicating the success of this function.
Definition at line 48 of file jobs_thread.cpp.
References jobs::internal::get_first_set_bit_pos(), m_thread, and jobs::success.
Referenced by jobs::internal::callback_scheduler::init().
 {
 #if defined(JOBS_PLATFORM_WINDOWS)
     wchar_t wide_name[64];
     std::mbstate_t state = std::mbstate_t();
     size_t ret_size = 0;
     mbsrtowcs_s(&ret_size, wide_name, &name, 128, &state);
     std::thread new_thread([entry_point, wide_name]() {
         SetThreadDescription(GetCurrentThread(), wide_name);
         entry_point();
     });
 #elif defined(JOBS_PLATFORM_PS4)
     char name_storage[128];
     strncpy(name_storage, name, 128);
     name_storage[127] = '\0';
     std::thread new_thread([=]() {
         scePthreadRename(scePthreadSelf(), name_storage);
         scePthreadSetaffinity(scePthreadSelf(), (SceKernelCpumask)core_affinity);
         entry_point();
     });
 #elif defined(JOBS_PLATFORM_SWITCH)
     char name_storage[nn::os::ThreadNameLengthMax];
     strncpy(name_storage, name, nn::os::ThreadNameLengthMax);
     name_storage[nn::os::ThreadNameLengthMax - 1] = '\0';
     // Filter affinity to only valid core indices or switch will complain.
     core_affinity = core_affinity & nn::os::GetThreadAvailableCoreMask();
     int ideal_core = jobs::internal::get_first_set_bit_pos(core_affinity) - 1;
     std::thread new_thread([=]() {
         nn::os::SetThreadName(nn::os::GetCurrentThread(), name_storage);
         nn::os::SetThreadCoreMask(nn::os::GetCurrentThread(), ideal_core, core_affinity);
         entry_point();
     });
 #else
     std::thread new_thread([entry_point]() {
         entry_point();
     });
 #endif
     m_thread.swap(new_thread);
     assert(m_thread.joinable());
     return result::success;
 }
join()
void jobs::internal::thread::join ()
Blocks until thread completes execution.
Returns
Value indicating the success of this function.
Definition at line 105 of file jobs_thread.cpp.
References m_thread.
Referenced by jobs::internal::callback_scheduler::~callback_scheduler(), and ~thread().
 {
     if (m_thread.joinable())
     {
         m_thread.join();
     }
 }
Field Documentation
m_memory_functions
memory_functions jobs::internal::thread::m_memory_functions private
Memory allocation functions provided by the scheduler.
Definition at line 87 of file jobs_thread.h.
m_thread
std::thread jobs::internal::thread::m_thread private
Thread of execution we are encapsulating
Definition at line 90 of file jobs_thread.h.
Referenced by init(), and join().
The documentation for this class was generated from the following files:
C:/Projects/libjobs/inc/jobs_thread.h
C:/Projects/libjobs/src/jobs_thread.cpp