libjobs: jobs::job_handle Class Reference
jobs::job_handle Class Reference
Represents an instance of a job that has been created by the scheduler.
#include <jobs_job.h>
Public Member Functions
job_handle ()
job_handle (const job_handle &other)
Copy constructor.
~job_handle ()
result set_work (const job_entry_point &job_work)
Sets the function to call when this job is executed.
result set_tag (const char *tag)
Sets the descriptive name of this job.
result set_stack_size (size_t stack_size)
Sets the minimum stack size required for this job to run.
result set_priority (priority job_priority)
Sets the priority of this job.
result set_completion_counter (const counter_handle &counter)
Sets a counter that will be incremented when the job completes.
result clear_dependencies ()
Clears the internal dependency list for this job.
result add_predecessor (job_handle other)
Adds a predecessor job that will always execute before this job executes.
result add_successor (job_handle other)
Adds a successor job that will always execute after this job executes.
bool is_pending ()
Determines if this job is pending execution.
bool is_running ()
Determines if this job is currently executing.
bool is_complete ()
Determines if this job has completed.
bool is_mutable ()
Determines if this job can be modified.
bool is_valid ()
Determines if this handle points to a valid job.
result wait (timeout in_timeout=timeout::infinite)
Waits for this job to complete.
result dispatch ()
Dispatches this job, causing it to be queued for execution.
job_handle & operator= (const job_handle &other)
Assignment operator.
bool operator== (const job_handle &rhs) const
Equality operator.
bool operator!= (const job_handle &rhs) const
Inequality operator.
Protected Member Functions
job_handle (scheduler *scheduler, size_t index)
Constructor.
void increase_ref ()
void decrease_ref ()
Private Attributes
scheduler * m_scheduler = nullptr
size_t m_index = 0
Friends
class scheduler
Detailed Description
Represents an instance of a job that has been created by the scheduler.
Job data is owned by the scheduler, be careful accessing handles if the scheduler has been destroyed.
Definition at line 152 of file jobs_job.h.
Constructor & Destructor Documentation
job_handle() [1/3]
jobs::job_handle::job_handle (scheduler * scheduler, size_t index) protected
Constructor.
Parameters
scheduler Scheduler that owns this job.
index Index into the scheduler's job pool where this jobs data is held.
Definition at line 203 of file jobs_job.cpp.
References increase_ref().
     : m_scheduler(scheduler)
     , m_index(index)
 {
     increase_ref();
 }
job_handle() [2/3]
jobs::job_handle::job_handle ()
Constructor
Definition at line 210 of file jobs_job.cpp.
     : m_scheduler(nullptr)
     , m_index(0)
 {
 }
job_handle() [3/3]
jobs::job_handle::job_handle (const job_handle & other)
Copy constructor.
Parameters
other Object to copy.
Definition at line 216 of file jobs_job.cpp.
References increase_ref(), m_index, and m_scheduler.
 {
     m_scheduler = other.m_scheduler;
     m_index = other.m_index;
     increase_ref();
 }
~job_handle()
jobs::job_handle::~job_handle ()
Destructor
Definition at line 224 of file jobs_job.cpp.
References decrease_ref().
 {
     decrease_ref();
 }
Member Function Documentation
add_predecessor()
result jobs::job_handle::add_predecessor (job_handle other)
Adds a predecessor job that will always execute before this job executes.
Care should be taken not to create circular dependencies which will cause jobs to never complete.
Parameters
other Handle of job to add as dependency.
Returns
Value indicating the success of this function.
Definition at line 359 of file jobs_job.cpp.
References jobs::scheduler::add_job_dependency(), jobs::invalid_handle, is_mutable(), is_valid(), m_index, m_scheduler, and jobs::not_mutable.
 {
     if (!is_valid())
     {
         return result::invalid_handle;
     }
     if (!is_mutable())
     {
         return result::not_mutable;
     }
     if (!other.is_valid())
     {
         return result::invalid_handle;
     }
     if (!other.is_mutable())
     {
         return result::not_mutable;
     }
     return m_scheduler->add_job_dependency(m_index, other.m_index);
 }
add_successor()
result jobs::job_handle::add_successor (job_handle other)
Adds a successor job that will always execute after this job executes.
Care should be taken not to create circular dependencies which will cause jobs to never complete.
Parameters
other Handle of job to add as dependency.
Returns
Value indicating the success of this function.
Definition at line 381 of file jobs_job.cpp.
References jobs::scheduler::add_job_dependency(), jobs::invalid_handle, is_mutable(), is_valid(), m_index, m_scheduler, and jobs::not_mutable.
 {
     if (!is_valid())
     {
         return result::invalid_handle;
     }
     if (!is_mutable())
     {
         return result::not_mutable;
     }
     if (!other.is_valid())
     {
         return result::invalid_handle;
     }
     if (!other.is_mutable())
     {
         return result::not_mutable;
     }
     return m_scheduler->add_job_dependency(other.m_index, m_index);
 }
clear_dependencies()
result jobs::job_handle::clear_dependencies ()
Clears the internal dependency list for this job.
Returns
Value indicating the success of this function.
Definition at line 343 of file jobs_job.cpp.
References jobs::scheduler::clear_job_dependencies(), jobs::invalid_handle, is_mutable(), is_valid(), m_index, m_scheduler, jobs::not_mutable, and jobs::success.
 {
     if (!is_valid())
     {
         return result::invalid_handle;
     }
     if (!is_mutable())
     {
         return result::not_mutable;
     }
     m_scheduler->clear_job_dependencies(m_index);
     return result::success;
 }
decrease_ref()
void jobs::job_handle::decrease_ref () protected
Decreases the reference count of this job. When it reaches zero, it will be disposed of and recycled.
Definition at line 247 of file jobs_job.cpp.
References jobs::scheduler::decrease_job_ref_count(), m_index, and m_scheduler.
Referenced by ~job_handle().
 {
     if (m_scheduler != nullptr)
     {
         m_scheduler->decrease_job_ref_count(m_index);
     }
 }
dispatch()
result jobs::job_handle::dispatch ()
Dispatches this job, causing it to be queued for execution.
If dispatching a large number of jobs in one go, consider using the more performant jobs::scheduler::dispatch_batch.
Returns
Value indicating the success of this function.
Definition at line 464 of file jobs_job.cpp.
References jobs::scheduler::dispatch_job(), jobs::invalid_handle, is_mutable(), is_valid(), m_index, m_scheduler, and jobs::not_mutable.
 {
     if (!is_valid())
     {
         return result::invalid_handle;
     }
     if (!is_mutable())
     {
         return result::not_mutable;
     }
     return m_scheduler->dispatch_job(m_index);
 }
increase_ref()
void jobs::job_handle::increase_ref () protected
Increases the reference count of this job.
Definition at line 239 of file jobs_job.cpp.
References jobs::scheduler::increase_job_ref_count(), m_index, and m_scheduler.
Referenced by job_handle(), and operator=().
 {
     if (m_scheduler != nullptr)
     {
         m_scheduler->increase_job_ref_count(m_index);
     }
 }
is_complete()
bool jobs::job_handle::is_complete ()
Determines if this job has completed.
Returns
True if job is completed.
Definition at line 425 of file jobs_job.cpp.
References jobs::internal::completed, jobs::scheduler::get_job_definition(), is_valid(), m_index, m_scheduler, and jobs::internal::job_definition::status.
Referenced by jobs::scheduler::wait_for_job().
 {
     if (!is_valid())
     {
         return false;
     }
     internal::job_definition& definition = m_scheduler->get_job_definition(m_index);
     return (definition.status == internal::job_status::completed);
 }
is_mutable()
bool jobs::job_handle::is_mutable ()
Determines if this job can be modified.
Jobs are only mutable before they have been dispatched, or after they have completed. At no other point should they be modified.
Returns
True if job is mutable.
Definition at line 436 of file jobs_job.cpp.
References jobs::internal::completed, jobs::scheduler::get_job_definition(), jobs::internal::initialized, is_valid(), m_index, m_scheduler, and jobs::internal::job_definition::status.
Referenced by add_predecessor(), add_successor(), clear_dependencies(), dispatch(), set_completion_counter(), set_priority(), set_stack_size(), set_tag(), and set_work().
 {
     if (!is_valid())
     {
         return false;
     }
     internal::job_definition& definition = m_scheduler->get_job_definition(m_index);
     return definition.status == internal::job_status::initialized ||
            definition.status == internal::job_status::completed;
 }
is_pending()
bool jobs::job_handle::is_pending ()
Determines if this job is pending execution.
Jobs pending execution are ones that have been queued, but not yet picked up by a worker thread. Jobs can also return to this state if they are requeued for any reason (such as no fibers being available).
Returns
True if job is pending.
Definition at line 403 of file jobs_job.cpp.
References jobs::scheduler::get_job_definition(), is_valid(), m_index, m_scheduler, jobs::internal::pending, and jobs::internal::job_definition::status.
 {
     if (!is_valid())
     {
         return false;
     }
     internal::job_definition& definition = m_scheduler->get_job_definition(m_index);
     return (definition.status == internal::job_status::pending);
 }
is_running()
bool jobs::job_handle::is_running ()
Determines if this job is currently executing.
A job is only in an executing state when it's fiber is running, waiting jobs are not considered to be running.
Returns
True if job is running.
Definition at line 414 of file jobs_job.cpp.
References jobs::scheduler::get_job_definition(), is_valid(), m_index, m_scheduler, jobs::internal::running, and jobs::internal::job_definition::status.
 {
     if (!is_valid())
     {
         return false;
     }
     internal::job_definition& definition = m_scheduler->get_job_definition(m_index);
     return (definition.status == internal::job_status::running);
 }
is_valid()
bool jobs::job_handle::is_valid ()
Determines if this handle points to a valid job.
Returns
True if handle is valid.
Definition at line 449 of file jobs_job.cpp.
References m_scheduler.
Referenced by add_predecessor(), add_successor(), clear_dependencies(), dispatch(), is_complete(), is_mutable(), is_pending(), is_running(), set_completion_counter(), set_priority(), set_stack_size(), set_tag(), set_work(), and wait().
 {
     return (m_scheduler != nullptr);
 }
operator!=()
bool jobs::job_handle::operator!= (const job_handle & rhs) const
Inequality operator.
Parameters
rhs Object to compare against.
Returns
True if objects are inequal.
Definition at line 483 of file jobs_job.cpp.
 {
     return !(*this == rhs);
 }
operator=()
job_handle & jobs::job_handle::operator= (const job_handle & other)
Assignment operator.
Parameters
other Object to assign.
Returns
Reference to this object.
Definition at line 229 of file jobs_job.cpp.
References increase_ref(), m_index, and m_scheduler.
 {
     m_scheduler = other.m_scheduler;
     m_index = other.m_index;
     increase_ref();
     return *this;
 }
operator==()
bool jobs::job_handle::operator== (const job_handle & rhs) const
Equality operator.
Parameters
rhs Object to compare against.
Returns
True if objects are equal.
Definition at line 478 of file jobs_job.cpp.
References m_index, and m_scheduler.
 {
     return (m_scheduler == rhs.m_scheduler && m_index == rhs.m_index);
 }
set_completion_counter()
result jobs::job_handle::set_completion_counter (const counter_handle & counter)
Sets a counter that will be incremented when the job completes.
Parameters
counter Handle of counter to increment when complete.
Returns
Value indicating the success of this function.
Definition at line 326 of file jobs_job.cpp.
References jobs::internal::job_definition::completion_counter, jobs::scheduler::get_job_definition(), jobs::invalid_handle, is_mutable(), is_valid(), m_index, m_scheduler, jobs::not_mutable, and jobs::success.
 {
     if (!is_valid())
     {
         return result::invalid_handle;
     }
     if (!is_mutable())
     {
         return result::not_mutable;
     }
     internal::job_definition& definition = m_scheduler->get_job_definition(m_index);
     definition.completion_counter = counter;
     return result::success;
 }
set_priority()
result jobs::job_handle::set_priority (priority job_priority)
Sets the priority of this job.
Queues are created for each priority, if you want a job to exist in multiple queues then priorities can be combined together into a bitmask (the job will only be executed once though). Worker thread pools can also be assigned to only work on jobs with specific priorities. Combining both of these can give fine grain control over when and where individual jobs are executed.
Parameters
job_priority Priority to assiociated with this job.
Returns
Value indicating the success of this function.
Definition at line 309 of file jobs_job.cpp.
References jobs::scheduler::get_job_definition(), jobs::invalid_handle, is_mutable(), is_valid(), jobs::internal::job_definition::job_priority, m_index, m_scheduler, jobs::not_mutable, and jobs::success.
 {
     if (!is_valid())
     {
         return result::invalid_handle;
     }
     if (!is_mutable())
     {
         return result::not_mutable;
     }
     internal::job_definition& definition = m_scheduler->get_job_definition(m_index);
     definition.job_priority = job_priority;
     return result::success;
 }
set_stack_size()
result jobs::job_handle::set_stack_size (size_t stack_size)
Sets the minimum stack size required for this job to run.
The scheduler will always attempt to allocate fibers to jobs, from a fiber pool with a smaller stack-size first. If all pools are empty or no pool exists that meets the minimum stack-size, the job will never complete.
Parameters
stack_size Minimum stack size required for this job to run.
Returns
Value indicating the success of this function.
Definition at line 292 of file jobs_job.cpp.
References jobs::scheduler::get_job_definition(), jobs::invalid_handle, is_mutable(), is_valid(), m_index, m_scheduler, jobs::not_mutable, jobs::internal::job_definition::stack_size, and jobs::success.
 {
     if (!is_valid())
     {
         return result::invalid_handle;
     }
     if (!is_mutable())
     {
         return result::not_mutable;
     }
     internal::job_definition& definition = m_scheduler->get_job_definition(m_index);
     definition.stack_size = stack_size;
     return result::success;
 }
set_tag()
result jobs::job_handle::set_tag (const char * tag)
Sets the descriptive name of this job.
Parameters
tag Name of this job.
Returns
Value indicating the success of this function.
Definition at line 272 of file jobs_job.cpp.
References jobs::scheduler::get_job_definition(), jobs::invalid_handle, is_mutable(), is_valid(), JOBS_MIN, m_index, m_scheduler, jobs::internal::job_definition::max_tag_length, jobs::not_mutable, jobs::success, and jobs::internal::job_definition::tag.
 {
     if (!is_valid())
     {
         return result::invalid_handle;
     }
     if (!is_mutable())
     {
         return result::not_mutable;
     }
     internal::job_definition& definition = m_scheduler->get_job_definition(m_index);
     size_t tag_len = strlen(tag);
     size_t to_copy = JOBS_MIN(tag_len, internal::job_definition::max_tag_length - 1);
     strncpy(definition.tag, tag, to_copy);
     definition.tag[to_copy] = '\0';
     return result::success;
 }
set_work()
result jobs::job_handle::set_work (const job_entry_point & job_work)
Sets the function to call when this job is executed.
Parameters
job_work Function to call on execution.
Returns
Value indicating the success of this function.
Definition at line 255 of file jobs_job.cpp.
References jobs::scheduler::get_job_definition(), jobs::invalid_handle, is_mutable(), is_valid(), m_index, m_scheduler, jobs::not_mutable, jobs::success, and jobs::internal::job_definition::work.
 {
     if (!is_valid())
     {
         return result::invalid_handle;
     }
     if (!is_mutable())
     {
         return result::not_mutable;
     }
     internal::job_definition& definition = m_scheduler->get_job_definition(m_index);
     definition.work = job_work;
     return result::success;
 }
wait()
result jobs::job_handle::wait (timeout in_timeout = timeout::infinite)
Waits for this job to complete.
If called from a job this is non-blocking, and will queue the job for execution after the given job completes. If called from any other place, it will block.
Parameters
in_timeout If provided, this function will wait a maximum of this time. If the function returns due to a timeout the result provided will be result::timeout.
Returns
Value indicating the success of this function.
Definition at line 454 of file jobs_job.cpp.
References jobs::invalid_handle, is_valid(), m_scheduler, and jobs::scheduler::wait_for_job().
 {
     if (!is_valid())
     {
         return result::invalid_handle;
     }
     return m_scheduler->wait_for_job(*this, in_timeout);
 }
Friends And Related Function Documentation
scheduler
friend class scheduler friend
Definition at line 156 of file jobs_job.h.
Field Documentation
m_index
size_t jobs::job_handle::m_index = 0 private
Index into the scheduler's job definition pool where this jobs data is held.
Definition at line 378 of file jobs_job.h.
Referenced by add_predecessor(), add_successor(), clear_dependencies(), jobs::scheduler::complete_job(), decrease_ref(), dispatch(), jobs::scheduler::dispatch_batch(), increase_ref(), is_complete(), is_mutable(), is_pending(), is_running(), job_handle(), operator=(), operator==(), jobs::scheduler::requeue_job_batch(), set_completion_counter(), set_priority(), set_stack_size(), set_tag(), set_work(), and jobs::scheduler::wait_for_job().
m_scheduler
scheduler* jobs::job_handle::m_scheduler = nullptr private
Pointer to the owning scheduler of this handle.
Definition at line 375 of file jobs_job.h.
Referenced by add_predecessor(), add_successor(), clear_dependencies(), decrease_ref(), dispatch(), increase_ref(), is_complete(), is_mutable(), is_pending(), is_running(), is_valid(), job_handle(), operator=(), operator==(), set_completion_counter(), set_priority(), set_stack_size(), set_tag(), set_work(), and wait().
The documentation for this class was generated from the following files:
C:/Projects/libjobs/inc/jobs_job.h
C:/Projects/libjobs/src/jobs_job.cpp