libjobs: jobs::profile_scope Class Reference
jobs::profile_scope Class Reference
#include <jobs_job.h>
Public Member Functions
profile_scope (jobs::profile_scope_type type, const char *tag)
~profile_scope ()
Private Attributes
internal::job_context * m_context = nullptr
Detailed Description
Simple RAII type that enters a profile scope on construction and exits it on destruction.
Definition at line 386 of file jobs_job.h.
Constructor & Destructor Documentation
profile_scope()
jobs::profile_scope::profile_scope (jobs::profile_scope_type type, const char * tag)
Todo:
Definition at line 489 of file jobs_job.cpp.
References jobs::internal::job_context::enter_scope(), and jobs::scheduler::get_active_job_context().
 {
     internal::job_context* context = scheduler::get_active_job_context();
     if (context != nullptr)
     {
         context->enter_scope(type, tag, true);
     }
     m_context = context;
 }
~profile_scope()
jobs::profile_scope::~profile_scope ()
Todo:
Definition at line 501 of file jobs_job.cpp.
References jobs::scheduler::get_active_job_context(), and jobs::internal::job_context::leave_scope().
 {
     internal::job_context* context = scheduler::get_active_job_context();
    // assert(context != nullptr);
     // Not sure if this situation is even possible, but make sure we always
     // leave on the same context we enter on.
     assert(context == m_context);
     if (context != nullptr)
     {
         context->leave_scope();
     }
 }
Field Documentation
m_context
internal::job_context* jobs::profile_scope::m_context = nullptr private
Definition at line 389 of file jobs_job.h.
The documentation for this class was generated from the following files:
C:/Projects/libjobs/inc/jobs_job.h
C:/Projects/libjobs/src/jobs_job.cpp