libjobs: jobs::internal::callback_scheduler Class Reference
jobs::internal::callback_scheduler Class Reference
#include <jobs_callback_scheduler.h>
Public Member Functions
callback_scheduler ()
~callback_scheduler ()
result init (jobs::scheduler *scheduler, size_t max_callbacks, const jobs::memory_functions &memory_functions)
Initializes this scheduler.
result schedule (timeout duration, size_t &handle, const callback_scheduler_function &callback)
Schedules a new callback after the given timeout.
result cancel (size_t handle)
Cancels a previously scheduled callback.
Private Member Functions
void run_callbacks ()
uint64_t get_ms_till_next_callback ()
Gets the number of milliseconds until the next callback needs to be invoked.
Private Attributes
jobs::memory_functions m_memory_functions
std::mutex m_schedule_updated_mutex
std::condition_variable m_schedule_updated_cvar
thread * m_callback_thread = nullptr
fixed_pool< callback_definition > m_callback_pool
bool m_shutting_down = false
jobs::scheduler * m_scheduler = nullptr
Detailed Description
Responsible for enqueueing callbacks which will be run after a given timeout.
Definition at line 74 of file jobs_callback_scheduler.h.
Constructor & Destructor Documentation
callback_scheduler()
jobs::internal::callback_scheduler::callback_scheduler ()
Constructor.
Definition at line 30 of file jobs_callback_scheduler.cpp.
 {
 }
~callback_scheduler()
jobs::internal::callback_scheduler::~callback_scheduler ()
Destructor.
Definition at line 34 of file jobs_callback_scheduler.cpp.
References jobs::internal::thread::join(), m_callback_thread, m_memory_functions, m_schedule_updated_cvar, m_schedule_updated_mutex, m_shutting_down, and jobs::memory_functions::user_free.
 {
     m_shutting_down = true;
     // Notify callback thread that its time to shutdown.
     {
         std::unique_lock<std::mutex> lock(m_schedule_updated_mutex);
         m_schedule_updated_cvar.notify_all();
     }
     if (m_callback_thread != nullptr)
     {
         m_callback_thread->join();
         m_memory_functions.user_free(m_callback_thread);
         m_callback_thread = nullptr;
     }
 }
Member Function Documentation
cancel()
result jobs::internal::callback_scheduler::cancel (size_t handle)
Cancels a previously scheduled callback.
Parameters
handle handle of callback to cancel.
Returns
Value indicating the success of this function.
Definition at line 164 of file jobs_callback_scheduler.cpp.
References jobs::internal::callback_definition::active, jobs::already_complete, jobs::internal::callback_definition::callback, jobs::internal::callback_definition::generation, m_callback_pool, m_schedule_updated_mutex, and jobs::success.
Referenced by jobs::counter_handle::remove(), jobs::counter_handle::wait_for(), and jobs::scheduler::wait_for_job().
 {
     std::unique_lock<std::mutex> lock(m_schedule_updated_mutex);
     size_t index = handle % m_callback_pool.capacity();
     size_t generation = (handle / m_callback_pool.capacity());
     callback_definition* def = m_callback_pool.get_index(index);
     if (def->generation != generation)
     {
         return result::already_complete;
     }
     def->callback = nullptr;
     def->active = false;
     m_callback_pool.free(index);
     return result::success;
 }
get_ms_till_next_callback()
uint64_t jobs::internal::callback_scheduler::get_ms_till_next_callback () private
Gets the number of milliseconds until the next callback needs to be invoked.
Returns
Number of milliseconds until next callback must be invoked.
Definition at line 120 of file jobs_callback_scheduler.cpp.
References jobs::internal::callback_definition::active, jobs::internal::callback_definition::duration, jobs::timeout::duration, jobs::internal::stopwatch::get_elapsed_ms(), jobs::timeout::infinite, JOBS_MAX, JOBS_MIN, m_callback_pool, and jobs::internal::callback_definition::stopwatch.
Referenced by init().
 {
     uint64_t time_till_next = UINT64_MAX;
     // @todo: this has unneccessary iteration over free elements, need to maintain an allocated list.
     for (size_t i = 0; i < m_callback_pool.capacity(); i++)
     {
         callback_definition& def =* m_callback_pool.get_index(i);
         if (def.active && def.duration.duration != timeout::infinite.duration)
         {
             size_t remaining = JOBS_MAX(0, def.duration.duration - def.stopwatch.get_elapsed_ms());
             time_till_next = JOBS_MIN(time_till_next, remaining);
         }
     }
     return time_till_next;
 }
init()
result jobs::internal::callback_scheduler::init (jobs::scheduler * scheduler, size_t max_callbacks, const jobs::memory_functions & memory_functions)
Initializes this scheduler.
Parameters
scheduler scheduler that owners this callback scheduler.
max_callbacks maximum number of callbacks that can queued concurrently.
memory_functions User defined functions for allocating and freeing memory.
Returns
Value indicating the success of this function.
Definition at line 52 of file jobs_callback_scheduler.cpp.
References get_ms_till_next_callback(), jobs::internal::thread::init(), m_callback_pool, m_callback_thread, m_memory_functions, m_schedule_updated_cvar, m_schedule_updated_mutex, m_scheduler, m_shutting_down, run_callbacks(), jobs::success, and jobs::memory_functions::user_alloc.
Referenced by jobs::scheduler::init().
 {
     m_scheduler = scheduler;
     m_memory_functions = memory_functions;
     // Init callback pool.
     result result = m_callback_pool.init(m_memory_functions, max_callbacks, [this](callback_definition* instance, size_t index)
     {
         new(instance) callback_definition();
         return result::success;
     });
     if (result != result::success)
     {
         return result;
     }
     // Init main thread.
     m_callback_thread = (thread*)m_memory_functions.user_alloc(sizeof(thread), alignof(thread));
     new(m_callback_thread) thread(m_memory_functions);
     m_callback_thread->init([&]()
     {
         while (!m_shutting_down)
         {
             std::unique_lock<std::mutex> lock(m_schedule_updated_mutex);
             run_callbacks();
             // No callbacks? Wait until we have one.
             uint64_t time_till_next_callback = get_ms_till_next_callback();
             if (m_callback_pool.count() == 0 || time_till_next_callback == UINT64_MAX)
             {
                 m_schedule_updated_cvar.wait(lock);
             }
             // Wait until next callback is due to run.
             else
             {
                 m_schedule_updated_cvar.wait_for(lock, std::chrono::milliseconds(time_till_next_callback));
             }
         }
     }, "Latent Callback Scheduler", 0xFFFF);
     return result::success;
 }
run_callbacks()
void jobs::internal::callback_scheduler::run_callbacks () private
Iterates through all pending callbacks and invokes and destroys those who's timeout has elapsed.
Definition at line 97 of file jobs_callback_scheduler.cpp.
References jobs::internal::callback_definition::active, jobs::internal::callback_definition::callback, jobs::internal::callback_definition::duration, jobs::timeout::duration, jobs::internal::callback_definition::generation, jobs::internal::stopwatch::get_elapsed_ms(), m_callback_pool, and jobs::internal::callback_definition::stopwatch.
Referenced by init().
 {
     // @todo: this has unneccessary iteration over free elements, need to maintain an allocated list.
     for (size_t i = 0; i < m_callback_pool.capacity(); i++)
     {
         callback_definition& def = *m_callback_pool.get_index(i);
         if (def.active)
         {
             if (def.stopwatch.get_elapsed_ms() >= def.duration.duration)
             {
                 def.callback();
                 size_t handle = i + (def.generation * m_callback_pool.capacity());
                 def.callback = nullptr;
                 def.active = false;
                 m_callback_pool.free(i);
             }
         }
     }
 }
schedule()
result jobs::internal::callback_scheduler::schedule (timeout duration, size_t & handle, const callback_scheduler_function & callback)
Schedules a new callback after the given timeout.
Parameters
duration how long before callback is invoked.
handle handle of scheduled callback, can be used to cancel it later.
callback callback that is run after timeout.
Returns
Value indicating the success of this function.
Definition at line 138 of file jobs_callback_scheduler.cpp.
References jobs::internal::callback_definition::active, jobs::internal::callback_definition::callback, jobs::internal::callback_definition::duration, jobs::internal::callback_definition::generation, m_callback_pool, m_schedule_updated_cvar, m_schedule_updated_mutex, m_scheduler, jobs::scheduler, jobs::internal::stopwatch::start(), jobs::internal::callback_definition::stopwatch, jobs::success, jobs::warning, and jobs::scheduler::write_log().
Referenced by jobs::counter_handle::remove(), jobs::counter_handle::wait_for(), and jobs::scheduler::wait_for_job().
 {
     std::unique_lock<std::mutex> lock(m_schedule_updated_mutex);
     size_t index = 0;
     result res = m_callback_pool.alloc(index);
     if (res != result::success)
     {
         m_scheduler->write_log(debug_log_verbosity::warning, debug_log_group::scheduler, "attempt to create latent callback, but pool is empty. Behaviour may be incorrect. Try increasing scheduler::set_max_callbacks.");
         return res;
     }
     callback_definition* def = m_callback_pool.get_index(index);
     def->active = true;
     def->stopwatch.start();
     def->duration = duration;
     def->callback = callback;
     def->generation++;
     m_schedule_updated_cvar.notify_all();
     handle = index + (def->generation * m_callback_pool.capacity());
     return result::success;
 }
Field Documentation
m_callback_pool
fixed_pool<callback_definition> jobs::internal::callback_scheduler::m_callback_pool private
Number of callbacks pending.
Definition at line 142 of file jobs_callback_scheduler.h.
Referenced by cancel(), get_ms_till_next_callback(), init(), run_callbacks(), and schedule().
m_callback_thread
thread* jobs::internal::callback_scheduler::m_callback_thread = nullptr private
Thread used for running callbacks.
Definition at line 139 of file jobs_callback_scheduler.h.
Referenced by init(), and ~callback_scheduler().
m_memory_functions
jobs::memory_functions jobs::internal::callback_scheduler::m_memory_functions private
Memory allocation functions provided by the scheduler.
Definition at line 130 of file jobs_callback_scheduler.h.
Referenced by init(), and ~callback_scheduler().
m_schedule_updated_cvar
std::condition_variable jobs::internal::callback_scheduler::m_schedule_updated_cvar private
Schedule updated condition variable
Definition at line 136 of file jobs_callback_scheduler.h.
Referenced by init(), schedule(), and ~callback_scheduler().
m_schedule_updated_mutex
std::mutex jobs::internal::callback_scheduler::m_schedule_updated_mutex private
Schedule updated mutex
Definition at line 133 of file jobs_callback_scheduler.h.
Referenced by cancel(), init(), schedule(), and ~callback_scheduler().
m_scheduler
jobs::scheduler* jobs::internal::callback_scheduler::m_scheduler = nullptr private
Scheduler that owns this class
Definition at line 148 of file jobs_callback_scheduler.h.
Referenced by init(), and schedule().
m_shutting_down
bool jobs::internal::callback_scheduler::m_shutting_down = false private
True if this class is currently being shutdown.
Definition at line 145 of file jobs_callback_scheduler.h.
Referenced by init(), and ~callback_scheduler().
The documentation for this class was generated from the following files:
C:/Projects/libjobs/inc/jobs_callback_scheduler.h
C:/Projects/libjobs/src/jobs_callback_scheduler.cpp