libjobs: jobs::event_definition Class Reference
jobs::event_definition Class Reference
#include <jobs_event.h>
Public Member Functions
event_definition ()
void reset ()
Data Fields
std::atomic< size_t > ref_count
Detailed Description
Encapsulates all the settings required to manage an event. This is used for internal storage, and shouldn't ever need to be touched by outside code.
Definition at line 42 of file jobs_event.h.
Constructor & Destructor Documentation
event_definition()
jobs::event_definition::event_definition ()
Todo:
Definition at line 27 of file jobs_event.cpp.
References reset().
 {
     reset();
 }
Member Function Documentation
reset()
void jobs::event_definition::reset ()
Todo:
Definition at line 32 of file jobs_event.cpp.
References ref_count.
Referenced by event_definition(), and jobs::scheduler::free_event().
 {
     ref_count = 0;
 }
Field Documentation
ref_count
std::atomic<size_t> jobs::event_definition::ref_count
Todo:
Definition at line 55 of file jobs_event.h.
Referenced by jobs::scheduler::decrease_event_ref_count(), jobs::scheduler::increase_event_ref_count(), and reset().
The documentation for this class was generated from the following files:
C:/Projects/libjobs/inc/jobs_event.h
C:/Projects/libjobs/src/jobs_event.cpp