libjobs: jobs::scheduler Class Reference
jobs::scheduler Class Reference
#include <jobs_scheduler.h>
Data Structures
struct fiber_pool
struct job_queue
struct thread_pool
class worker_thread_state
Public Member Functions
scheduler ()
~scheduler ()
result set_memory_functions (const memory_functions &functions)
Overrides the default memory allocation functions used by the scheduler.
result set_profile_functions (const profile_functions &functions)
Overrides the default profiling functions used by the scheduler.
result set_debug_output (const debug_output_function &function, debug_log_verbosity max_verbosity=debug_log_verbosity::message)
Provides a function which all debug output will be passed.
result set_max_jobs (size_t max_jobs)
Sets the maximum number of jobs.
result set_max_dependencies (size_t max_dependencies)
Sets the maximum number of job dependencies.
result set_max_profile_scopes (size_t max_scopes)
Sets the maximum number of profile scopes that can be tracked.
result set_max_counters (size_t max_counters)
Sets the maximum number of counters that can be created and used for syncronization.
result set_max_callbacks (size_t max_callbacks)
Sets the maximum number of latent callbacks that can be scheduld and used for syncronization.
result add_thread_pool (size_t thread_count, priority job_priorities=priority::all)
Adds a new pool of worker threads to the scheduler.
result add_fiber_pool (size_t fiber_count, size_t stack_size)
Adds a new pool of fibers threads to the scheduler.
result init ()
Initializes this scheduler so it's ready to accept jobs.
result create_job (job_handle &instance)
Creates a new job that can later be enqueued for execution.
result create_event (event_handle &instance, bool auto_reset=false)
Creates a new event that can be used for job syncronization.
result create_counter (counter_handle &instance)
Creates a new counter that can be used for job syncronization.
result dispatch_batch (job_handle *job_array, size_t count)
Dispatches multiple jobs for execution in a single go.
result wait_until_idle (timeout wait_timeout=timeout::infinite)
Waits until all jobs are complete and the schedulers workers are idle.
bool is_idle () const
Returns true if all jobs are complete and the scheduler and it's workers are idle.
Static Public Member Functions
static result sleep (timeout duration=timeout::infinite)
Puts the job or thread to sleep for the given amount of time.
static size_t get_logical_core_count ()
Returns the number of logical cores on the system.
static internal::job_context * get_worker_job_context ()
Gets the context of the worker management fiber running individual jobs.
static internal::job_context * get_active_job_context ()
Gets the context of the job currently running on calling thread.
static bool is_profiling_active ()
Gets if the active scheduler has profiling enabled.
static internal::job_definition * get_active_job_definition ()
Gets the definition of the job currently running on calling thread.
Protected Member Functions
internal::job_definition & get_job_definition (size_t index)
Gets a job definition by its pool index.
void free_job (size_t index)
Free's a job based on its pool index.
void increase_job_ref_count (size_t index)
Increases the reference count of the job based on it's pool index.
void decrease_job_ref_count (size_t index)
Decreases the reference count of the job based on it's pool index.
result dispatch_job (size_t index)
Dispatches a job for execution given it's pool index.
result requeue_job (size_t index)
Requeues a job that has previously been picked up for execution.
result requeue_job_batch (job_handle *job_array, size_t count, size_t job_queues)
Requeues a quantity of jobs that have previously been picked up for execution.
bool get_next_job (size_t &job_index, priority priorities, bool can_block)
Gets the next available job from the highest priority queue available.
bool get_next_job_from_queue (size_t &job_index, job_queue &queue, size_t queue_mask)
Gets the next available job a given queue.
void complete_job (size_t job_index)
Completes the given job index.
result wait_for_job (job_handle job_handle, timeout wait_timeout=timeout::infinite)
Waits for a job to complete.
void write_log (debug_log_verbosity level, debug_log_group group, const char *message,...)
Writes a log message to sink provided by set_debug_output.
void clear_job_dependencies (size_t job_index)
Clears all the dependencies assigned to the given job index.
result add_job_dependency (size_t successor, size_t predecessor)
Creates a given dependency between two jobs.
result allocate_fiber (size_t required_stack_size, size_t &fiber_index, size_t &fiber_pool_index)
Attempts to allocate a fiber out of the available fiber pools with the required stack size.
result free_fiber (size_t fiber_index, size_t fiber_pool_index)
Frees a fiber allocated with allocate_fiber, so it can be recycled later.
void leave_context (internal::job_context &old_context)
Leaves the given job execution context in preperation for entering another.
void enter_context (internal::job_context &new_context)
Enters the given job execution context.
void switch_context (internal::job_context &new_context)
Switches from current job execution context to a new one.
void return_to_worker (internal::job_context &new_context, bool supress_requeue)
Returns execution from the current fiber to the worker thread.
result alloc_scope (internal::profile_scope_definition *&output)
Allocates a profile scope from the pool.
result free_scope (internal::profile_scope_definition *scope)
Frees a profile scope previously allocated with alloc_scope.
internal::counter_definition & get_counter_definition (size_t index)
Gets a counter definition by its pool index.
void free_counter (size_t index)
Free's a counter based on its pool index.
void increase_counter_ref_count (size_t index)
Increases the reference count of the counter based on it's pool index.
void decrease_counter_ref_count (size_t index)
Decreases the reference count of the counter based on it's pool index.
void notify_job_available (size_t job_count=1)
Notifies any workers that a given number of jobs are available for processing.
void notify_job_complete ()
Notifies any waiting workers that a job has completed.
void wait_for_job_available ()
Blocks until a new job has been singled as being available by notify_job_available.
Private Member Functions
void worker_entry_point (size_t pool_index, size_t worker_index, const internal::thread &this_thread, const thread_pool &thread_pool)
void worker_fiber_entry_point (size_t pool_index, size_t worker_index)
bool execute_next_job (priority job_priorities, bool can_block)
void execute_fiber_job ()
Executes the job assinged to the fiber we are running within.
Static Private Member Functions
static void * default_alloc (size_t size, size_t alignment)
static void default_free (void *ptr)
Private Attributes
size_t m_max_jobs = 100
size_t m_max_dependencies = 100
size_t m_max_profile_scopes = 1000
size_t m_max_counters = 100
size_t m_max_callbacks = 100
memory_functions m_raw_memory_functions
memory_functions m_memory_functions
profile_functions m_profile_functions
size_t m_thread_pool_count = 0
thread_pool m_thread_pools [max_thread_pools]
size_t m_worker_count = 0
size_t m_fiber_pool_count = 0
fiber_pool m_fiber_pools [max_fiber_pools]
fiber_pool * m_fiber_pools_sorted_by_stack [max_fiber_pools]
bool m_initialized = false
bool m_destroying = false
bool m_platform_fiber_aware = false
internal::fixed_pool< internal::job_definition > m_job_pool
debug_output_function m_debug_output_function = nullptr
debug_log_verbosity m_debug_output_max_verbosity
char m_log_format_buffer [max_log_size]
char m_log_buffer [max_log_size]
std::mutex m_log_mutex
std::atomic< size_t > m_total_memory_allocated { 0 }
job_queue m_pending_job_queues [(int) priority::count]
std::mutex m_task_available_mutex
std::condition_variable m_task_available_cvar
std::mutex m_task_complete_mutex
std::condition_variable m_task_complete_cvar
std::atomic< size_t > m_active_job_count { 0 }
std::atomic< size_t > m_available_jobs { 0 }
internal::fixed_pool< internal::job_dependency > m_job_dependency_pool
internal::fixed_pool< internal::counter_definition > m_counter_pool
internal::callback_scheduler m_callback_scheduler
internal::fixed_pool< internal::profile_scope_definition > m_profile_scope_pool
worker_thread_state * m_worker_thread_states = nullptr
Static Private Attributes
static const size_t max_thread_pools = 16
static const size_t max_fiber_pools = 16
static const int max_log_size = 256
static thread_local scheduler * m_worker_thread_scheduler {nullptr}
static thread_local worker_thread_state * m_worker_thread_state {nullptr}
static bool m_profiling_active = false
Friends
class job_handle
class event_handle
class counter_handle
class internal::job_context
class internal::callback_scheduler
class internal::profile_scope_internal
Detailed Description
The scheduler is the heart of the library. Its responsible for managing the creation and execution of all threads, fibers and jobs.
Definition at line 100 of file jobs_scheduler.h.
Constructor & Destructor Documentation
scheduler()
jobs::scheduler::scheduler ()
Default constructor.
Definition at line 81 of file jobs_scheduler.cpp.
References default_alloc(), default_free(), jobs::profile_functions::enter_scope, jobs::profile_functions::leave_scope, m_profile_functions, m_raw_memory_functions, jobs::memory_functions::user_alloc, and jobs::memory_functions::user_free.
 {
     m_raw_memory_functions.user_alloc = default_alloc;
     m_raw_memory_functions.user_free = default_free;
     m_profile_functions.enter_scope = nullptr;
     m_profile_functions.leave_scope = nullptr;
 }
~scheduler()
jobs::scheduler::~scheduler ()
Destructor.
Definition at line 90 of file jobs_scheduler.cpp.
References jobs::error, m_destroying, m_fiber_pool_count, m_fiber_pools, m_memory_functions, m_thread_pool_count, m_thread_pools, m_worker_thread_states, notify_job_available(), jobs::scheduler::thread_pool::pool, jobs::scheduler::fiber_pool::pool, jobs::scheduler, jobs::memory_functions::user_free, and write_log().
 {
     m_destroying = true;
     // Wake up all threads.
     notify_job_available(0xFFFF);
     // Join all threads.
     for (size_t i = 0; i < m_thread_pool_count; i++)
     {
         thread_pool& pool = m_thread_pools[i];
         for (size_t j = 0; j < pool.pool.capacity(); j++)
         {
             pool.pool.get_index(j)->join();
         }
     }
     // Destroy all fibers
     // Allocate fibers.
     for (size_t i = 0; i < m_fiber_pool_count; i++)
     {
         fiber_pool& pool = m_fiber_pools[i];
         for (size_t j = 0; j < pool.pool.capacity(); j++)
         {
             pool.pool.get_index(j)->destroy();
         }
     }
     // Destroy all worker states.
     if (m_worker_thread_states != nullptr)
     {
         m_memory_functions.user_free(m_worker_thread_states);
         m_worker_thread_states = nullptr;
     }
     // Platform destruction.
 #if defined(JOBS_PLATFORM_PS4)
     // Ensure fiber prx is loaded.
     if (m_owns_scesysmodule_fiber)
     {
         if (sceSysmoduleUnloadModule(SCE_SYSMODULE_FIBER) != SCE_OK)
         {
             write_log(debug_log_verbosity::error, debug_log_group::scheduler, "failed to unload SCE_SYSMODULE_FIBER");
         }
         m_owns_scesysmodule_fiber = false;
     }
 #endif
 }
Member Function Documentation
add_fiber_pool()
result jobs::scheduler::add_fiber_pool (size_t fiber_count, size_t stack_size)
Adds a new pool of fibers threads to the scheduler.
This creates a new pool of fibers that are used to hold the state of currently executing jobs.
Fibers hold the state of a currently executing job, the maximum concurrently running/sleeping/waiting jobs is equal to that of the number of fibers.
New jobs will always allocate a fiber from the pool with the smallest stack size that fulfills its requested stack size.
Multiple pools with different granularities of stack sizes should be created to reduce the memory overhead. Creating a single large pool with a large stack size will result in unnecessarily high memory usage (as the memory allocated is equal to fiber_count * stack_size).
Parameters
fiber_count Number of fibers to create in the new pool.
stack_size Size of the stack each fiber is allocated.
Returns
Value indicating the success of this function.
Definition at line 277 of file jobs_scheduler.cpp.
References jobs::already_initialized, jobs::scheduler::fiber_pool::fiber_count, m_fiber_pool_count, m_fiber_pools, m_initialized, max_fiber_pools, jobs::maximum_exceeded, jobs::scheduler::fiber_pool::stack_size, and jobs::success.
 {
     if (m_initialized)
     {
         return result::already_initialized;
     }
     if (m_fiber_pool_count == max_fiber_pools)
     {
         return result::maximum_exceeded;
     }
     fiber_pool& pool = m_fiber_pools[m_fiber_pool_count++];
     pool.stack_size = stack_size;
     pool.fiber_count = fiber_count;
     return result::success;
 }
add_job_dependency()
result jobs::scheduler::add_job_dependency (size_t successor, size_t predecessor) protected
Creates a given dependency between two jobs.
Parameters
successor Index of job that should complete last.
predecessor Index of job that should complete first.
Returns
Value indicating the success of this function.
Definition at line 717 of file jobs_scheduler.cpp.
References jobs::internal::job_definition::first_predecessor, jobs::internal::job_definition::first_successor, get_job_definition(), jobs::job, jobs::internal::job_dependency::job, job_handle, m_job_dependency_pool, jobs::internal::job_dependency::next, jobs::internal::job_definition::pending_predecessors, jobs::success, jobs::warning, and write_log().
Referenced by jobs::job_handle::add_predecessor(), and jobs::job_handle::add_successor().
 {
     internal::job_definition& successor_def = get_job_definition(successor);
     internal::job_definition& predecessor_def = get_job_definition(predecessor);
     size_t successor_dep_index;
     size_t predecessor_dep_index;
     result res1 = m_job_dependency_pool.alloc(successor_dep_index);
     result res2 = m_job_dependency_pool.alloc(predecessor_dep_index);
     if (res1 != result::success || res2 != result::success)
     {
         write_log(debug_log_verbosity::warning, debug_log_group::job, "attempt to add job dependency, but dependency pool is empty, if unhandled may cause incorrect job ordering behaviour. Try increasing scheduler::set_max_dependencies.");
         return res1;
     }
     internal::job_dependency* successor_dep = m_job_dependency_pool.get_index(successor_dep_index);
     successor_dep->job = job_handle(this, successor);
     successor_dep->next = predecessor_def.first_successor;
     internal::job_dependency* predecessor_dep = m_job_dependency_pool.get_index(predecessor_dep_index);
     predecessor_dep->job = job_handle(this, predecessor);
     predecessor_dep->next = successor_def.first_predecessor;
     successor_def.first_predecessor = predecessor_dep;
     predecessor_def.first_successor = successor_dep;
     successor_def.pending_predecessors++;
     return result::success;
 }
add_thread_pool()
result jobs::scheduler::add_thread_pool (size_t thread_count, priority job_priorities = priority::all)
Adds a new pool of worker threads to the scheduler.
This creates a new pool of worker threads that can execute jobs queued on this scheduler. Thread pools can be assigned multiple job priorities, and will only execute jobs queued with one of these priorities. This can be used to segregate long-running and time-critical work onto different threads.
Parameters
thread_count Number of threads to create in the new pool.
job_priorities Bitmask of all the job priorities this thread pool will execute.
Returns
Value indicating the success of this function.
Definition at line 259 of file jobs_scheduler.cpp.
References jobs::already_initialized, jobs::scheduler::thread_pool::job_priorities, m_initialized, m_thread_pool_count, m_thread_pools, max_thread_pools, jobs::maximum_exceeded, jobs::success, and jobs::scheduler::thread_pool::thread_count.
 {
     if (m_initialized)
     {
         return result::already_initialized;
     }
     if (m_thread_pool_count == max_thread_pools)
     {
         return result::maximum_exceeded;
     }
     thread_pool& pool = m_thread_pools[m_thread_pool_count++];
     pool.job_priorities = job_priorities;
     pool.thread_count = thread_count;
     return result::success;
 }
alloc_scope()
result jobs::scheduler::alloc_scope (internal::profile_scope_definition *& output) protected
Allocates a profile scope from the pool.
Parameters
output Reference to storage location of allocated scope.
Returns
Value indicating the success of this function.
Definition at line 1504 of file jobs_scheduler.cpp.
References m_profile_scope_pool, jobs::success, and WorkerThreadState.
Referenced by jobs::internal::job_context::enter_scope().
 {
     // We maintain a small thread-local list for speedy allocations.
     result res = WorkerThreadState.profile_scope_cache.pop(output);
     if (res == result::success)
     {
         return res;
     }
     // Otherwise fall back to the main synchronized pool.
     size_t index = 0;
     res = m_profile_scope_pool.alloc(index);
     if (res != result::success)
     {
         return res;
     }
     output = m_profile_scope_pool.get_index(index);
     return result::success;
 }
allocate_fiber()
result jobs::scheduler::allocate_fiber (size_t required_stack_size, size_t & fiber_index, size_t & fiber_pool_index) protected
Attempts to allocate a fiber out of the available fiber pools with the required stack size.
Allocation will always be attempted from pools with the smallest stack size first.
Parameters
required_stack_size Minimum stack size required for allocated fiber.
fiber_index Reference to store index of allocated fiber.
fiber_pool_index Reference to store pool index of allocated fiber.
Returns
Value indicating the success of this function.
Definition at line 1278 of file jobs_scheduler.cpp.
References jobs::error, jobs::job, m_fiber_pool_count, m_fiber_pools_sorted_by_stack, jobs::maximum_exceeded, jobs::out_of_fibers, jobs::scheduler::fiber_pool::pool, jobs::scheduler::fiber_pool::stack_size, jobs::success, jobs::verbose, and write_log().
Referenced by execute_next_job().
 {
     bool any_suitable_pools = false;
     for (size_t i = 0; i < m_fiber_pool_count; i++)
     {
         fiber_pool& pool = *m_fiber_pools_sorted_by_stack[i];
         if (pool.stack_size >= required_stack_size)
         {
             any_suitable_pools = true;
             result res = pool.pool.alloc(fiber_index);
             if (res == result::success)
             {
 #if defined(JOBS_USE_VERBOSE_LOGGING)
                 write_log(debug_log_verbosity::verbose, debug_log_group::job, "fiber allocated, pool=%zi index=%zi", i, fiber_index);
 #endif
                 fiber_pool_index = i;
                 return result::success;
             }
         }
     }
     if (!any_suitable_pools)
     {
         write_log(debug_log_verbosity::error, debug_log_group::job, "no fiber pools have large enough stack size to fulfil request for of %zi. job will never complete.", required_stack_size);
         return result::maximum_exceeded;
     }
     else
     {
         return result::out_of_fibers;
     }
 }
clear_job_dependencies()
void jobs::scheduler::clear_job_dependencies (size_t job_index) protected
Clears all the dependencies assigned to the given job index.
Parameters
job_index Job index to clear dependencies for.
Definition at line 678 of file jobs_scheduler.cpp.
References jobs::internal::job_definition::first_predecessor, jobs::internal::job_definition::first_successor, get_job_definition(), m_job_dependency_pool, jobs::internal::job_dependency::next, jobs::internal::job_dependency::pool_index, and jobs::internal::job_dependency::reset().
Referenced by jobs::job_handle::clear_dependencies(), complete_job(), and free_job().
 {
     internal::job_definition& def = get_job_definition(job_index);
     // Clear up predecessors.
     {
         internal::job_dependency* dep = def.first_predecessor;
         while (dep != nullptr)
         {
             size_t pool_index = dep->pool_index;
             internal::job_dependency* next = dep->next;
             dep->reset();
             m_job_dependency_pool.free(pool_index);
             dep = next;
         }
         def.first_predecessor = nullptr;
     }
     // Clear up successors.
     {
         internal::job_dependency* dep = def.first_successor;
         while (dep != nullptr)
         {
             size_t pool_index = dep->pool_index;
             internal::job_dependency* next = dep->next;
             dep->reset();
             m_job_dependency_pool.free(pool_index);
             dep = next;
         }
         def.first_successor = nullptr;
     }
 }
complete_job()
void jobs::scheduler::complete_job (size_t job_index) protected
Completes the given job index.
When called this will perform any completion processing required by the job, this includes waking up successors, incrementing counters and so on.
Parameters
job_index Job index to complete.
Definition at line 1129 of file jobs_scheduler.cpp.
References jobs::counter_handle::add(), clear_job_dependencies(), jobs::internal::completed, jobs::internal::job_definition::completion_counter, jobs::internal::job_definition::context, decrease_job_ref_count(), jobs::internal::job_context::fiber_index, jobs::internal::job_context::fiber_pool_index, jobs::internal::job_definition::first_successor, free_fiber(), get_job_definition(), jobs::internal::job_context::has_fiber, jobs::internal::job_definition::index, jobs::internal::initialized, jobs::counter_handle::is_valid(), jobs::internal::job_dependency::job, jobs_profile_scope, JOBS_YIELD, m_active_job_count, jobs::job_handle::m_index, jobs::internal::job_dependency::next, notify_job_complete(), jobs::internal::pending, jobs::internal::job_definition::pending_predecessors, requeue_job(), jobs::internal::running, jobs::internal::job_definition::status, jobs::internal::multiple_writer_single_reader_list< data_type >::iterator::value(), jobs::internal::job_definition::wait_list, jobs::internal::waiting_on_job, and jobs::worker.
Referenced by execute_next_job().
 {
     jobs_profile_scope(profile_scope_type::worker, "scheduler::complete_job", this);
     internal::job_definition& def = get_job_definition(job_index);
     bool needs_to_wake_up_successors = false;
     assert(def.status == internal::job_status::running);
     def.status = internal::job_status::completed;
     // For each job waiting on this one, set it back to pending and requeue it.
     {
         internal::multiple_writer_single_reader_list<internal::job_definition*>::iterator iter;
         for (def.wait_list.iterate(iter); iter; iter++)
         {
             internal::job_definition* wait_def = iter.value();
             internal::job_status expected = internal::job_status::waiting_on_job;
             if (wait_def->status.compare_exchange_strong(expected, internal::job_status::pending))
             {
                 requeue_job(wait_def->index);
             }
         }
     }
     // For each successor, reduce its pending predecessor count.
     internal::job_dependency* dep = def.first_successor;
     while (dep != nullptr)
     {
         internal::job_definition& successor_def = get_job_definition(dep->job.m_index);
         size_t num = --successor_def.pending_predecessors;
         if (num <= 0)
         {
             // Successor is still waiting on dispatch. We can't enqueue it until its
             // initial setup has completed.
             while (successor_def.status == internal::job_status::initialized)
             {
                 // Note: if this is showing up in your profiles, you've fucked up somewhere and not dispatched a dependent job.
                 JOBS_YIELD();
             }
             requeue_job(successor_def.index);
             needs_to_wake_up_successors = true;
         }
         dep = dep->next;
     }
     // Clear up the fiber now, even if our handle is going to hang around for a while.
     if (def.context.has_fiber)
     {
         free_fiber(def.context.fiber_index, def.context.fiber_pool_index);
         def.context.has_fiber = false;
     }
     // Clean up dependencies, we no longer need them at this point.
     clear_job_dependencies(job_index);
     // Increase the completion counter.
     if (def.completion_counter.is_valid())
     {
         def.completion_counter.add(1);
     }
     // Remove the ref count we added on dispatch.
     decrease_job_ref_count(job_index);
     // Keep track of number of active jobs for idle monitoring.
     m_active_job_count--;
     // Wake up anyone waiting for tasks to complete.
     {
         notify_job_complete();
     }
 }
create_counter()
result jobs::scheduler::create_counter (counter_handle & instance)
Creates a new counter that can be used for job syncronization.
Parameters
instance On success the created counter will be stored here.
Returns
Value indicating the success of this function.
Definition at line 569 of file jobs_scheduler.cpp.
References counter_handle, get_counter_definition(), m_counter_pool, jobs::scheduler, jobs::success, jobs::warning, and write_log().
Referenced by create_event().
 {
     size_t index = 0;
     result res = m_counter_pool.alloc(index);
     if (res != result::success)
     {
         write_log(debug_log_verbosity::warning, debug_log_group::scheduler, "attempt to create counter, but counter pool is empty. Try increasing scheduler::set_max_counters.");
         return res;
     }
     internal::counter_definition& def = get_counter_definition(index);
     instance = counter_handle(this, index);
     return result::success;
 }
create_event()
result jobs::scheduler::create_event (event_handle & instance, bool auto_reset = false)
Creates a new event that can be used for job syncronization.
Parameters
instance On success the created event will be stored here.
auto_reset If the event automatically resets after being signalled, or needs to be manually reset.
Returns
Value indicating the success of this function.
Definition at line 555 of file jobs_scheduler.cpp.
References create_counter(), event_handle, and jobs::success.
 {
     counter_handle counter;
     result res = create_counter(counter);
     if (res != result::success)
     {
         return res;
     }
     instance = event_handle(this, counter, auto_reset);
     return result::success;
 }
create_job()
result jobs::scheduler::create_job (job_handle & instance)
Creates a new job that can later be enqueued for execution.
Ones a job is fully created and setup, it can be queued for execution by calling queue_job.
Parameters
instance On success the created job will be stored here.
Returns
Value indicating the success of this function.
Definition at line 524 of file jobs_scheduler.cpp.
References get_job_definition(), job_handle, m_job_pool, jobs::scheduler, jobs::success, jobs::warning, and write_log().
 {
     size_t index = 0;
     result res = m_job_pool.alloc(index);
     if (res != result::success)
     {
         write_log(debug_log_verbosity::warning, debug_log_group::scheduler, "attempt to create job, but job pool is empty. Try increasing scheduler::set_max_jobs.");
         return res;
     }
     internal::job_definition& def = get_job_definition(index);
     instance = job_handle(this, index);
     return result::success;
 }
decrease_counter_ref_count()
void jobs::scheduler::decrease_counter_ref_count (size_t index) protected
Decreases the reference count of the counter based on it's pool index.
If the reference count goes to 0 the counter will be automatically freed.
Parameters
index Index of counter to decrement ref count of.
Definition at line 600 of file jobs_scheduler.cpp.
References free_counter(), get_counter_definition(), and jobs::internal::counter_definition::ref_count.
Referenced by jobs::counter_handle::decrease_ref().
 {
     internal::counter_definition& def = get_counter_definition(index);
     size_t new_ref_count = --def.ref_count;
     if (new_ref_count == 0)
     {
         free_counter(index);
     }
 }
decrease_job_ref_count()
void jobs::scheduler::decrease_job_ref_count (size_t index) protected
Decreases the reference count of the job based on it's pool index.
If the reference count goes to 0 the job will be automatically freed.
Parameters
index Index of counter to decrement ref count of.
Definition at line 668 of file jobs_scheduler.cpp.
References free_job(), get_job_definition(), and jobs::internal::job_definition::ref_count.
Referenced by complete_job(), and jobs::job_handle::decrease_ref().
 {
     internal::job_definition& def = get_job_definition(index);
     size_t new_ref_count = def.ref_count.fetch_sub(1, std::memory_order_relaxed) - 1;
     if (new_ref_count == 0)
     {
         free_job(index);
     }
 }
default_alloc()
void * jobs::scheduler::default_alloc (size_t size, size_t alignment) static private
Default memory allocation function
Definition at line 142 of file jobs_scheduler.cpp.
Referenced by scheduler().
 {
 #if defined(JOBS_PLATFORM_WINDOWS) || defined(JOBS_PLATFORM_XBOX_ONE)
     void* ptr = _aligned_malloc(size, alignment);
 #else
     void* ptr = memalign(alignment, size);
 #endif
     return ptr;
 }
default_free()
void jobs::scheduler::default_free (void * ptr) static private
Default memory deallocation function
Definition at line 152 of file jobs_scheduler.cpp.
Referenced by scheduler().
 {
 #if defined(JOBS_PLATFORM_WINDOWS) || defined(JOBS_PLATFORM_XBOX_ONE)
     _aligned_free(ptr);
 #else
     free(ptr);
 #endif
 }
dispatch_batch()
result jobs::scheduler::dispatch_batch (job_handle * job_array, size_t count)
Dispatches multiple jobs for execution in a single go.
This function combines the overhead for dispatching jobs, reducing the overall cost to a minimum.
Parameters
job_array Pointer to array of jobs to dispatch.
count Number of jobs in array.
Returns
Value indicating the success of this function.
Definition at line 902 of file jobs_scheduler.cpp.
References jobs::already_dispatched, jobs::internal::completed, jobs::internal::job_definition::context, jobs::count, get_job_definition(), increase_job_ref_count(), jobs::internal::initialized, jobs::job, jobs::internal::job_context::job_def, jobs::internal::job_definition::job_priority, jobs_profile_scope, m_active_job_count, jobs::job_handle::m_index, jobs::internal::pending, jobs::internal::job_context::queues_contained_in, requeue_job_batch(), jobs::internal::job_definition::status, jobs::success, jobs::warning, jobs::worker, and write_log().
 {
     jobs_profile_scope(profile_scope_type::worker, "scheduler::dispatch_batch", this);
     size_t job_queues = 0;
     // Jobs always get an extra ref count until they are complete so they don't get freed while running.
     for (size_t i = 0; i < count; i++)
     {
         size_t index = job_array[i].m_index;
         internal::job_definition& def = get_job_definition(index);
         internal::job_status status = def.status.load(std::memory_order_relaxed);
         if (status != internal::job_status::initialized &&
             status != internal::job_status::completed)
         {
             write_log(debug_log_verbosity::warning, debug_log_group::job, "attempt to dispatch job that is still running, index=%zi", index);
             return result::already_dispatched;
         }
         increase_job_ref_count(index);
         def.status.store(internal::job_status::pending, std::memory_order_relaxed);
         def.context.queues_contained_in = 0;
         def.context.job_def = &def;
         job_queues |= (size_t)def.job_priority;
     }
     // Keep track of number of active jobs for idle monitoring.
     m_active_job_count.fetch_add(count);
     // Dispatch valid jobs.
     requeue_job_batch(job_array, count, job_queues);
     return result::success;
 }
dispatch_job()
result jobs::scheduler::dispatch_job (size_t index) protected
Dispatches a job for execution given it's pool index.
Parameters
index Index of job to dispatch.
Returns
Value indicating the success of this function.
Definition at line 865 of file jobs_scheduler.cpp.
References jobs::already_dispatched, jobs::internal::completed, jobs::internal::job_definition::context, get_job_definition(), increase_job_ref_count(), jobs::internal::initialized, jobs::job, jobs::internal::job_context::job_def, jobs_profile_scope, m_active_job_count, jobs::internal::pending, jobs::internal::job_definition::pending_predecessors, jobs::internal::job_context::queues_contained_in, requeue_job(), jobs::internal::job_definition::status, jobs::success, jobs::verbose, jobs::warning, jobs::worker, and write_log().
Referenced by jobs::job_handle::dispatch().
 {
     jobs_profile_scope(profile_scope_type::worker, "scheduler::dispatch_job", this);
     internal::job_definition& def = get_job_definition(index);
     internal::job_status status = def.status.load(std::memory_order_relaxed);
     if (status != internal::job_status::initialized &&
         status != internal::job_status::completed)
     {
         write_log(debug_log_verbosity::warning, debug_log_group::job, "attempt to dispatch job that is still running, index=%zi", index);
         return result::already_dispatched;
     }
 #if defined(JOBS_USE_VERBOSE_LOGGING)
     write_log(debug_log_verbosity::verbose, debug_log_group::job, "dispatching job, index=%zi", index);
 #endif
     // Jobs always get an extra ref count until they are complete so they don't get freed while running.
     increase_job_ref_count(index);
     def.status.store(internal::job_status::pending, std::memory_order_relaxed);
     def.context.queues_contained_in = 0;
     def.context.job_def = &def;
     // Keep track of number of active jobs for idle monitoring.
     m_active_job_count++;
     // If not dependent on anything, enqueue into queues right now.
     // Put job into a job queue for each priority it holds (not sure why you would want multiple priorities, but might as well support it ...).
     if (def.pending_predecessors == 0)
     {
         requeue_job(index);
     }
     return result::success;
 }
enter_context()
void jobs::scheduler::enter_context (internal::job_context & new_context) protected
Enters the given job execution context.
Entering a context performs various bits of cleanup worker, such as pushing profiler markers onto the thread stack and resuming from where the context fiber left of.
Parameters
new_context Context to enter.
Definition at line 622 of file jobs_scheduler.cpp.
References jobs::profile_functions::enter_scope, jobs::internal::job_context::fiber_index, jobs::internal::job_context::fiber_pool_index, jobs::internal::job_context::is_fiber_raw, m_fiber_pools_sorted_by_stack, m_platform_fiber_aware, m_profile_functions, jobs::internal::profile_scope_definition::next, jobs::scheduler::fiber_pool::pool, jobs::internal::job_context::profile_stack_head, jobs::internal::job_context::raw_fiber, jobs::internal::fiber::switch_to(), jobs::internal::profile_scope_definition::tag, jobs::internal::profile_scope_definition::type, and WorkerThreadState.
Referenced by switch_context().
 {
     internal::fiber* job_fiber = nullptr;
     if (context.is_fiber_raw)
     {
         job_fiber = &context.raw_fiber;
     }
     else
     {
         job_fiber = m_fiber_pools_sorted_by_stack[context.fiber_pool_index]->pool.get_index(context.fiber_index);
     }
     // Recreate the profile scope stack.
     if (m_profile_functions.enter_scope != nullptr && !m_platform_fiber_aware)
     {
         internal::profile_scope_definition* scope = context.profile_stack_head;
         while (scope != nullptr)
         {
             m_profile_functions.enter_scope(scope->type, scope->tag);
             scope = scope->next;
         }
     }
     WorkerThreadState.active_job_context = &context;
     job_fiber->switch_to();
 }
execute_fiber_job()
void jobs::scheduler::execute_fiber_job () private
Executes the job assinged to the fiber we are running within.
Warning: This is set to force no-inlne to ensure thread_local variables read inside it are not cached on the stack between invocation, which can be problematic with fibers which may return/re-enter at unknown points, which can cause the compiler to cache variables for incorrect lifetimes. This is not needed on windows as we use the /GT flag to enable fiber-safe optimizations.
Definition at line 840 of file jobs_scheduler.cpp.
References jobs::scheduler::worker_thread_state::active_job_context, jobs::scheduler::worker_thread_state::cloned_job_index, jobs::internal::job_context::enter_scope(), jobs::fiber, get_job_definition(), jobs::job, jobs::scheduler::worker_thread_state::job_completed, jobs::scheduler::worker_thread_state::job_index, jobs::internal::job_context::leave_scope(), jobs::internal::job_definition::tag, jobs::verbose, jobs::internal::job_definition::work, WorkerThreadState, and write_log().
Referenced by worker_fiber_entry_point().
 {
     worker_thread_state& state = WorkerThreadState;
     internal::job_definition& def = get_job_definition(state.job_index);
 #if defined(JOBS_USE_VERBOSE_LOGGING)
     // Execute the job assigned to this thread.
     write_log(debug_log_verbosity::verbose, debug_log_group::job, "executing job, state=%p index=%zi/%zi", &state, state.job_index, state.cloned_job_index.load());
 #endif
     state.active_job_context->enter_scope(profile_scope_type::fiber, true, def.tag);
     def.work();
 #if defined(JOBS_USE_VERBOSE_LOGGING)
     // Execute the job assigned to this thread.
     write_log(debug_log_verbosity::verbose, debug_log_group::job, "finished executing job, state=%p index=%zi/%zi", &state, state.job_index, state.cloned_job_index.load());
 #endif
     state.job_completed = true;
     state.active_job_context->leave_scope();
 }
execute_next_job()
bool jobs::scheduler::execute_next_job (priority job_priorities, bool can_block) private
Executes the next job in the work queue.
Parameters
job_priorities Bitmask of priorities that can be executed.
can_block True if the function can block until a job is available to execute.
Returns
True if a job was executed.
Definition at line 1206 of file jobs_scheduler.cpp.
References allocate_fiber(), complete_job(), jobs::internal::job_definition::context, jobs::internal::job_context::fiber_index, jobs::internal::job_context::fiber_pool_index, get_job_definition(), get_next_job(), jobs::internal::job_context::has_fiber, jobs::job, jobs::scheduler::worker_thread_state::job_index, m_fiber_pools_sorted_by_stack, jobs::scheduler::fiber_pool::pool, requeue_job(), jobs::internal::job_definition::stack_size, jobs::success, switch_context(), jobs::verbose, jobs::warning, WorkerThreadState, and write_log().
Referenced by wait_for_job(), wait_until_idle(), and worker_entry_point().
 {
     auto& thread_state = WorkerThreadState;
     // Grab next job to run.
     size_t job_index;
     if (get_next_job(job_index, job_priorities, can_block))
     {
         internal::job_definition& def = get_job_definition(job_index);
         // If job does not have a fiber allocated, grab a fiber to run job on.
         if (!def.context.has_fiber)
         {
             result res = allocate_fiber(def.stack_size, def.context.fiber_index, def.context.fiber_pool_index);
             if (res == result::success)
             {
                 def.context.has_fiber = true;
             }
             else
             {
                 write_log(debug_log_verbosity::warning, debug_log_group::job, "requeuing job as no fibers available, index=%zi", job_index);
                 // @todo: don't requeue, this results in churn, put it in a queue to be requeued on job-completion.
                 // No fiber available? Back into the queue you go.
                 requeue_job(job_index);
                 // There is further work to do so return true here.
                 return true;
             }
         }
         // Perform the old switcharoo to fiber land.
         thread_state.job_index = job_index;
         thread_state.cloned_job_index = job_index;
         thread_state.job_completed = false;
         thread_state.job_supress_requeue = false;
         internal::fiber* job_fiber = m_fiber_pools_sorted_by_stack[def.context.fiber_pool_index]->pool.get_index(def.context.fiber_index);
 #if defined(JOBS_USE_VERBOSE_LOGGING)
         write_log(debug_log_verbosity::verbose, debug_log_group::job, "switching state=%p job=%zi/%zi fiber=%zi:%zi", &thread_state, thread_state.job_index, thread_state.cloned_job_index.load(), def.context.fiber_pool_index, def.context.fiber_index);
 #endif
         switch_context(def.context);
 #if defined(JOBS_USE_VERBOSE_LOGGING)
         write_log(debug_log_verbosity::verbose, debug_log_group::job, "returning from state=%p job=%zi/%zi fiber=%zi:%zi completed=%s", &thread_state, thread_state.job_index, thread_state.cloned_job_index.load(), def.context.fiber_pool_index, def.context.fiber_index, thread_state.job_completed ? "true" : "false");
 #endif
         // If not complete yet, requeue, we probably have some sync point/dependencies to deal with.
         if (!thread_state.job_completed)
         {
             if (!thread_state.job_supress_requeue)
             {
                 // No fiber available? Back into the queue you go.
                 requeue_job(thread_state.job_index);
             }
             // There is further work to do so return true here.
             return true;
         }
         // Else mark as completed.
         else
         {
             complete_job(thread_state.job_index);
         }
         return true;
     }
     return false;
 }
free_counter()
void jobs::scheduler::free_counter (size_t index) protected
Free's a counter based on its pool index.
The counter will be recycled later.
Parameters
index Index of counter to free.
Definition at line 586 of file jobs_scheduler.cpp.
References get_counter_definition(), m_counter_pool, and jobs::internal::counter_definition::reset().
Referenced by decrease_counter_ref_count().
 {
     internal::counter_definition& def = get_counter_definition(index);
     def.reset();
     m_counter_pool.free(index);
 }
free_fiber()
result jobs::scheduler::free_fiber (size_t fiber_index, size_t fiber_pool_index) protected
Frees a fiber allocated with allocate_fiber, so it can be recycled later.
Parameters
fiber_index Index of allocated fiber.
fiber_pool_index Pool index of allocated fiber.
Returns
Value indicating the success of this function.
Definition at line 1313 of file jobs_scheduler.cpp.
References m_fiber_pools_sorted_by_stack, jobs::scheduler::fiber_pool::pool, and jobs::success.
Referenced by complete_job(), and free_job().
 {
     fiber_pool& pool = *m_fiber_pools_sorted_by_stack[fiber_pool_index];
     pool.pool.free(fiber_index);
     return result::success;
 }
free_job()
void jobs::scheduler::free_job (size_t index) protected
Free's a job based on its pool index.
The job will bre recycled later.
Parameters
index Index of job to free.
Definition at line 541 of file jobs_scheduler.cpp.
References clear_job_dependencies(), jobs::internal::job_definition::context, jobs::internal::job_context::fiber_index, jobs::internal::job_context::fiber_pool_index, free_fiber(), get_job_definition(), jobs::internal::job_context::has_fiber, m_job_pool, and jobs::internal::job_definition::reset().
Referenced by decrease_job_ref_count().
 {
     internal::job_definition& def = get_job_definition(index);
     if (def.context.has_fiber)
     {
         free_fiber(def.context.fiber_index, def.context.fiber_pool_index);
         def.context.has_fiber = false;
     }
     clear_job_dependencies(index);
     def.reset();
     m_job_pool.free(index);
 }
free_scope()
result jobs::scheduler::free_scope (internal::profile_scope_definition * scope) protected
Frees a profile scope previously allocated with alloc_scope.
Parameters
scope Scope to free.
Returns
Value indicating the success of this function.
Definition at line 1525 of file jobs_scheduler.cpp.
References m_profile_scope_pool, jobs::success, and WorkerThreadState.
Referenced by jobs::internal::job_context::leave_scope().
 {
     // Free to the small thread-local list for speedy allocations
     result res = WorkerThreadState.profile_scope_cache.push(scope);
     if (res == result::success)
     {
         return res;
     }
     // Return to main synchronized pool.
     return m_profile_scope_pool.free(scope);
 }
get_active_job_context()
internal::job_context * jobs::scheduler::get_active_job_context () static
Gets the context of the job currently running on calling thread.
Generally this should not need to be called by user-code. Rather the wrappers that interface with the context (profile_scope, job_handle, etc) should be preferred.
Returns
Context of the currently running job, or nullptr if no job is running on this thread.
Definition at line 1601 of file jobs_scheduler.cpp.
References m_worker_thread_scheduler, and WorkerThreadState.
Referenced by jobs::internal::profile_scope_internal::profile_scope_internal(), jobs::counter_handle::remove(), jobs::counter_handle::wait_for(), wait_for_job(), and jobs::internal::profile_scope_internal::~profile_scope_internal().
 {
     if (m_worker_thread_scheduler == nullptr)
     {
         return nullptr;
     }
     return WorkerThreadState.active_job_context;
 }
get_active_job_definition()
internal::job_definition * jobs::scheduler::get_active_job_definition () static
Gets the definition of the job currently running on calling thread.
Generally this should not need to be called by user-code. Rather the wrappers that interface with the context (profile_scope, job_handle, etc) should be preferred. Its public on the off chance that user-code wants finer-grain control over things like profiling scope.
Returns
Definition of the currently running job, or nullptr if no job is running on this thread.
Definition at line 1624 of file jobs_scheduler.cpp.
References m_worker_thread_scheduler, and WorkerThreadState.
Referenced by sleep().
 {
     if (m_worker_thread_scheduler == nullptr)
     {
         return nullptr;
     }
     if (WorkerThreadState.active_job_context != nullptr)
     {
         return WorkerThreadState.active_job_context->job_def;
     }
     else
     {
         return nullptr;
     }
 }
get_counter_definition()
internal::counter_definition& jobs::scheduler::get_counter_definition (size_t index) inline protected
Gets a counter definition by its pool index.
Parameters
index Index into the counter pool of definition to retrieve.
Returns
Counter definition at the given index.
Definition at line 650 of file jobs_scheduler.h.
References JOBS_FORCE_NO_INLINE.
Referenced by jobs::counter_handle::add_to_wait_list(), create_counter(), decrease_counter_ref_count(), free_counter(), jobs::counter_handle::get(), increase_counter_ref_count(), jobs::counter_handle::modify_value(), jobs::counter_handle::notify_value_changed(), jobs::counter_handle::remove(), jobs::counter_handle::remove_from_wait_list(), and jobs::counter_handle::wait_for().
     {
         return *m_counter_pool.get_index(index);
     }
get_job_definition()
internal::job_definition& jobs::scheduler::get_job_definition (size_t index) inline protected
Gets a job definition by its pool index.
Parameters
index Index into the job pool of definition to retrieve.
Returns
Job definition at the given index.
Definition at line 423 of file jobs_scheduler.h.
References jobs::timeout::infinite, JOBS_FORCE_INLINE, and jobs::message.
Referenced by add_job_dependency(), clear_job_dependencies(), complete_job(), create_job(), decrease_job_ref_count(), dispatch_batch(), dispatch_job(), execute_fiber_job(), execute_next_job(), free_job(), get_next_job_from_queue(), increase_job_ref_count(), jobs::job_handle::is_complete(), jobs::job_handle::is_mutable(), jobs::job_handle::is_pending(), jobs::job_handle::is_running(), requeue_job(), requeue_job_batch(), jobs::job_handle::set_completion_counter(), jobs::job_handle::set_priority(), jobs::job_handle::set_stack_size(), jobs::job_handle::set_tag(), jobs::job_handle::set_work(), and wait_for_job().
     {
         return *m_job_pool.get_index(index);
     }
get_logical_core_count()
size_t jobs::scheduler::get_logical_core_count () static
Returns the number of logical cores on the system.
This is provided to given a rough idea of the amount of worker threads that should be spawned by the scheduler to provide maximum utilization of system resources.
Returns
Number of logical cores on the system.
Definition at line 1680 of file jobs_scheduler.cpp.
Referenced by init().
 {
 #if defined(JOBS_PLATFORM_PS4)
     return 6; // Using the 7th core for workers can cause sync problems if a mutex gets held when its timesliced back to the OS.
 #else
     return std::thread::hardware_concurrency();
 #endif
 }
get_next_job()
bool jobs::scheduler::get_next_job (size_t & job_index, priority priorities, bool can_block) protected
Gets the next available job from the highest priority queue available.
Parameters
job_index Reference to store retrieved job index in.
priorities Priority queues to look for jobs in.
can_block If true the function will block until a job is available. Otherwise the return value can be used to determine if a job was found.
Returns
True if a job was retrieved.
Definition at line 1093 of file jobs_scheduler.cpp.
References jobs::count, get_next_job_from_queue(), jobs_profile_scope, m_destroying, m_pending_job_queues, wait_for_job_available(), and jobs::worker.
Referenced by execute_next_job().
 {
     jobs_profile_scope(profile_scope_type::worker, "scheduler::get_next_job", this);
     while (!m_destroying)
     {
         {
             jobs_profile_scope(profile_scope_type::worker, "dequeue job", this);
             // Look for work in each priority queue we can execute.
             for (size_t i = 0; i < (int)priority::count; i++)
             {
                 int mask = 1 << i;
                 if (((size_t)priorities & mask) != 0)
                 {
                     if (get_next_job_from_queue(job_index, m_pending_job_queues[i], mask))
                     {
                         return true;
                     }
                 }
             }
         }
         if (!can_block)
         {
             break;
         }
         // Wait for next job.
         wait_for_job_available();
     }
     return false;
 }
get_next_job_from_queue()
bool jobs::scheduler::get_next_job_from_queue (size_t & job_index, job_queue & queue, size_t queue_mask) protected
Gets the next available job a given queue.
Parameters
job_index Reference to store retrieved job index in.
queue Queue to retrieve job from.
queue_mask Priority mask of queue.
Returns
True if a job was retrieved.
Definition at line 1051 of file jobs_scheduler.cpp.
References jobs::internal::job_definition::context, jobs::count, jobs::internal::atomic_queue< data_type >::count(), jobs::empty, get_job_definition(), jobs::scheduler::worker_thread_state::job_index, jobs_profile_scope, m_available_jobs, jobs::internal::pending, jobs::scheduler::job_queue::pending_job_indicies, jobs::internal::job_definition::pending_predecessors, jobs::internal::atomic_queue< data_type >::pop(), jobs::internal::job_context::queues_contained_in, jobs::internal::running, jobs::internal::job_definition::status, jobs::verbose, jobs::worker, and write_log().
Referenced by get_next_job().
 {
     bool shifted_last_iteration = false;
     jobs_profile_scope(profile_scope_type::worker, "scheduler::get_next_job_from_queue", this);
     size_t count = queue.pending_job_indicies.count();
     for (size_t i = 0; i < count; i++)
     {
         size_t job_index;
         result res = queue.pending_job_indicies.pop(job_index);
         if (res == result::empty)
         {
             break;
         }
         internal::job_definition& def = get_job_definition(job_index);
         // If job hasn't already started running (because its been picked up from another queue),
         // the mark it as running and return it.
         internal::job_status expected = internal::job_status::pending;
         if (def.status.compare_exchange_strong(expected, internal::job_status::running))
         {
             def.context.queues_contained_in &= ~queue_mask;
             assert(def.pending_predecessors == 0);
 #if defined(JOBS_USE_VERBOSE_LOGGING)
             write_log(debug_log_verbosity::verbose, debug_log_group::worker, "Picked up %zi from queue %i", job_index, queue_mask);
 #endif
             size_t result = --m_available_jobs;
             output_job_index = job_index;
             return true;
         }
     }
     return false;
 }
get_worker_job_context()
internal::job_context * jobs::scheduler::get_worker_job_context () static
Gets the context of the worker management fiber running individual jobs.
Generally this should not need to be called by user-code. Rather the wrappers that interface with the context (profile_scope, job_handle, etc) should be preferred.
Returns
Context of the current threads worker fiber, or nullptr if not called on a worker thread.
Definition at line 1615 of file jobs_scheduler.cpp.
References m_worker_thread_scheduler, and WorkerThreadState.
Referenced by jobs::counter_handle::remove(), jobs::counter_handle::wait_for(), and wait_for_job().
 {
     if (m_worker_thread_scheduler == nullptr)
     {
         return nullptr;
     }
     return &WorkerThreadState.job_context;
 }
increase_counter_ref_count()
void jobs::scheduler::increase_counter_ref_count (size_t index) protected
Increases the reference count of the counter based on it's pool index.
Parameters
index Index of counter to increment ref count of.
Definition at line 594 of file jobs_scheduler.cpp.
References get_counter_definition(), and jobs::internal::counter_definition::ref_count.
Referenced by jobs::counter_handle::increase_ref().
 {
     internal::counter_definition& def = get_counter_definition(index);
     size_t new_ref_count = ++def.ref_count;
 }
increase_job_ref_count()
void jobs::scheduler::increase_job_ref_count (size_t index) protected
Increases the reference count of the job based on it's pool index.
Parameters
index Index of counter to increment ref count of.
Definition at line 662 of file jobs_scheduler.cpp.
References get_job_definition(), and jobs::internal::job_definition::ref_count.
Referenced by dispatch_batch(), dispatch_job(), and jobs::job_handle::increase_ref().
 {
     internal::job_definition& def = get_job_definition(index);
     def.ref_count.fetch_add(1, std::memory_order_relaxed);
 }
init()
result jobs::scheduler::init ()
Initializes this scheduler so it's ready to accept jobs.
Initializes this scheduler so it's ready to accept jobs. All allocation of memory is done up-front during the execution of this function.
Returns
Value indicating the success of this function.
Definition at line 295 of file jobs_scheduler.cpp.
References jobs::already_initialized, jobs::internal::job_definition::context, jobs::count, jobs::error, jobs::scheduler::fiber_pool::fiber_count, get_logical_core_count(), jobs::internal::callback_scheduler::init(), jobs::internal::atomic_queue< data_type >::init(), jobs::scheduler::thread_pool::job_priorities, m_callback_scheduler, m_counter_pool, m_fiber_pool_count, m_fiber_pools, m_fiber_pools_sorted_by_stack, m_initialized, m_job_dependency_pool, m_job_pool, m_max_callbacks, m_max_counters, m_max_dependencies, m_max_jobs, m_max_profile_scopes, m_memory_functions, m_pending_job_queues, m_platform_fiber_aware, m_profile_scope_pool, m_raw_memory_functions, m_thread_pool_count, m_thread_pools, m_total_memory_allocated, m_worker_count, m_worker_thread_states, jobs::memory, jobs::message, jobs::no_fiber_pools, jobs::no_thread_pools, jobs::out_of_memory, jobs::scheduler::job_queue::pending_job_indicies, jobs::platform_error, jobs::scheduler::thread_pool::pool, jobs::scheduler::fiber_pool::pool, jobs::internal::job_context::scheduler, jobs::scheduler, jobs::scheduler::fiber_pool::stack_size, jobs::success, jobs::scheduler::thread_pool::thread_count, jobs::memory_functions::user_alloc, jobs::memory_functions::user_free, jobs::verbose, and write_log().
 {
     if (m_initialized)
     {
         return result::already_initialized;
     }
     if (m_thread_pool_count == 0)
     {
         return result::no_thread_pools;
     }
     if (m_fiber_pool_count == 0)
     {
         return result::no_fiber_pools;
     }
     m_initialized = true;
     // Trampoline the memory functions so we can log allocations.
     m_memory_functions.user_alloc = [=](size_t size, size_t alignment) -> void* {
         void* ptr = m_raw_memory_functions.user_alloc(size, alignment);
         m_total_memory_allocated += size;
 #if defined(JOBS_USE_VERBOSE_LOGGING)
         write_log(debug_log_verbosity::verbose, debug_log_group::memory, "allocated memory block, size=%zi ptr=0x%08p total=%zi", size, ptr, m_total_memory_allocated.load());
 #endif
         return reinterpret_cast<char*>(ptr);
     };
     m_memory_functions.user_free = [=](void* ptr) {
         return m_raw_memory_functions.user_free(ptr);
     };
     // Platform initialization.
 #if defined(JOBS_PLATFORM_PS4)
     // Ensure fiber prx is loaded.
     if (sceSysmoduleIsLoaded(SCE_SYSMODULE_FIBER))
     {
         if (sceSysmoduleLoadModule(SCE_SYSMODULE_FIBER) != SCE_OK)
         {
             write_log(debug_log_verbosity::error, debug_log_group::scheduler, "failed to load SCE_SYSMODULE_FIBER");
             return result::platform_error;
         }
         else
         {
             m_owns_scesysmodule_fiber = true;
         }
     }
     m_platform_fiber_aware = true;
 #endif
     // Allocate jobs.
     result result = m_job_pool.init(m_memory_functions, m_max_jobs, [this](internal::job_definition* instance, size_t index)
     {
         new(instance) internal::job_definition(index);
         instance->context.scheduler = this;
         return result::success;
     });
     if (result != result::success)
     {
         return result;
     }
     // Allocate job dependencies.
     result = m_job_dependency_pool.init(m_memory_functions, m_max_dependencies, [](internal::job_dependency* instance, size_t index)
     {
         new(instance) internal::job_dependency(index);
         return result::success;
     });
     if (result != result::success)
     {
         return result;
     }
     // Allocate counters.
     result = m_counter_pool.init(m_memory_functions, m_max_counters, [](internal::counter_definition* instance, size_t index)
     {
         new(instance) internal::counter_definition();
         return result::success;
     });
     if (result != result::success)
     {
         return result;
     }
     // Allocate profile scopes.
     result = m_profile_scope_pool.init(m_memory_functions, m_max_profile_scopes, [](internal::profile_scope_definition* instance, size_t index)
     {
         new(instance) internal::profile_scope_definition();
         return result::success;
     });
     if (result != result::success)
     {
         return result;
     }
     // Allocate callbacks.
     result = m_callback_scheduler.init(this, m_max_callbacks, m_memory_functions);
     if (result != result::success)
     {
         return result;
     }
     // Allocate task queues.
     for (size_t i = 0; i < (int)priority::count; i++)
     {
         result = m_pending_job_queues[i].pending_job_indicies.init(m_memory_functions, m_max_jobs);
         if (result != result::success)
         {
             return result;
         }
     }
     // Allocate fibers.
     for (size_t i = 0; i < m_fiber_pool_count; i++)
     {
         fiber_pool& pool = m_fiber_pools[i];
         m_fiber_pools_sorted_by_stack[i] = &pool;
         result = pool.pool.init(m_memory_functions, pool.fiber_count, [&](internal::fiber* instance, size_t index)
         {
             new(instance) internal::fiber(m_memory_functions);
             char buffer[64];
             memset(buffer, 0, sizeof(buffer));
             sprintf(buffer, "Job (Pool=%zi Index=%zi)", i, index);
             return instance->init(pool.stack_size, [this, i, index]()
             {
                 worker_fiber_entry_point(i, index);
             }, buffer);
         });
         if (result != result::success)
         {
             return result;
         }
     }
     // Sort fiber pools by stack size, smallest to largest, saves
     // redundent iteration when looking for smallest fitting stack size.
     auto fiber_sort_predicate = [](const scheduler::fiber_pool* lhs, const scheduler::fiber_pool* rhs)
     {
         return lhs->stack_size < rhs->stack_size;
     };
     std::sort(m_fiber_pools_sorted_by_stack, m_fiber_pools_sorted_by_stack + m_fiber_pool_count, fiber_sort_predicate);
     // Allocate worker states.
     for (size_t i = 0; i < m_thread_pool_count; i++)
     {
         thread_pool& pool = m_thread_pools[i];
         m_worker_count += pool.thread_count;
     }
     m_worker_thread_states = (worker_thread_state*)m_memory_functions.user_alloc(sizeof(worker_thread_state) * m_worker_count, alignof(worker_thread_state));
     if (m_worker_thread_states == nullptr)
     {
         return result::out_of_memory;
     }
     for (size_t i = 0; i < m_worker_count; i++)
     {
         new(m_worker_thread_states + i) worker_thread_state();
     }
     // Allocate threads.
     size_t thread_index = 0;
     size_t logical_cores = get_logical_core_count();
     for (size_t i = 0; i < m_thread_pool_count; i++)
     {
         thread_pool& pool = m_thread_pools[i];
         result = pool.pool.init(m_memory_functions, pool.thread_count, [&](internal::thread* instance, size_t index)
         {
             new(instance) internal::thread(m_memory_functions);
             size_t core_affinity = ((size_t)1 << (thread_index % logical_cores));
             thread_index++;
             char buffer[64];
             memset(buffer, 0, sizeof(buffer));
             sprintf(buffer, "Worker (Pool=%zi:%zi Affinity=%zi)", i, index, core_affinity);
             return instance->init([&, i, index, thread_index]()
             {
                 m_worker_thread_scheduler = this;
                 m_worker_thread_state = (m_worker_thread_states + (thread_index  - 1));
                 worker_entry_point(i, index, *instance, pool);
             }, buffer, core_affinity);
         });
         if (result != result::success)
         {
             return result;
         }
     }
     // Dump out some general logs describing the scheduler setup.
     write_log(debug_log_verbosity::message, debug_log_group::scheduler, "scheduler initialized");
     write_log(debug_log_verbosity::message, debug_log_group::scheduler, "\t%zi bytes allocated", m_total_memory_allocated.load());
     write_log(debug_log_verbosity::message, debug_log_group::scheduler, "\t%i max jobs", m_max_jobs);
     write_log(debug_log_verbosity::message, debug_log_group::scheduler, "\t%i max dependencies", m_max_dependencies);
     write_log(debug_log_verbosity::message, debug_log_group::scheduler, "\t%i max profile scopes", m_max_profile_scopes);
     write_log(debug_log_verbosity::message, debug_log_group::scheduler, "\t%i max counters", m_max_counters);
     write_log(debug_log_verbosity::message, debug_log_group::scheduler, "\t%i max callbacks", m_max_callbacks);
     write_log(debug_log_verbosity::message, debug_log_group::scheduler, "\t%i thread pools", m_thread_pool_count);
     for (size_t i = 0; i < m_thread_pool_count; i++)
     {
         thread_pool& pool = m_thread_pools[i];
         write_log(debug_log_verbosity::message, debug_log_group::scheduler, "\t\t[%i] workers=%i priorities=0x%08x", i, pool.thread_count, pool.job_priorities);
     }
     write_log(debug_log_verbosity::message, debug_log_group::scheduler, "\t%i fiber pools", m_fiber_pool_count);
     for (size_t i = 0; i < m_fiber_pool_count; i++)
     {
         fiber_pool& pool = *m_fiber_pools_sorted_by_stack[i];
         write_log(debug_log_verbosity::message, debug_log_group::scheduler, "\t\t[%i] fibers=%i stack_size=%i", i, pool.fiber_count, pool.stack_size);
     }
     return result::success;
 }
is_idle()
bool jobs::scheduler::is_idle () const
Returns true if all jobs are complete and the scheduler and it's workers are idle.
Returns
True if idle.
Definition at line 1499 of file jobs_scheduler.cpp.
References m_active_job_count.
Referenced by wait_until_idle().
 {
     return (m_active_job_count.load() == 0);
 }
is_profiling_active()
bool jobs::scheduler::is_profiling_active () static
Gets if the active scheduler has profiling enabled.
Used to early-out of various bits of profiling code.
Returns
True if profiling is active.
Definition at line 1610 of file jobs_scheduler.cpp.
References m_profiling_active.
Referenced by jobs::internal::profile_scope_internal::profile_scope_internal(), and jobs::internal::profile_scope_internal::~profile_scope_internal().
 {
     return m_profiling_active;
 }
leave_context()
void jobs::scheduler::leave_context (internal::job_context & old_context) protected
Leaves the given job execution context in preperation for entering another.
Leaving a context performs various bits of cleanup worker, such as poping profiler markers off the threads stack, in preperation for a new context being entered.
Parameters
old_context Context to leave.
Definition at line 610 of file jobs_scheduler.cpp.
References jobs::profile_functions::leave_scope, m_platform_fiber_aware, m_profile_functions, and jobs::internal::job_context::profile_scope_depth.
Referenced by switch_context().
 {
     // Remove everything from the profile scope stack.
     if (m_profile_functions.leave_scope != nullptr && !m_platform_fiber_aware)
     {
         for (size_t i = 0; i < context.profile_scope_depth; i++)
         {
             m_profile_functions.leave_scope();
         }
     }
 }
notify_job_available()
void jobs::scheduler::notify_job_available (size_t job_count = 1) protected
Notifies any workers that a given number of jobs are available for processing.
Parameters
job_count Number of jobs that are newly available.
Definition at line 1640 of file jobs_scheduler.cpp.
References jobs_profile_scope, m_available_jobs, m_task_available_cvar, m_worker_count, and jobs::worker.
Referenced by jobs::counter_handle::notify_value_changed(), requeue_job(), requeue_job_batch(), and ~scheduler().
 {
     jobs_profile_scope(profile_scope_type::worker, "scheduler::notify_job_available", this);
     size_t result = (m_available_jobs += job_count);
     if (job_count > m_worker_count)
     {
         m_task_available_cvar.notify_all();
     }
     else
     {
         for (int i = 0; i < job_count; i++)
         {
             m_task_available_cvar.notify_one();
         }
     }
 }
notify_job_complete()
void jobs::scheduler::notify_job_complete () protected
Notifies any waiting workers that a job has completed.
Definition at line 1659 of file jobs_scheduler.cpp.
References jobs_profile_scope, m_task_complete_cvar, and jobs::worker.
Referenced by complete_job().
 {
     jobs_profile_scope(profile_scope_type::worker, "scheduler::notify_job_complete", this);
     m_task_complete_cvar.notify_all();
 }
requeue_job()
result jobs::scheduler::requeue_job (size_t index) protected
Requeues a job that has previously been picked up for execution.
This is primarily used when requeueing a job following it being readied by a condition it is waiting on being fulfilled (counter getting to value, job completing, etc).
Parameters
index Index of job to requeue.
Returns
Value indicating the success of this function.
Definition at line 1016 of file jobs_scheduler.cpp.
References jobs::internal::job_definition::context, jobs::count, get_job_definition(), jobs::internal::job_definition::job_priority, jobs_profile_scope, m_pending_job_queues, notify_job_available(), jobs::internal::pending, jobs::scheduler::job_queue::pending_job_indicies, jobs::internal::atomic_queue< data_type >::push(), jobs::internal::job_context::queues_contained_in, jobs::internal::sleeping, jobs::internal::job_definition::status, jobs::success, jobs::internal::waiting_on_counter, jobs::internal::waiting_on_job, and jobs::worker.
Referenced by complete_job(), dispatch_job(), execute_next_job(), jobs::counter_handle::notify_value_changed(), jobs::counter_handle::remove(), jobs::counter_handle::wait_for(), and wait_for_job().
 {
     jobs_profile_scope(profile_scope_type::worker, "scheduler::requeue_job", this);
     internal::job_definition& def = get_job_definition(index);
     // Reset the status to pending if its anything else.
     // @todo: is this neccessary? Most requeues will set the status themselves.
     internal::job_status status = def.status.load(std::memory_order_relaxed);
     if (status != internal::job_status::sleeping &&
         status != internal::job_status::waiting_on_job &&
         status != internal::job_status::waiting_on_counter)
     {
         def.status.store(internal::job_status::pending, std::memory_order_relaxed);
     }
     // Put job into a job queue for each priority it holds (not sure why you would want multiple priorities, but might as well support it ...).
     for (size_t i = 0; i < (int)priority::count; i++)
     {
         int mask = 1 << i;
         if (((size_t)def.job_priority & mask) != 0 && (def.context.queues_contained_in & mask) == 0)
         {
             def.context.queues_contained_in |= mask;
             result res = m_pending_job_queues[i].pending_job_indicies.push(index);
             assert(res == result::success);
         }
     }
     notify_job_available(1);
     return result::success;
 }
requeue_job_batch()
result jobs::scheduler::requeue_job_batch (job_handle * job_array, size_t count, size_t job_queues) protected
Requeues a quantity of jobs that have previously been picked up for execution.
This works the same as requeue_job except it combines a lot of the overhead to reduce the overall execution time.
Parameters
job_array Array of job handles to requeue.
count Number of job handles in job_array.
job_queues Bitmaks of queues that jobs should be enqueued in (only if their priority mask also contains the queue).
Returns
Value indicating the success of this function.
Definition at line 939 of file jobs_scheduler.cpp.
References jobs::internal::job_definition::context, jobs::count, get_job_definition(), jobs::internal::job_definition::job_priority, jobs_profile_scope, jobs::job_handle::m_index, m_pending_job_queues, notify_job_available(), jobs::scheduler::job_queue::pending_job_indicies, jobs::internal::job_definition::pending_predecessors, jobs::internal::atomic_queue< data_type >::push_batch(), jobs::internal::job_context::queues_contained_in, jobs::success, and jobs::worker.
Referenced by dispatch_batch().
 {
     jobs_profile_scope(profile_scope_type::worker, "scheduler::requeue_job_batch", this);
     size_t queued_job_count = 0;
     bool first_iteration = true;
     // Generate a list of jobs for each priority and queue them at once.
     for (size_t i = 0; i < (int)priority::count; i++)
     {
         int mask = 1 << i;
         // After first iteration we know what queues jobs exists for
         // any we don't care about.
         if (((size_t)job_queues & mask) == 0)
         {
             continue;
         }
         jobs_profile_scope(profile_scope_type::worker, "sort by priority", this);
         // Do an in-place sort.
         size_t number_with_priority = 0;
         size_t write_index = 0;
         for (size_t j = 0; j < count; j++)
         {
             size_t index = job_array[j].m_index;
             internal::job_definition& def = get_job_definition(index);
             if (def.pending_predecessors != 0)
             {
                 continue;
             }
             // Store number of valid jobs and a mask of all queues jobs exist in.
             if (first_iteration)
             {
                 queued_job_count++;
             }
             if (((size_t)def.job_priority & mask) != 0 && (def.context.queues_contained_in & mask) == 0)
             {
                 def.context.queues_contained_in |= mask;
                 number_with_priority++;
                 if (i != write_index)
                 {
                     size_t tmp = job_array[write_index].m_index;
                     job_array[write_index].m_index = job_array[j].m_index;
                     job_array[j].m_index = tmp;
                 }
                 write_index++;
             }
         }
         if (number_with_priority > 0)
         {
             jobs_profile_scope(profile_scope_type::worker, "batch enqueue", this);
             result res = m_pending_job_queues[i].pending_job_indicies.push_batch(
                 &job_array[0].m_index,
                 reinterpret_cast<size_t>(&job_array[1].m_index) - reinterpret_cast<size_t>(&job_array[0].m_index),
                 number_with_priority);
             assert(res == result::success);
         }
         first_iteration = false;
     }
     notify_job_available(queued_job_count);
     return result::success;
 }
return_to_worker()
void jobs::scheduler::return_to_worker (internal::job_context & new_context, bool supress_requeue) protected
Returns execution from the current fiber to the worker thread.
Parameters
new_context Context of worker thread to return to.
supress_requeue If true the worker will not requeue the job when it's switched to.
Definition at line 656 of file jobs_scheduler.cpp.
References switch_context(), and WorkerThreadState.
Referenced by jobs::counter_handle::remove(), and jobs::counter_handle::wait_for().
 {
     WorkerThreadState.job_supress_requeue = supress_requeue;
     switch_context(new_context);
 }
set_debug_output()
result jobs::scheduler::set_debug_output (const debug_output_function & function, debug_log_verbosity max_verbosity = debug_log_verbosity::message)
Provides a function which all debug output will be passed.
Parameters
function Function to pass all debug output.
max_verbosity Any debug output more verbose than this will be dropped. Saves perf formatting the logs.
Returns
Value indicating the success of this function.
Definition at line 186 of file jobs_scheduler.cpp.
References jobs::already_initialized, m_debug_output_function, m_debug_output_max_verbosity, m_initialized, and jobs::success.
 {
     if (m_initialized)
     {
         return result::already_initialized;
     }
     m_debug_output_function = function;
     m_debug_output_max_verbosity = max_verbosity;
     return result::success;
 }
set_max_callbacks()
result jobs::scheduler::set_max_callbacks (size_t max_callbacks)
Sets the maximum number of latent callbacks that can be scheduld and used for syncronization.
A latent callback is created for each wait/sleep call that is provided with a timeout value. This has a direct effect on the quantity of memory allocated by the scheduler when initialized.
Parameters
max_callbacks New maximum number of callbacks.
Returns
Value indicating the success of this function.
Definition at line 247 of file jobs_scheduler.cpp.
References jobs::already_initialized, m_initialized, m_max_callbacks, and jobs::success.
 {
     if (m_initialized)
     {
         return result::already_initialized;
     }
     m_max_callbacks = max_callbacks;
     return result::success;
 }
set_max_counters()
result jobs::scheduler::set_max_counters (size_t max_counters)
Sets the maximum number of counters that can be created and used for syncronization.
This capacity is used for both raw counters and events. This has a direct effect on the quantity of memory allocated by the scheduler when initialized.
Parameters
max_counters New maximum number of counters.
Returns
Value indicating the success of this function.
Definition at line 235 of file jobs_scheduler.cpp.
References jobs::already_initialized, m_initialized, m_max_counters, and jobs::success.
 {
     if (m_initialized)
     {
         return result::already_initialized;
     }
     m_max_counters = max_counters;
     return result::success;
 }
set_max_dependencies()
result jobs::scheduler::set_max_dependencies (size_t max_dependencies)
Sets the maximum number of job dependencies.
Sets the maximum number of jobs dependencies shared between all jobs at a given time. This has a direct effect on the quantity of memory allocated by the scheduler when initialized.
Parameters
max_dependencies New maximum number of job dependencies.
Returns
Value indicating the success of this function.
Definition at line 211 of file jobs_scheduler.cpp.
References jobs::already_initialized, m_initialized, m_max_dependencies, and jobs::success.
 {
     if (m_initialized)
     {
         return result::already_initialized;
     }
     m_max_dependencies = max_dependencies;
     return result::success;
 }
set_max_jobs()
result jobs::scheduler::set_max_jobs (size_t max_jobs)
Sets the maximum number of jobs.
Sets the maximum number of jobs that can be concurrently managed by the scheduler. This has a direct effect on the quantity of memory allocated by the scheduler when initialized.
Parameters
max_jobs New maximum number of jobs.
Returns
Value indicating the success of this function.
Definition at line 199 of file jobs_scheduler.cpp.
References jobs::already_initialized, m_initialized, m_max_jobs, and jobs::success.
 {
     if (m_initialized)
     {
         return result::already_initialized;
     }
     m_max_jobs = max_jobs;
     return result::success;
 }
set_max_profile_scopes()
result jobs::scheduler::set_max_profile_scopes (size_t max_scopes)
Sets the maximum number of profile scopes that can be tracked.
If you have heavily nested profile scope call graphs, you should increase this value. This has a direct effect on the quantity of memory allocated by the scheduler when initialized.
This value is per worker thread.
Parameters
max_scopes New maximum number of profile scopes.
Returns
Value indicating the success of this function.
Definition at line 223 of file jobs_scheduler.cpp.
References jobs::already_initialized, m_initialized, m_max_profile_scopes, and jobs::success.
 {
     if (m_initialized)
     {
         return result::already_initialized;
     }
     m_max_profile_scopes = max_scopes;
     return result::success;
 }
set_memory_functions()
result jobs::scheduler::set_memory_functions (const memory_functions & functions)
Overrides the default memory allocation functions used by the scheduler.
Parameters
functions Struct containing all the memory allocation functions to override.
Returns
Value indicating the success of this function.
Definition at line 161 of file jobs_scheduler.cpp.
References jobs::already_initialized, m_initialized, m_raw_memory_functions, and jobs::success.
 {
     if (m_initialized)
     {
         return result::already_initialized;
     }
     m_raw_memory_functions = functions;
     return result::success;
 }
set_profile_functions()
result jobs::scheduler::set_profile_functions (const profile_functions & functions)
Overrides the default profiling functions used by the scheduler.
Parameters
functions Struct containing all the profiling functions to override.
Returns
Value indicating the success of this function.
Definition at line 173 of file jobs_scheduler.cpp.
References jobs::already_initialized, jobs::profile_functions::enter_scope, jobs::profile_functions::leave_scope, m_initialized, m_profile_functions, m_profiling_active, and jobs::success.
 {
     if (m_initialized)
     {
         return result::already_initialized;
     }
     m_profile_functions = functions;
     m_profiling_active = (functions.enter_scope != nullptr && functions.leave_scope != nullptr);
     return result::success;
 }
sleep()
result jobs::scheduler::sleep (timeout duration = timeout::infinite) static
Puts the job or thread to sleep for the given amount of time.
If called from a job this is non-blocking, and will queue the job for execution after the time period has elapsed. If called from any other place, it will block.
Parameters
duration The length of time before this function returns.
Returns
Value indicating the success of this function.
Definition at line 1538 of file jobs_scheduler.cpp.
References jobs::timeout::duration, get_active_job_definition(), jobs::timeout::is_infinite(), jobs::job, jobs::internal::pending, jobs::internal::sleeping, jobs::success, jobs::timeout, jobs::verbose, and WorkerThreadState.
 {
     // I hope this isn't intentional ...
     assert(!duration.is_infinite());
     internal::job_definition* definition = get_active_job_definition();
     // If we have a job context, put it to sleep.
     if (definition != nullptr)
     {
         volatile bool timeout_called = false;
 #if defined(JOBS_USE_VERBOSE_LOGGING)
         definition->context.scheduler->write_log(debug_log_verbosity::verbose, debug_log_group::job, "sleeping fiber=%zi:%zi", definition->context.fiber_pool_index, definition->context.fiber_index);
 #endif
         // Put job to sleep.
         definition->status = internal::job_status::sleeping;
         // Queue a wakeup.
         size_t schedule_handle;
         result res = definition->context.scheduler->m_callback_scheduler.schedule(duration, schedule_handle, [&]() {
 #if defined(JOBS_USE_VERBOSE_LOGGING)
             definition->context.scheduler->write_log(debug_log_verbosity::verbose, debug_log_group::job, "wakeup fiber=%zi:%zi", definition->context.fiber_pool_index, definition->context.fiber_index);
 #endif
             timeout_called = true;
             definition->status = internal::job_status::pending;
             definition->context.scheduler->requeue_job(definition->index);
         });
         // Failed to schedule a wakeup? Abort.
         if (res != result::success)
         {
             definition->status = internal::job_status::pending;
             return res;
         }
         // Supress requeueing the job, we will do this when the callback returns.
         WorkerThreadState.job_supress_requeue = true;
         // Switch back to worker which will requeue fiber for execution later.
         definition->context.scheduler->switch_context(WorkerThreadState.job_context);
         // We shouldn't be able to get back here without a timeout.
         assert(timeout_called);
         return result::timeout;
     }
     // No job context? Blocking sleep then I guess?
     else
     {
         // Not really sure why you would want this ... But better to support all situations I guess.
         std::this_thread::sleep_for(std::chrono::milliseconds(duration.duration));
         return result::timeout;
     }
 }
switch_context()
void jobs::scheduler::switch_context (internal::job_context & new_context) protected
Switches from current job execution context to a new one.
This is a helper function that essentially just calls leave_context on the current context and enter_context on the new context provided.
Parameters
new_context Context to switch to.
Definition at line 650 of file jobs_scheduler.cpp.
References enter_context(), leave_context(), and WorkerThreadState.
Referenced by execute_next_job(), return_to_worker(), wait_for_job(), and worker_fiber_entry_point().
 {
     leave_context(*WorkerThreadState.active_job_context);
     enter_context(new_context);
 }
wait_for_job()
result jobs::scheduler::wait_for_job (job_handle job_handle, timeout wait_timeout = timeout::infinite) protected
Waits for a job to complete.
If called from a job this is non-blocking, and will queue the job for execution after the given job completes. If called from any other place, it will block.
Parameters
job_handle Job to wait for completion of.
wait_timeout If provided, this function will wait a maximum of this time. If the function returns due to a timeout the result provided will be result::timeout.
Returns
Value indicating the success of this function.
Definition at line 1364 of file jobs_scheduler.cpp.
References jobs::internal::callback_scheduler::cancel(), jobs::internal::completed, jobs::timeout::duration, execute_next_job(), get_active_job_context(), jobs::internal::stopwatch::get_elapsed_ms(), get_job_definition(), get_worker_job_context(), jobs::internal::job_definition::index, jobs::job_handle::is_complete(), jobs::timeout::is_infinite(), jobs::internal::job_context::job_def, job_handle, jobs_profile_scope, m_callback_scheduler, jobs::job_handle::m_index, m_task_complete_cvar, m_task_complete_mutex, jobs::internal::pending, requeue_job(), jobs::internal::running, jobs::internal::callback_scheduler::schedule(), jobs::internal::stopwatch::start(), jobs::internal::job_definition::status, jobs::success, switch_context(), jobs::timeout, jobs::internal::job_definition::wait_job, jobs::internal::job_definition::wait_list, jobs::internal::job_definition::wait_list_link, jobs::internal::waiting_on_job, jobs::worker, and WorkerThreadState.
Referenced by jobs::job_handle::wait().
 {
     jobs_profile_scope(profile_scope_type::worker, "scheduler::wait_for_job", this);
     internal::job_context* context = get_active_job_context();
     internal::job_context* worker_context = get_worker_job_context();
     // If we have a job context, adds this event to its dependencies and put it to sleep.
     if (context != nullptr)
     {
         assert(worker_context != nullptr);
         volatile bool timeout_called = false;
         // Put job to sleep.
         context->job_def->status = internal::job_status::waiting_on_job;
         context->job_def->wait_job = job_handle_in;
         // Queue a wakeup.
         size_t schedule_handle;
         if (!wait_timeout.is_infinite())
         {
             result res = m_callback_scheduler.schedule(wait_timeout, schedule_handle, [&]() {
                 // Do this atomatically to make sure we don't set it to pending after the scheduler
                 // has already done that due to this event being signalled.
                 internal::job_status expected = internal::job_status::waiting_on_job;
                 if (context->job_def->status.compare_exchange_strong(expected, internal::job_status::pending))
                 {
                     timeout_called = true;
                     requeue_job(context->job_def->index);
                 }
             });
             // Failed to schedule a wakeup? Abort.
             if (res != result::success)
             {
                 context->job_def->status = internal::job_status::running;
                 return res;
             }
         }
         // Attach this to wakeup queue for job.
         bool is_complete = false;
         {
             internal::job_definition& other_job_def = get_job_definition(job_handle_in.m_index);
             internal::optional_shared_lock<internal::spinwait_mutex> lock(other_job_def.wait_list.get_mutex());
             // Check it hasn't completed while acquiring lock.
             if (other_job_def.status == internal::job_status::completed)
             {
                 context->job_def->status = internal::job_status::running;
                 is_complete = true;
             }
             else
             {
                 context->job_def->wait_list_link.value = context->job_def;
                 other_job_def.wait_list.add(&context->job_def->wait_list_link, false);
             }
         }
         if (!is_complete)
         {
             // Supress requeueing the job, we will do this when the callback returns.
             WorkerThreadState.job_supress_requeue = true;
             // Switch back to worker which will requeue fiber for execution later.
             switch_context(*worker_context);
         }
         // Cleanup
         context->job_def->wait_job = job_handle();
         // If we timed out, just escape here.
         if (timeout_called && !is_complete)
         {
             return result::timeout;
         }
         // Cancel callback and clear our job handle.
         if (!wait_timeout.is_infinite())
         {
             m_callback_scheduler.cancel(schedule_handle);
         }
         return result::success;
     }
     // If we have no job context, we just have to do a blocking wait.
     else
     {
         internal::stopwatch timer;
         timer.start();
         while (!job_handle_in.is_complete())
         {
             if (timer.get_elapsed_ms() > wait_timeout.duration)
             {
                 return result::timeout;
             }
     #if 0 // Not supported right now as helper thread must be converted to a fiber.
             if (!execute_next_job(assist_on_tasks, false))
     #endif
             {
                 std::unique_lock<std::mutex> lock(m_task_complete_mutex);
                 if (job_handle_in.is_complete())
                 {
                     break;
                 }
                 else
                 {
                     if (wait_timeout.is_infinite())
                     {
                         m_task_complete_cvar.wait(lock);
                     }
                     else
                     {
                         size_t ms_remaining = wait_timeout.duration - timer.get_elapsed_ms();
                         if (ms_remaining > 0)
{
                             m_task_complete_cvar.wait_for(lock, std::chrono::milliseconds(ms_remaining));
                         }
                     }
                 }
             }
         }
     }
     return result::success;
 }
wait_for_job_available()
void jobs::scheduler::wait_for_job_available () protected
Blocks until a new job has been singled as being available by notify_job_available.
Definition at line 1666 of file jobs_scheduler.cpp.
References jobs_profile_scope, m_available_jobs, m_destroying, m_task_available_cvar, m_task_available_mutex, and jobs::worker.
Referenced by get_next_job().
 {
     jobs_profile_scope(profile_scope_type::worker, "scheduler::wait_for_job_available", this);
     std::unique_lock<std::mutex> lock(m_task_available_mutex);
     if (m_destroying || m_available_jobs > 0)
     {
         return;
     }
     m_task_available_cvar.wait(lock);
 }
wait_until_idle()
result jobs::scheduler::wait_until_idle (timeout wait_timeout = timeout::infinite)
Waits until all jobs are complete and the schedulers workers are idle.
This call is blocking.
Parameters
wait_timeout If provided, this function will wait a maximum of this time. If the function returns due to a timeout the result provided will be result::timeout.
Returns
Value indicating the success of this function.
Definition at line 1321 of file jobs_scheduler.cpp.
References jobs::timeout::duration, execute_next_job(), jobs::internal::stopwatch::get_elapsed_ms(), is_idle(), jobs::timeout::is_infinite(), m_destroying, m_task_complete_cvar, m_task_complete_mutex, jobs::internal::stopwatch::start(), jobs::success, and jobs::timeout.
 {
     internal::stopwatch timer;
     timer.start();
     while (!is_idle() || m_destroying)
     {
         if (timer.get_elapsed_ms() > wait_timeout.duration)
         {
             return result::timeout;
         }
 #if 0 // Not supported right now as helper thread must be converted to a fiber.
         if (!execute_next_job(assist_on_tasks, false))
 #endif
         {
             std::unique_lock<std::mutex> lock(m_task_complete_mutex);
             if (is_idle() || m_destroying)
             {
                 break;
             }
             else
             {
                 if (wait_timeout.is_infinite())
                 {
                     m_task_complete_cvar.wait(lock);
                 }
                 else
                 {
                     size_t ms_remaining = wait_timeout.duration - timer.get_elapsed_ms();
                     if (ms_remaining > 0)
                     {
                         m_task_complete_cvar.wait_for(lock, std::chrono::milliseconds(ms_remaining));
                     }
                 }
             }
         }
     }
     return result::success;
 }
worker_entry_point()
void jobs::scheduler::worker_entry_point (size_t pool_index, size_t worker_index, const internal::thread & this_thread, const thread_pool & thread_pool) private
Entry point for all worker threads.
Definition at line 793 of file jobs_scheduler.cpp.
References jobs::internal::fiber::convert_fiber_to_thread(), jobs::internal::fiber::convert_thread_to_fiber(), execute_next_job(), jobs::scheduler::thread_pool::job_priorities, m_destroying, jobs::verbose, jobs::worker, WorkerThreadState, and write_log().
 {
     auto& thread_state = WorkerThreadState;
     thread_state.job_index = 0;
     thread_state.cloned_job_index = 0;
     thread_state.job_context.reset();
     thread_state.job_context.scheduler = this;
     thread_state.job_context.has_fiber = true;
     thread_state.job_context.is_fiber_raw = true;
     internal::fiber::convert_thread_to_fiber(thread_state.job_context.raw_fiber);
     thread_state.job_context.job_def = nullptr;
     thread_state.active_job_context = &thread_state.job_context;
     write_log(debug_log_verbosity::verbose, debug_log_group::worker, "worker started, pool=%zi worker=%zi priorities=0x%08x", pool_index, worker_index, thread_pool.job_priorities);
     thread_state.active_job_context->enter_scope(profile_scope_type::worker, false, "Worker (pool=%zi, index=%zi)", pool_index, worker_index);
     while (!m_destroying)
     {
         execute_next_job(thread_pool.job_priorities, true);
     }
     thread_state.active_job_context->leave_scope();
     write_log(debug_log_verbosity::verbose, debug_log_group::worker, "worker terminated, pool=%zi worker=%zi", pool_index, worker_index);
     internal::fiber::convert_fiber_to_thread();
 }
worker_fiber_entry_point()
void jobs::scheduler::worker_fiber_entry_point (size_t pool_index, size_t worker_index) private
Entry point for all worker job fibers.
Definition at line 824 of file jobs_scheduler.cpp.
References execute_fiber_job(), switch_context(), jobs::verbose, jobs::worker, WorkerThreadState, and write_log().
 {
     write_log(debug_log_verbosity::verbose, debug_log_group::worker, "fiber started, pool=%zi worker=%zi", pool_index, worker_index);
     while (true)
     {
         // Execute the job we have been provided.
         execute_fiber_job();
         // Switch back to the main worker thread fiber.
         switch_context(WorkerThreadState.job_context);
     }
     write_log(debug_log_verbosity::verbose, debug_log_group::worker, "fiber terminated, pool=%zi worker=%zi", pool_index, worker_index);
 }
write_log()
void jobs::scheduler::write_log (debug_log_verbosity level, debug_log_group group, const char * message, ...) protected
Writes a log message to sink provided by set_debug_output.
Parameters
level Verbosity level of log message.
group Semantic group this message belongs to.
message Printf style format for this log.
... Arguments for printf formatting of message.
Definition at line 750 of file jobs_scheduler.cpp.
References jobs::internal::debug_log_group_strings, jobs::internal::debug_log_verbosity_strings, m_debug_output_function, m_debug_output_max_verbosity, m_log_buffer, m_log_format_buffer, m_log_mutex, m_worker_thread_state, and max_log_size.
Referenced by add_job_dependency(), allocate_fiber(), create_counter(), create_job(), dispatch_batch(), dispatch_job(), jobs::internal::job_context::enter_scope(), execute_fiber_job(), execute_next_job(), get_next_job_from_queue(), init(), jobs::internal::callback_scheduler::schedule(), worker_entry_point(), worker_fiber_entry_point(), and ~scheduler().
 {
     if (m_debug_output_function == nullptr)
     {
         return;
     }
     if ((int)level > (int)m_debug_output_max_verbosity)
     {
         return;
     }
     std::lock_guard<std::mutex> lock(m_log_mutex);
     // Format message.
     va_list list;
     va_start(list, message);
     vsnprintf(m_log_buffer, max_log_size, message, list);
     va_end(list);
     // Format log in format:
     //  [verbose] warning: message
 #if defined(JOBS_USE_VERBOSE_LOGGING)
     snprintf(m_log_format_buffer, max_log_size, "[%08x][%p][%s] %s: %s\n",
         *reinterpret_cast<unsigned int*>(&std::this_thread::get_id()),
         m_worker_thread_state,
         internal::debug_log_group_strings[(int)group],
         internal::debug_log_verbosity_strings[(int)level],
         m_log_buffer);
 #else
     snprintf(m_log_format_buffer, max_log_size, "[%s] %s: %s\n",
         internal::debug_log_group_strings[(int)group],
         internal::debug_log_verbosity_strings[(int)level],
         m_log_buffer);
 #endif
     m_debug_output_function(level, group, m_log_format_buffer);
 }
Friends And Related Function Documentation
counter_handle
friend class counter_handle friend
Definition at line 411 of file jobs_scheduler.h.
Referenced by create_counter().
event_handle
friend class event_handle friend
Definition at line 410 of file jobs_scheduler.h.
Referenced by create_event().
internal::callback_scheduler
friend class internal::callback_scheduler friend
Definition at line 413 of file jobs_scheduler.h.
internal::job_context
friend class internal::job_context friend
Definition at line 412 of file jobs_scheduler.h.
internal::profile_scope_internal
friend class internal::profile_scope_internal friend
Definition at line 414 of file jobs_scheduler.h.
job_handle
friend class job_handle friend
Definition at line 409 of file jobs_scheduler.h.
Referenced by add_job_dependency(), create_job(), and wait_for_job().
Field Documentation
m_active_job_count
std::atomic<size_t> jobs::scheduler::m_active_job_count { 0 } private
Number of jobs that have been dispatched but not completed yet.
Definition at line 833 of file jobs_scheduler.h.
Referenced by complete_job(), dispatch_batch(), dispatch_job(), and is_idle().
m_available_jobs
std::atomic<size_t> jobs::scheduler::m_available_jobs { 0 } private
Number of jobs waiting in queues to be executed.
Definition at line 836 of file jobs_scheduler.h.
Referenced by get_next_job_from_queue(), notify_job_available(), and wait_for_job_available().
m_callback_scheduler
internal::callback_scheduler jobs::scheduler::m_callback_scheduler private
Instance responsable for queueing and calling latent callbacks.
Definition at line 845 of file jobs_scheduler.h.
Referenced by init(), jobs::counter_handle::remove(), jobs::counter_handle::wait_for(), and wait_for_job().
m_counter_pool
internal::fixed_pool<internal::counter_definition> jobs::scheduler::m_counter_pool private
Pool of events that can be allocated.
Definition at line 842 of file jobs_scheduler.h.
Referenced by create_counter(), free_counter(), and init().
m_debug_output_function
debug_output_function jobs::scheduler::m_debug_output_function = nullptr private
Function to pass all debug output
Definition at line 800 of file jobs_scheduler.h.
Referenced by set_debug_output(), and write_log().
m_debug_output_max_verbosity
debug_log_verbosity jobs::scheduler::m_debug_output_max_verbosity private
Max output verbosity of log messages.
Definition at line 803 of file jobs_scheduler.h.
Referenced by set_debug_output(), and write_log().
m_destroying
bool jobs::scheduler::m_destroying = false private
True if the scheduler is being torn down and threads need to exit.
Definition at line 791 of file jobs_scheduler.h.
Referenced by get_next_job(), wait_for_job_available(), wait_until_idle(), worker_entry_point(), and ~scheduler().
m_fiber_pool_count
size_t jobs::scheduler::m_fiber_pool_count = 0 private
Number of fiber pools that have been added.
Definition at line 779 of file jobs_scheduler.h.
Referenced by add_fiber_pool(), allocate_fiber(), init(), and ~scheduler().
m_fiber_pools
fiber_pool jobs::scheduler::m_fiber_pools[max_fiber_pools] private
Array of fiber pools that have been added.
Definition at line 782 of file jobs_scheduler.h.
Referenced by add_fiber_pool(), init(), and ~scheduler().
m_fiber_pools_sorted_by_stack
fiber_pool* jobs::scheduler::m_fiber_pools_sorted_by_stack[max_fiber_pools] private
Array of pointers to fiber pools, sorted by stack size
Definition at line 785 of file jobs_scheduler.h.
Referenced by allocate_fiber(), enter_context(), execute_next_job(), free_fiber(), and init().
m_initialized
bool jobs::scheduler::m_initialized = false private
True if this scheduler has been initialized.
Definition at line 788 of file jobs_scheduler.h.
Referenced by add_fiber_pool(), add_thread_pool(), init(), set_debug_output(), set_max_callbacks(), set_max_counters(), set_max_dependencies(), set_max_jobs(), set_max_profile_scopes(), set_memory_functions(), and set_profile_functions().
m_job_dependency_pool
internal::fixed_pool<internal::job_dependency> jobs::scheduler::m_job_dependency_pool private
Pool of dependencies to be allocated.
Definition at line 839 of file jobs_scheduler.h.
Referenced by add_job_dependency(), clear_job_dependencies(), and init().
m_job_pool
internal::fixed_pool<internal::job_definition> jobs::scheduler::m_job_pool private
Pool of jobs that can be allocated.
Definition at line 797 of file jobs_scheduler.h.
Referenced by create_job(), free_job(), and init().
m_log_buffer
char jobs::scheduler::m_log_buffer[max_log_size] private
Buffer used for creating log messages.
Definition at line 809 of file jobs_scheduler.h.
Referenced by write_log().
m_log_format_buffer
char jobs::scheduler::m_log_format_buffer[max_log_size] private
Buffer used for creating log message formats.
Definition at line 806 of file jobs_scheduler.h.
Referenced by write_log().
m_log_mutex
std::mutex jobs::scheduler::m_log_mutex private
Mutex for writing to the log
Definition at line 812 of file jobs_scheduler.h.
Referenced by write_log().
m_max_callbacks
size_t jobs::scheduler::m_max_callbacks = 100 private
Maximum number of callbacks we can have.
Definition at line 756 of file jobs_scheduler.h.
Referenced by init(), and set_max_callbacks().
m_max_counters
size_t jobs::scheduler::m_max_counters = 100 private
Maximum number of counters we can have.
Definition at line 753 of file jobs_scheduler.h.
Referenced by init(), and set_max_counters().
m_max_dependencies
size_t jobs::scheduler::m_max_dependencies = 100 private
Maximum number of dependencies jobs can have.
Definition at line 747 of file jobs_scheduler.h.
Referenced by init(), and set_max_dependencies().
m_max_jobs
size_t jobs::scheduler::m_max_jobs = 100 private
Maximum number of jobs this scheduler can handle concurrently.
Definition at line 744 of file jobs_scheduler.h.
Referenced by init(), and set_max_jobs().
m_max_profile_scopes
size_t jobs::scheduler::m_max_profile_scopes = 1000 private
Maximum number of profile scopes we can have.
Definition at line 750 of file jobs_scheduler.h.
Referenced by init(), and set_max_profile_scopes().
m_memory_functions
memory_functions jobs::scheduler::m_memory_functions private
Trampolined memory functions that also log allocations.
Definition at line 764 of file jobs_scheduler.h.
Referenced by init(), and ~scheduler().
m_pending_job_queues
job_queue jobs::scheduler::m_pending_job_queues[(int) priority::count] private
Pending job queues, one for each priority.
Definition at line 818 of file jobs_scheduler.h.
Referenced by get_next_job(), init(), requeue_job(), and requeue_job_batch().
m_platform_fiber_aware
bool jobs::scheduler::m_platform_fiber_aware = false private
True if the platform is fiber-aware for profiling purposes. Means we don't have to push/pop profile stack when we switch fiber context.
Definition at line 794 of file jobs_scheduler.h.
Referenced by enter_context(), init(), and leave_context().
m_profile_functions
profile_functions jobs::scheduler::m_profile_functions private
User-defined profiling functions.
Definition at line 767 of file jobs_scheduler.h.
Referenced by enter_context(), jobs::internal::job_context::enter_scope(), leave_context(), jobs::internal::job_context::leave_scope(), jobs::internal::profile_scope_internal::profile_scope_internal(), scheduler(), and set_profile_functions().
m_profile_scope_pool
internal::fixed_pool<internal::profile_scope_definition> jobs::scheduler::m_profile_scope_pool private
Profiling values
Definition at line 848 of file jobs_scheduler.h.
Referenced by alloc_scope(), free_scope(), and init().
m_profiling_active
bool jobs::scheduler::m_profiling_active = false static private
Determines if profiling is active or not.
Definition at line 869 of file jobs_scheduler.h.
Referenced by is_profiling_active(), and set_profile_functions().
m_raw_memory_functions
memory_functions jobs::scheduler::m_raw_memory_functions private
User-defined memory allocation functions.
Definition at line 761 of file jobs_scheduler.h.
Referenced by init(), scheduler(), and set_memory_functions().
m_task_available_cvar
std::condition_variable jobs::scheduler::m_task_available_cvar private
Task available condition variable
Definition at line 824 of file jobs_scheduler.h.
Referenced by notify_job_available(), and wait_for_job_available().
m_task_available_mutex
std::mutex jobs::scheduler::m_task_available_mutex private
Task available mutex
Definition at line 821 of file jobs_scheduler.h.
Referenced by wait_for_job_available().
m_task_complete_cvar
std::condition_variable jobs::scheduler::m_task_complete_cvar private
Task complete condition variable
Definition at line 830 of file jobs_scheduler.h.
Referenced by notify_job_complete(), wait_for_job(), and wait_until_idle().
m_task_complete_mutex
std::mutex jobs::scheduler::m_task_complete_mutex private
Task complete mutex
Definition at line 827 of file jobs_scheduler.h.
Referenced by wait_for_job(), and wait_until_idle().
m_thread_pool_count
size_t jobs::scheduler::m_thread_pool_count = 0 private
Number of thread pools that have been added.
Definition at line 770 of file jobs_scheduler.h.
Referenced by add_thread_pool(), init(), and ~scheduler().
m_thread_pools
thread_pool jobs::scheduler::m_thread_pools[max_thread_pools] private
Array of thread pools that have been added.
Definition at line 773 of file jobs_scheduler.h.
Referenced by add_thread_pool(), init(), and ~scheduler().
m_total_memory_allocated
std::atomic<size_t> jobs::scheduler::m_total_memory_allocated { 0 } private
Total memory alloacted
Definition at line 815 of file jobs_scheduler.h.
Referenced by init().
m_worker_count
size_t jobs::scheduler::m_worker_count = 0 private
Total number of worker threads.
Definition at line 776 of file jobs_scheduler.h.
Referenced by init(), and notify_job_available().
m_worker_thread_scheduler
thread_local scheduler * jobs::scheduler::m_worker_thread_scheduler {nullptr} static private
Scheduler that owns the current worker thread
Definition at line 863 of file jobs_scheduler.h.
Referenced by get_active_job_context(), get_active_job_definition(), and get_worker_job_context().
m_worker_thread_state
thread_local scheduler::worker_thread_state * jobs::scheduler::m_worker_thread_state {nullptr} static private
Index of the current worker thread.
Definition at line 866 of file jobs_scheduler.h.
Referenced by write_log().
m_worker_thread_states
worker_thread_state* jobs::scheduler::m_worker_thread_states = nullptr private
Array of worker threads indexed by m_worker_job_index.
Definition at line 860 of file jobs_scheduler.h.
Referenced by init(), and ~scheduler().
max_fiber_pools
const size_t jobs::scheduler::max_fiber_pools = 16 static private
Maximum number of fiber pools that can be added.
Definition at line 738 of file jobs_scheduler.h.
Referenced by add_fiber_pool().
max_log_size
const int jobs::scheduler::max_log_size = 256 static private
Maximum size of each log message.
Definition at line 741 of file jobs_scheduler.h.
Referenced by write_log().
max_thread_pools
const size_t jobs::scheduler::max_thread_pools = 16 static private
Maximum number of threads pools that can be added.
Definition at line 735 of file jobs_scheduler.h.
Referenced by add_thread_pool().
The documentation for this class was generated from the following files:
C:/Projects/libjobs/inc/jobs_scheduler.h
C:/Projects/libjobs/src/jobs_scheduler.cpp