libjobs: jobs::internal::fiber Class Reference
jobs::internal::fiber Class Reference
#include <jobs_fiber.h>
Public Member Functions
fiber ()
fiber (const memory_functions &memory_functions)
~fiber ()
void destroy ()
result init (size_t stack_size, const fiber_entry_point &entry_point, const char *name)
Initializes this fiber.
result switch_to ()
Switches this threads execution context to this fiber.
Static Public Member Functions
static void convert_thread_to_fiber (fiber &result)
Converts the current thread to a fiber.
static void convert_fiber_to_thread ()
Converts the current fiber to a thread.
Private Attributes
memory_functions m_memory_functions
fiber_entry_point m_entry_point
bool m_is_thread = false
void * m_fiber_context = nullptr
Detailed Description
Encapsulates a single user-space thread's (aka. coroutine/fiber) context of execution.
Definition at line 54 of file jobs_fiber.h.
Constructor & Destructor Documentation
fiber() [1/2]
jobs::internal::fiber::fiber ()
Default constructor.
Definition at line 29 of file jobs_fiber.cpp.
 {
 }
fiber() [2/2]
jobs::internal::fiber::fiber (const memory_functions & memory_functions)
Constructor.
Parameters
memory_functions Scheduler defined memory functions used to override default memory allocation behaviour.
Definition at line 33 of file jobs_fiber.cpp.
     : m_memory_functions(memory_functions)
 {
 }
~fiber()
jobs::internal::fiber::~fiber ()
Destructor.
Definition at line 38 of file jobs_fiber.cpp.
References destroy().
 {
     destroy();
 }
Member Function Documentation
convert_fiber_to_thread()
void jobs::internal::fiber::convert_fiber_to_thread () static
Converts the current fiber to a thread.
This performs the inverse of convert_thread_to_fiber and should be invoked when the thread has finished performing any fiber operations.
Definition at line 167 of file jobs_fiber.cpp.
Referenced by jobs::scheduler::worker_entry_point().
 {
 #if defined(JOBS_PLATFORM_WINDOWS) || defined(JOBS_PLATFORM_XBOX_ONE)
     ConvertFiberToThread();
 #elif defined(JOBS_PLATFORM_PS4)
     //Nothing to do.
 #elif defined(JOBS_PLATFORM_SWITCH)
     //Nothing to do.
 #else
 #   error Unimplemented platform
 #endif
 }
convert_thread_to_fiber()
void jobs::internal::fiber::convert_thread_to_fiber (fiber & result) static
Converts the current thread to a fiber.
On some operating systems (notably windows) fibers can only be run by other fibers. so any worker threads dealing with fibers need to first be converted. Which is done using this function.
Definition at line 143 of file jobs_fiber.cpp.
References m_entry_point, and m_is_thread.
Referenced by jobs::scheduler::worker_entry_point().
 {
     result.m_entry_point = nullptr;
     result.m_is_thread = true;
 #if defined(JOBS_PLATFORM_WINDOWS) || defined(JOBS_PLATFORM_XBOX_ONE)
     result.m_fiber_handle = ConvertThreadToFiberEx(nullptr, FIBER_FLAG_FLOAT_SWITCH);
 #elif defined(JOBS_PLATFORM_PS4)
     // Nothing to do.
 #elif defined(JOBS_PLATFORM_SWITCH)
     // Nothing to do.
 #else
 #   error Unimplemented platform
 #endif
 }
destroy()
void jobs::internal::fiber::destroy ()
Disposes of all resources. Performed automatically in destructor if not called beforehand.
Definition at line 43 of file jobs_fiber.cpp.
References m_fiber_context, m_is_thread, m_memory_functions, and jobs::memory_functions::user_free.
Referenced by ~fiber().
 {
 #if defined(JOBS_PLATFORM_WINDOWS) || defined(JOBS_PLATFORM_XBOX_ONE)
     if (m_fiber_handle != nullptr && !m_is_thread)
     {
         DeleteFiber(m_fiber_handle);
         m_fiber_handle = nullptr;
     }
 #elif defined(JOBS_PLATFORM_PS4)
     if (m_fiber_handle_created && !m_is_thread)
     {
         sceFiberFinalize(&m_fiber_handle);
         m_fiber_handle_created = false;
     }
 #elif defined(JOBS_PLATFORM_SWITCH)
     if (m_fiber_handle_created && !m_is_thread)
     {
         nn::os::FinalizeFiber(&m_fiber_handle);
         m_fiber_handle_created = false;
     }
 #else
 #   error Unimplemented platform
 #endif
     if (m_fiber_context != nullptr)
     {
         m_memory_functions.user_free(m_fiber_context);
         m_fiber_context = nullptr;
     }
 }
init()
result jobs::internal::fiber::init (size_t stack_size, const fiber_entry_point & entry_point, const char * name)
Initializes this fiber.
Parameters
stack_size Size of the stack that should be allocated for this fibers execution context.
entry_point Function that this fiber should start running when executed.
name Descriptive name of this fiber.
Returns
Value indicating the success of this function.
Definition at line 82 of file jobs_fiber.cpp.
References jobs::error, m_entry_point, m_fiber_context, m_memory_functions, jobs::out_of_memory, jobs::platform_error, jobs::success, and jobs::memory_functions::user_alloc.
 {
     m_entry_point = entry_point;
 #if defined(JOBS_PLATFORM_WINDOWS) || defined(JOBS_PLATFORM_XBOX_ONE)
     m_fiber_handle = CreateFiberEx(stack_size, stack_size, FIBER_FLAG_FLOAT_SWITCH, trampoline_entry_point, this);
     if (m_fiber_handle == nullptr)
     {
         // Try and figure out some useful results if possible.
         DWORD error = GetLastError();
         if (error == ERROR_OUTOFMEMORY)
         {
             return result::out_of_memory;
         }
         return result::platform_error;
     }
 #elif defined(JOBS_PLATFORM_PS4)
     m_fiber_context = m_memory_functions.user_alloc(stack_size, SCE_FIBER_CONTEXT_ALIGNMENT);
     if (m_fiber_context == nullptr)
     {
         return result::out_of_memory;
     }
     int32_t ret = sceFiberInitialize(&m_fiber_handle, name, trampoline_entry_point, reinterpret_cast<uint64_t>(this), m_fiber_context, stack_size, nullptr);
     if (ret != SCE_OK)
     {
         return result::platform_error;
     }
     m_fiber_handle_created = true;
 #elif defined(JOBS_PLATFORM_SWITCH)
     // Size of stack must be aligned to this (there are no notes about this in the api
     // docs, but it will assert if you don't ...). Note this value is not the same as nn::os::FiberStackAlignment.
     static const int stack_size_alignment = 0x1000;
     stack_size = ((stack_size + stack_size_alignment - 1) / stack_size_alignment) * stack_size_alignment;
     m_fiber_context = m_memory_functions.user_alloc(stack_size, nn::os::FiberStackAlignment);
     if (m_fiber_context == nullptr)
     {
         return result::out_of_memory;
     }
     nn::os::InitializeFiber(&m_fiber_handle, trampoline_entry_point, reinterpret_cast<void*>(this), m_fiber_context, stack_size, 0);
     m_fiber_handle_created = true;
 #else
 #   error Unimplemented platform
 #endif
     return result::success;
 }
switch_to()
result jobs::internal::fiber::switch_to ()
Switches this threads execution context to this fiber.
Returns
Value indicating the success of this function.
Definition at line 188 of file jobs_fiber.cpp.
References m_entry_point, m_is_thread, jobs::platform_error, and jobs::success.
Referenced by jobs::scheduler::enter_context().
 {
 #if defined(JOBS_PLATFORM_WINDOWS) || defined(JOBS_PLATFORM_XBOX_ONE)
     SwitchToFiber(m_fiber_handle);
 #elif defined(JOBS_PLATFORM_PS4)
     if (m_is_thread)
     {
         int32_t ret = sceFiberReturnToThread(0, 0);
         if (ret != SCE_OK)
         {
             return result::platform_error;
         }
     }
     else
     {
         int32_t ret = sceFiberRun(&m_fiber_handle, 0, 0);
         if (ret != SCE_OK)
         {
             return result::platform_error;
         }
     }
 #elif defined(JOBS_PLATFORM_SWITCH)
     if (m_is_thread)
     {
         nn::os::SwitchToFiber(nullptr);
     }
     else
     {
         nn::os::SwitchToFiber(&m_fiber_handle);
     }
 #else
 #   error Unimplemented platform
 #endif
     return result::success;
 }
Field Documentation
m_entry_point
fiber_entry_point jobs::internal::fiber::m_entry_point private
User defined entry point to execute when the fiber is run.
Definition at line 139 of file jobs_fiber.h.
Referenced by convert_thread_to_fiber(), init(), and switch_to().
m_fiber_context
void* jobs::internal::fiber::m_fiber_context = nullptr private
Stack space allocated to fiber context.
Definition at line 145 of file jobs_fiber.h.
Referenced by destroy(), and init().
m_is_thread
bool jobs::internal::fiber::m_is_thread = false private
Stack space allocated to fiber context.
Definition at line 142 of file jobs_fiber.h.
Referenced by convert_thread_to_fiber(), destroy(), and switch_to().
m_memory_functions
memory_functions jobs::internal::fiber::m_memory_functions private
Memory allocation functions provided by the scheduler.
Definition at line 136 of file jobs_fiber.h.
Referenced by destroy(), and init().
The documentation for this class was generated from the following files:
C:/Projects/libjobs/inc/jobs_fiber.h
C:/Projects/libjobs/src/jobs_fiber.cpp