libjobs: jobs::fiber Class Reference
jobs::fiber Class Reference
#include <jobs_fiber.h>
Public Member Functions
fiber ()
fiber (const memory_functions &memory_functions)
~fiber ()
result init (size_t stack_size, const fiber_entry_point &entry_point)
Initializes this fiber.
result switch_to ()
Switches this threads execution context to this fiber.
Static Public Member Functions
static fiber convert_thread_to_fiber ()
Converts the current thread to a fiber.
static void convert_fiber_to_thread ()
Converts the current fiber to a thread.
Private Attributes
memory_functions m_memory_functions
fiber_entry_point m_entry_point
Detailed Description
Encapsulates a single user-space thread's (aka. coroutine/fiber) context of execution.
Definition at line 47 of file jobs_fiber.h.
Constructor & Destructor Documentation
fiber() [1/2]
jobs::fiber::fiber ()
Default constructor.
Definition at line 28 of file jobs_fiber.cpp.
 {
 }
fiber() [2/2]
jobs::fiber::fiber (const memory_functions & memory_functions)
Constructor.
Parameters
memory_function Scheduler defined memory functions used to override default memory allocation behaviour.
Definition at line 32 of file jobs_fiber.cpp.
     : m_memory_functions(memory_functions)
 {
 }
~fiber()
jobs::fiber::~fiber ()
Destructor.
Definition at line 37 of file jobs_fiber.cpp.
 {
 }
Member Function Documentation
convert_fiber_to_thread()
void jobs::fiber::convert_fiber_to_thread () static
Converts the current fiber to a thread.
This performs the inverse of convert_thread_to_fiber and should be invoked when the thread has finished performing any fiber operations.
Definition at line 79 of file jobs_fiber.cpp.
Referenced by jobs::scheduler::worker_entry_point().
 {
 #ifdef JOBS_PLATFORM_WINDOWS
     ConvertFiberToThread();
 #else
 #   error Unimplemented platform
 #endif
 }
convert_thread_to_fiber()
fiber jobs::fiber::convert_thread_to_fiber () static
Converts the current thread to a fiber.
On some operating systems (notably windows) fibers can only be run by other fibers. so any worker threads dealing with fibers need to first be converted. Which is done using this function.
Definition at line 65 of file jobs_fiber.cpp.
References m_entry_point.
Referenced by jobs::scheduler::worker_entry_point().
 {
     fiber new_fiber;
     new_fiber.m_entry_point = nullptr;
 #ifdef JOBS_PLATFORM_WINDOWS
     new_fiber.m_fiber_handle = ConvertThreadToFiberEx(nullptr, FIBER_FLAG_FLOAT_SWITCH);;
 #else
 #   error Unimplemented platform
 #endif
     return new_fiber;
 }
init()
result jobs::fiber::init (size_t stack_size, const fiber_entry_point & entry_point)
Initializes this fiber.
Parameters
stack_size Size of the stack that should be allocated for this fibers execution context.
entry_point Function that this fiber should start running when executed.
Returns
Value indicating the success of this function.
Definition at line 41 of file jobs_fiber.cpp.
References jobs::error, m_entry_point, jobs::out_of_memory, jobs::platform_error, and jobs::success.
 {
     m_entry_point = entry_point;
 #ifdef JOBS_PLATFORM_WINDOWS
     m_fiber_handle = CreateFiberEx(stack_size, stack_size, FIBER_FLAG_FLOAT_SWITCH, trampoline_entry_point, this);
     if (m_fiber_handle == nullptr)
     {
         // Try and figure out some useful results if possible.
         DWORD error = GetLastError();
         if (error == ERROR_OUTOFMEMORY)
         {
             return result::out_of_memory;
         }
         return result::platform_error;
     }
 #else
 #   error Unimplemented platform
 #endif
     return result::success;
 }
switch_to()
result jobs::fiber::switch_to ()
Switches this threads execution context to this fiber.
Returns
Value indicating the success of this function.
Definition at line 88 of file jobs_fiber.cpp.
References m_entry_point, and jobs::success.
Referenced by jobs::scheduler::enter_context().
 {
 #ifdef JOBS_PLATFORM_WINDOWS
     SwitchToFiber(m_fiber_handle);
 #else
 #   error Unimplemented platform
 #endif
     return result::success;
 }
Field Documentation
m_entry_point
fiber_entry_point jobs::fiber::m_entry_point private
User defined entry point to execute when the fiber is run.
Definition at line 115 of file jobs_fiber.h.
Referenced by convert_thread_to_fiber(), init(), and switch_to().
m_memory_functions
memory_functions jobs::fiber::m_memory_functions private
Memory allocation functions provided by the scheduler.
Definition at line 112 of file jobs_fiber.h.
The documentation for this class was generated from the following files:
C:/Projects/libjobs/inc/jobs_fiber.h
C:/Projects/libjobs/src/jobs_fiber.cpp