libjobs: jobs::timeout Struct Reference
jobs::timeout Struct Reference
Represents a period of time used as a timeout for a blocking function.
#include <jobs_utils.h>
Public Member Functions
timeout ()
Default constructor.
timeout (uint64_t inDuration)
Constructor.
bool is_infinite ()
Returns true if this timeout is infinite.
Data Fields
uint64_t duration
Static Public Attributes
static const timeout infinite = timeout(UINT64_MAX)
Detailed Description
Represents a period of time used as a timeout for a blocking function.
Definition at line 1083 of file jobs_utils.h.
Constructor & Destructor Documentation
timeout() [1/2]
jobs::timeout::timeout () inline
Default constructor.
Definition at line 1093 of file jobs_utils.h.
         : duration(0)
     {
     }
timeout() [2/2]
jobs::timeout::timeout (uint64_t inDuration) inline
Constructor.
Parameters
inDuration Duration in milliseconds of this timeout.
Definition at line 1103 of file jobs_utils.h.
         : duration(inDuration)
     {
     }
Member Function Documentation
is_infinite()
bool jobs::timeout::is_infinite () inline
Returns true if this timeout is infinite.
Returns
true if an infinite timeout.
Definition at line 1113 of file jobs_utils.h.
Referenced by jobs::counter_handle::remove(), jobs::scheduler::sleep(), jobs::counter_handle::wait_for(), jobs::scheduler::wait_for_job(), and jobs::scheduler::wait_until_idle().
     {
         return duration == infinite.duration;
     }
Field Documentation
duration
uint64_t jobs::timeout::duration
Duration of this timeout in milliseconds.
Definition at line 1088 of file jobs_utils.h.
Referenced by jobs::internal::callback_scheduler::get_ms_till_next_callback(), jobs::counter_handle::remove(), jobs::internal::callback_scheduler::run_callbacks(), jobs::scheduler::sleep(), jobs::counter_handle::wait_for(), jobs::scheduler::wait_for_job(), and jobs::scheduler::wait_until_idle().
infinite
const timeout jobs::timeout::infinite = timeout(UINT64_MAX) static
Represents an infinite, non-ending timeout.
Definition at line 1119 of file jobs_utils.h.
Referenced by jobs::internal::stopwatch::get_elapsed_us(), jobs::scheduler::get_job_definition(), and jobs::internal::callback_scheduler::get_ms_till_next_callback().
The documentation for this struct was generated from the following files:
C:/Projects/libjobs/inc/jobs_utils.h
C:/Projects/libjobs/src/jobs_utils.cpp