libjobs: jobs::stopwatch Struct Reference
jobs::stopwatch Struct Reference
Utility class used to time the duration between two points in code.
#include <jobs_utils.h>
Public Member Functions
void start ()
void stop ()
size_t get_elapsed_ms ()
Private Attributes
std::chrono::high_resolution_clock::time_point m_start_time
std::chrono::high_resolution_clock::time_point m_end_time
bool m_has_end = false
Detailed Description
Utility class used to time the duration between two points in code.
Definition at line 74 of file jobs_utils.h.
Member Function Documentation
get_elapsed_ms()
size_t jobs::stopwatch::get_elapsed_ms ()
Todo:
Definition at line 40 of file jobs_utils.cpp.
References jobs::count, m_end_time, m_has_end, and m_start_time.
Referenced by jobs::scheduler::wait_for_job(), and jobs::scheduler::wait_until_idle().
 {
     std::chrono::high_resolution_clock::time_point end_time;
     if (m_has_end)
     {
         end_time = m_end_time;
     }
     else
     {
         end_time = std::chrono::high_resolution_clock::now();
     }
     float elapsed = std::chrono::duration<float, std::chrono::milliseconds::period>(end_time - m_start_time).count();
     return (size_t)elapsed;
 }
start()
void jobs::stopwatch::start ()
Todo:
Definition at line 28 of file jobs_utils.cpp.
References m_has_end, and m_start_time.
Referenced by jobs::scheduler::wait_for_job(), and jobs::scheduler::wait_until_idle().
 {
     m_start_time = std::chrono::high_resolution_clock::now();
     m_has_end = false;
 }
stop()
void jobs::stopwatch::stop ()
Todo:
Definition at line 34 of file jobs_utils.cpp.
References m_end_time, and m_has_end.
 {
     m_end_time = std::chrono::high_resolution_clock::now();
     m_has_end = true;
 }
Field Documentation
m_end_time
std::chrono::high_resolution_clock::time_point jobs::stopwatch::m_end_time private
Todo:
Definition at line 93 of file jobs_utils.h.
Referenced by get_elapsed_ms(), and stop().
m_has_end
bool jobs::stopwatch::m_has_end = false private
Todo:
Definition at line 96 of file jobs_utils.h.
Referenced by get_elapsed_ms(), start(), and stop().
m_start_time
std::chrono::high_resolution_clock::time_point jobs::stopwatch::m_start_time private
Todo:
Definition at line 90 of file jobs_utils.h.
Referenced by get_elapsed_ms(), and start().
The documentation for this struct was generated from the following files:
C:/Projects/libjobs/inc/jobs_utils.h
C:/Projects/libjobs/src/jobs_utils.cpp