libjobs: jobs::atomic_queue< data_type > Struct Template Reference
jobs::atomic_queue< data_type > Struct Template Reference
#include <jobs_utils.h>
Public Member Functions
~atomic_queue ()
result init (const memory_functions &memory_functions, size_t capacity)
result pop (data_type &result)
result push (data_type value)
size_t count ()
bool is_empty ()
Private Attributes
data_type * m_buffer = nullptr
memory_functions m_memory_functions
size_t m_head
size_t m_tail
std::atomic< size_t > m_uncomitted_head
std::atomic< size_t > m_uncomitted_tail
size_t m_capacity
Detailed Description
template<typename data_type>
struct jobs::atomic_queue< data_type >
Todo:
Definition at line 119 of file jobs_utils.h.
Constructor & Destructor Documentation
~atomic_queue()
template<typename data_type> jobs::atomic_queue< data_type >::~atomic_queue () inline
Todo:
Definition at line 124 of file jobs_utils.h.
     {
         if (m_buffer != nullptr)
         {
             m_memory_functions.user_free(m_buffer);
             m_buffer = nullptr;
         }
     }
Member Function Documentation
count()
template<typename data_type> size_t jobs::atomic_queue< data_type >::count () inline
Todo:
Definition at line 209 of file jobs_utils.h.
Referenced by jobs::scheduler::get_next_job_from_queue().
     {
         printf("Head:%zi tail:%zi count:%zi\n", m_head, m_tail, (m_head - m_tail));
         return (m_head - m_tail);
     }
init()
template<typename data_type> result jobs::atomic_queue< data_type >::init (const memory_functions & memory_functions, size_t capacity) inline
Todo:
Definition at line 134 of file jobs_utils.h.
Referenced by jobs::scheduler::init().
     {
         // implemented as an atomic circular buffer.
         m_buffer = (data_type*)memory_functions.user_alloc(sizeof(data_type) * capacity);
         m_memory_functions = memory_functions;
         m_head = 0;
         m_tail = 0;
         m_uncomitted_head = 0;
         m_uncomitted_tail = 0;
         m_capacity = capacity;
         return result::success;
     }
is_empty()
template<typename data_type> bool jobs::atomic_queue< data_type >::is_empty () inline
Todo:
Definition at line 216 of file jobs_utils.h.
     {
         return (m_head == m_tail);
     }
pop()
template<typename data_type> result jobs::atomic_queue< data_type >::pop (data_type & result) inline
Todo:
Definition at line 151 of file jobs_utils.h.
Referenced by jobs::scheduler::get_next_job_from_queue().
     {
         while (true)
         {
             size_t old_tail = m_tail;
             size_t new_tail = old_tail + 1;
             size_t diff = (m_head - new_tail);
             if (diff < 0 || diff > m_capacity)
             {
                 return result::empty;
             }
             if (m_uncomitted_tail.compare_exchange_strong(old_tail, new_tail))
             {
                 result =  m_buffer[old_tail % m_capacity];
                 m_tail = m_uncomitted_tail;
                 break;
             }
             else
             {
                 _mm_pause();
             }
         }
         return result::success;
     }
push()
template<typename data_type> result jobs::atomic_queue< data_type >::push (data_type value) inline
Todo:
Definition at line 180 of file jobs_utils.h.
Referenced by jobs::scheduler::dispatch_job(), jobs::scheduler::get_next_job_from_queue(), and jobs::scheduler::requeue_job().
     {
         while (true)
         {
             size_t old_head = m_head;
             size_t new_head = old_head + 1;
             size_t diff = (new_head - m_tail);
             if (diff < 0 || diff > m_capacity)
             {
                 continue;
             }
             if (m_uncomitted_head.compare_exchange_strong(old_head, new_head))
             {
                 m_buffer[old_head % m_capacity] = value;
                 m_head = m_uncomitted_head;
                 break;
             }
             else
             {
                 _mm_pause();
             }
         }
         return result::success;
     }
Field Documentation
m_buffer
template<typename data_type> data_type* jobs::atomic_queue< data_type >::m_buffer = nullptr private
Todo:
Definition at line 224 of file jobs_utils.h.
m_capacity
template<typename data_type> size_t jobs::atomic_queue< data_type >::m_capacity private
Todo:
Definition at line 242 of file jobs_utils.h.
m_head
template<typename data_type> size_t jobs::atomic_queue< data_type >::m_head private
Todo:
Definition at line 230 of file jobs_utils.h.
m_memory_functions
template<typename data_type> memory_functions jobs::atomic_queue< data_type >::m_memory_functions private
Todo:
Definition at line 227 of file jobs_utils.h.
m_tail
template<typename data_type> size_t jobs::atomic_queue< data_type >::m_tail private
Todo:
Definition at line 233 of file jobs_utils.h.
m_uncomitted_head
template<typename data_type> std::atomic<size_t> jobs::atomic_queue< data_type >::m_uncomitted_head private
Todo:
Definition at line 236 of file jobs_utils.h.
m_uncomitted_tail
template<typename data_type> std::atomic<size_t> jobs::atomic_queue< data_type >::m_uncomitted_tail private
Todo:
Definition at line 239 of file jobs_utils.h.
The documentation for this struct was generated from the following file:
C:/Projects/libjobs/inc/jobs_utils.h