libjobs: jobs::internal::atomic_queue< data_type > Struct Template Reference
jobs::internal::atomic_queue< data_type > Struct Template Reference
Thread-safe lock-less queue.
#include <jobs_utils.h>
Public Member Functions
~atomic_queue ()
result init (const memory_functions &memory_functions, int64_t capacity)
Initializes this queue to the given capacity.
result pop (data_type &result, bool can_block=false)
Pops off the first value in the queue.
result push (data_type value, bool can_block=true)
Pushes a new value into the queue.
result push_batch (data_type *buffer, size_t stride, size_t count, bool can_block=true)
Pushes a number of items into the queue in a single operation.
size_t count ()
Gets the number of items in the queue.
bool is_empty ()
Gets if this queue is empty.
Private Attributes
data_type * m_buffer = nullptr
memory_functions m_memory_functions
int64_t m_head
int64_t m_tail
std::atomic< int64_t > m_uncomitted_head
std::atomic< int64_t > m_uncomitted_tail
int64_t m_capacity
Detailed Description
template<typename data_type>
struct jobs::internal::atomic_queue< data_type >
Thread-safe lock-less queue.
This is implemented internally as a ring buffer.
Definition at line 566 of file jobs_utils.h.
Constructor & Destructor Documentation
~atomic_queue()
template<typename data_type> jobs::internal::atomic_queue< data_type >::~atomic_queue () inline
Destructor.
Definition at line 571 of file jobs_utils.h.
     {
         if (m_buffer != nullptr)
         {
             m_memory_functions.user_free(m_buffer);
             m_buffer = nullptr;
         }
     }
Member Function Documentation
count()
template<typename data_type> size_t jobs::internal::atomic_queue< data_type >::count () inline
Gets the number of items in the queue.
Returns
Number of items in the queue.
Definition at line 750 of file jobs_utils.h.
Referenced by jobs::scheduler::get_next_job_from_queue().
     {
         return (size_t)(m_head - m_tail);
     }
init()
template<typename data_type> result jobs::internal::atomic_queue< data_type >::init (const memory_functions & memory_functions, int64_t capacity) inline
Initializes this queue to the given capacity.
The only memory allocated by this queue is during this function.
Parameters
memory_functions Functions to use for allocating and deallocating queue buffers.
capacity Maximum capacity of queue.
Returns
Value indicating the success of this function.
Definition at line 590 of file jobs_utils.h.
Referenced by jobs::scheduler::init().
     {
         // implemented as an atomic circular buffer.
         m_buffer = (data_type*)memory_functions.user_alloc(sizeof(data_type) * capacity, alignof(data_type));
         m_memory_functions = memory_functions;
         m_head = 0;
         m_tail = 0;
         m_uncomitted_head = 0;
         m_uncomitted_tail = 0;
         m_capacity = capacity;
         return result::success;
     }
is_empty()
template<typename data_type> bool jobs::internal::atomic_queue< data_type >::is_empty () inline
Gets if this queue is empty.
Returns
True if queue is empty.
Definition at line 760 of file jobs_utils.h.
     {
         return (m_head == m_tail);
     }
pop()
template<typename data_type> result jobs::internal::atomic_queue< data_type >::pop (data_type & result, bool can_block = false) inline
Pops off the first value in the queue.
Parameters
result Reference to store poped value.
can_block If true and the queue is empty, this function will block until a value is available, otherwise result::empty will be returned.
Returns
Value indicating the success of this function.
Definition at line 615 of file jobs_utils.h.
Referenced by jobs::scheduler::get_next_job_from_queue().
     {
         while (true)
         {
             int64_t old_tail = m_tail;
             int64_t new_tail = old_tail + 1;
             int64_t diff = (m_head - new_tail);
             if (diff < 0)
             {
                 if (can_block)
                 {
                     continue;
                 }
                 else
                 {
                     return result::empty;
                 }
             }
             if (m_uncomitted_tail.compare_exchange_strong(old_tail, new_tail))
             {
                 result = m_buffer[old_tail % m_capacity];
                 m_tail = m_uncomitted_tail;
                 break;
             }
             else
             {
                 JOBS_YIELD();
             }
         }
         return result::success;
     }
push()
template<typename data_type> result jobs::internal::atomic_queue< data_type >::push (data_type value, bool can_block = true) inline
Pushes a new value into the queue.
Parameters
value New value to push into the queue.
can_block If true and the queue is full, this function will block until space is available, otherwise result::maximum_exceeded will be returned.
Returns
Value indicating the success of this function.
Definition at line 659 of file jobs_utils.h.
Referenced by jobs::scheduler::requeue_job().
     {
         while (true)
         {
             int64_t old_head = m_head;
             int64_t new_head = old_head + 1;
             int64_t diff = (new_head - m_tail);
             if (diff > m_capacity)
             {
                 if (can_block)
                 {
                     continue;
                 }
                 else
                 {
                     return result::maximum_exceeded;
                 }
             }
             if (m_uncomitted_head.compare_exchange_strong(old_head, new_head))
             {
                 m_buffer[old_head % m_capacity] = value;
                 m_head = m_uncomitted_head;
                 break;
             }
             else
             {
                 JOBS_YIELD();
             }
         }
         return result::success;
     }
push_batch()
template<typename data_type> result jobs::internal::atomic_queue< data_type >::push_batch (data_type * buffer, size_t stride, size_t count, bool can_block = true) inline
Pushes a number of items into the queue in a single operation.
Parameters
buffer Pointer to the first value to push into the queue.
stride Byte offset to add to buffer to get subsequent value.
count Number of values that need to be pushed into queue.
can_block If true and the queue is full, this function will block until space is available, otherwise result::maximum_exceeded will be returned.
Returns
Value indicating the success of this function.
Definition at line 705 of file jobs_utils.h.
Referenced by jobs::scheduler::requeue_job_batch().
     {
         while (true)
         {
             int64_t old_head = m_head;
             int64_t new_head = old_head + count;
             int64_t diff = (new_head - m_tail);
             if (diff > m_capacity)
             {
                 if (can_block)
                 {
                     continue;
                 }
                 else
                 {
                     return result::maximum_exceeded;
                 }
             }
             if (m_uncomitted_head.compare_exchange_strong(old_head, new_head))
             {
                 for (size_t i = 0; i < count; i++)
                 {
                     data_type* ptr = reinterpret_cast<data_type*>(reinterpret_cast<char*>(buffer) + (stride * i));
                     m_buffer[(old_head + i) % m_capacity] = *ptr;
                 }
                 m_head = m_uncomitted_head;
                 break;
             }
             else
             {
                 JOBS_YIELD();
             }
         }
         return result::success;
     }
Field Documentation
m_buffer
template<typename data_type> data_type* jobs::internal::atomic_queue< data_type >::m_buffer = nullptr private
Linear data buffer storing all values in queue.
Definition at line 768 of file jobs_utils.h.
m_capacity
template<typename data_type> int64_t jobs::internal::atomic_queue< data_type >::m_capacity private
Maximum number of items in queue.
Definition at line 786 of file jobs_utils.h.
m_head
template<typename data_type> int64_t jobs::internal::atomic_queue< data_type >::m_head private
Current write position in ring buffer. (Need to modulus to get buffer index).
Definition at line 774 of file jobs_utils.h.
m_memory_functions
template<typename data_type> memory_functions jobs::internal::atomic_queue< data_type >::m_memory_functions private
Memory functions used for memory allocation.
Definition at line 771 of file jobs_utils.h.
m_tail
template<typename data_type> int64_t jobs::internal::atomic_queue< data_type >::m_tail private
Current read position in ring buffer. (Need to modulus to get buffer index).
Definition at line 777 of file jobs_utils.h.
m_uncomitted_head
template<typename data_type> std::atomic<int64_t> jobs::internal::atomic_queue< data_type >::m_uncomitted_head private
Current position that a write is being permitted in-progress on.
Definition at line 780 of file jobs_utils.h.
m_uncomitted_tail
template<typename data_type> std::atomic<int64_t> jobs::internal::atomic_queue< data_type >::m_uncomitted_tail private
Current position that a read is being permitted in-progress on.
Definition at line 783 of file jobs_utils.h.
The documentation for this struct was generated from the following file:
C:/Projects/libjobs/inc/jobs_utils.h