libjobs: jobs::internal::stopwatch Struct Reference
jobs::internal::stopwatch Struct Reference
Utility class used to time the duration between two points in code.
#include <jobs_utils.h>
Public Member Functions
void start ()
void stop ()
uint64_t get_elapsed_ms ()
Number of elapsed milliseconds between start and stop calls.
uint64_t get_elapsed_us ()
Number of elapsed microseconds between start and stop calls.
Private Attributes
std::chrono::high_resolution_clock::time_point m_start_time
std::chrono::high_resolution_clock::time_point m_end_time
bool m_has_end = false
Detailed Description
Utility class used to time the duration between two points in code.
Definition at line 187 of file jobs_utils.h.
Member Function Documentation
get_elapsed_ms()
uint64_t jobs::internal::stopwatch::get_elapsed_ms ()
Number of elapsed milliseconds between start and stop calls.
If stop has not been called yet, this gives a running value.
Returns
Number of elapsed milliseconds.
Definition at line 62 of file jobs_utils.cpp.
References jobs::count, m_end_time, m_has_end, and m_start_time.
Referenced by jobs::internal::callback_scheduler::get_ms_till_next_callback(), jobs::counter_handle::remove(), jobs::internal::callback_scheduler::run_callbacks(), jobs::counter_handle::wait_for(), jobs::scheduler::wait_for_job(), and jobs::scheduler::wait_until_idle().
 {
     std::chrono::high_resolution_clock::time_point end_time;
     if (m_has_end)
     {
         end_time = m_end_time;
     }
     else
     {
         end_time = std::chrono::high_resolution_clock::now();
     }
     float elapsed = std::chrono::duration<float, std::chrono::milliseconds::period>(end_time - m_start_time).count();
     return (uint64_t)elapsed;
 }
get_elapsed_us()
uint64_t jobs::internal::stopwatch::get_elapsed_us ()
Number of elapsed microseconds between start and stop calls.
If stop has not been called yet, this gives a running value.
Returns
Number of elapsed microseconds.
Definition at line 79 of file jobs_utils.cpp.
References jobs::count, jobs::timeout::infinite, m_end_time, m_has_end, and m_start_time.
 {
     std::chrono::high_resolution_clock::time_point end_time;
     if (m_has_end)
     {
         end_time = m_end_time;
     }
     else
     {
         end_time = std::chrono::high_resolution_clock::now();
     }
     float elapsed = std::chrono::duration<float, std::chrono::microseconds::period>(end_time - m_start_time).count();
     return (uint64_t)elapsed;
 }
start()
void jobs::internal::stopwatch::start ()
Starts measuring time.
Definition at line 50 of file jobs_utils.cpp.
References m_has_end, and m_start_time.
Referenced by jobs::counter_handle::remove(), jobs::internal::callback_scheduler::schedule(), jobs::counter_handle::wait_for(), jobs::scheduler::wait_for_job(), and jobs::scheduler::wait_until_idle().
 {
     m_start_time = std::chrono::high_resolution_clock::now();
     m_has_end = false;
 }
stop()
void jobs::internal::stopwatch::stop ()
Stops measuring time.
Definition at line 56 of file jobs_utils.cpp.
References m_end_time, and m_has_end.
 {
     m_end_time = std::chrono::high_resolution_clock::now();
     m_has_end = true;
 }
Field Documentation
m_end_time
std::chrono::high_resolution_clock::time_point jobs::internal::stopwatch::m_end_time private
Timestamp when stop was called.
Definition at line 221 of file jobs_utils.h.
Referenced by get_elapsed_ms(), get_elapsed_us(), and stop().
m_has_end
bool jobs::internal::stopwatch::m_has_end = false private
If stop has been called and m_end_time is valid.
Definition at line 224 of file jobs_utils.h.
Referenced by get_elapsed_ms(), get_elapsed_us(), start(), and stop().
m_start_time
std::chrono::high_resolution_clock::time_point jobs::internal::stopwatch::m_start_time private
Timestamp when start was called.
Definition at line 218 of file jobs_utils.h.
Referenced by get_elapsed_ms(), get_elapsed_us(), and start().
The documentation for this struct was generated from the following files:
C:/Projects/libjobs/inc/jobs_utils.h
C:/Projects/libjobs/src/jobs_utils.cpp