libjobs: jobs::internal::multiple_writer_single_reader_list< data_type >::iterator Struct Reference
jobs::internal::multiple_writer_single_reader_list< data_type >::iterator Struct Reference
#include <jobs_utils.h>
Public Member Functions
iterator ()
~iterator ()
data_type value ()
Gets the value held by the current link iterator is at.
operator bool () const
Conversion to bool operator.
iterator & operator++ (int)
Post increment operator.
bool remove ()
Removes the current link.
Private Member Functions
bool start (multiple_writer_single_reader_list *owner, bool lock_required)
Starts itererating from the beginning of the given list.
bool next ()
Moves to the next value in the list.
Private Attributes
multiple_writer_single_reader_list * m_owner = nullptr
link * m_link = nullptr
bool m_locked = false
Friends
struct multiple_writer_single_reader_list< data_type >
Detailed Description
template<typename data_type>
struct jobs::internal::multiple_writer_single_reader_list< data_type >::iterator
Provides functionality to iterate over list in a thread-safe manner.
Definition at line 303 of file jobs_utils.h.
Constructor & Destructor Documentation
iterator()
template<typename data_type> jobs::internal::multiple_writer_single_reader_list< data_type >::iterator::iterator () inline
Constructor
Definition at line 308 of file jobs_utils.h.
         {
         }
~iterator()
template<typename data_type> jobs::internal::multiple_writer_single_reader_list< data_type >::iterator::~iterator () inline
Destructor
Definition at line 313 of file jobs_utils.h.
References jobs::internal::optional_lock< mutex_type >::m_locked.
         {
             if (m_locked)
             {
                 m_owner->m_lock.unlock();
                 m_locked = false;
             }
         }
Member Function Documentation
next()
template<typename data_type> bool jobs::internal::multiple_writer_single_reader_list< data_type >::iterator::next () inline private
Moves to the next value in the list.
Returns
True if there are more values to iterate over.
Definition at line 416 of file jobs_utils.h.
         {
             m_link = m_link->next;
             return (m_link != nullptr);
         }
operator bool()
template<typename data_type> jobs::internal::multiple_writer_single_reader_list< data_type >::iterator::operator bool () const inline
Conversion to bool operator.
Returns
True if there are more values to iterate over.
Definition at line 337 of file jobs_utils.h.
         {
             return m_link != nullptr;
         }
operator++()
template<typename data_type> iterator& jobs::internal::multiple_writer_single_reader_list< data_type >::iterator::operator++ (int) inline
Post increment operator.
Causes the iterator to move onto the next value in the list.
Returns
Reference to this iterator.
Definition at line 349 of file jobs_utils.h.
         {
             next();
             return *this;
         }
remove()
template<typename data_type> bool jobs::internal::multiple_writer_single_reader_list< data_type >::iterator::remove () inline
Removes the current link.
Returns
True if there are more values to iterate over.
Definition at line 360 of file jobs_utils.h.
References jobs::internal::multiple_writer_single_reader_list< data_type >::link::next, and jobs::internal::multiple_writer_single_reader_list< data_type >::link::prev.
Referenced by jobs::counter_handle::notify_value_changed().
         {
             // Remove first.
             link* original = m_link;
             link* next = m_link->next;
             if (original->next != nullptr)
             {
                 original->next->prev = original->prev;
             }
             if (original->prev != nullptr)
             {
                 original->prev->next = original->next;
             }
             if (original == m_owner->m_head.load())
             {
                 m_owner->m_head = original->next;
             }
             // Move onto next.
             m_link = next;
             return (m_link != nullptr);
         }
start()
template<typename data_type> bool jobs::internal::multiple_writer_single_reader_list< data_type >::iterator::start (multiple_writer_single_reader_list * owner, bool lock_required) inline private
Starts itererating from the beginning of the given list.
Parameters
owner List to iterate over.
lock_required If a read lock needs to be acquired on the list. If not its assumed the lock has been acquired further up the callstack.
Returns
True if there are more values to iterate over.
Definition at line 395 of file jobs_utils.h.
References jobs::internal::spinwait_mutex::lock(), jobs::internal::multiple_writer_single_reader_list< data_type >::m_lock, and jobs::internal::optional_lock< mutex_type >::m_locked.
         {
             assert(m_locked == false);
             m_owner = owner;
             if (lock_required)
             {
                 //printf("Locked\n");
                 m_owner->m_lock.lock();
                 m_locked = true;
             }
             m_link = m_owner->m_head.load();
             return (m_link != nullptr);
         }
value()
template<typename data_type> data_type jobs::internal::multiple_writer_single_reader_list< data_type >::iterator::value () inline
Gets the value held by the current link iterator is at.
Returns
Value of current link.
Definition at line 327 of file jobs_utils.h.
Referenced by jobs::scheduler::complete_job(), and jobs::counter_handle::notify_value_changed().
         {
             return m_link->value;
         }
Friends And Related Function Documentation
multiple_writer_single_reader_list< data_type >
template<typename data_type> friend struct multiple_writer_single_reader_list< data_type > friend
Definition at line 424 of file jobs_utils.h.
Field Documentation
m_link
template<typename data_type> link* jobs::internal::multiple_writer_single_reader_list< data_type >::iterator::m_link = nullptr private
Current link in the list.
Definition at line 430 of file jobs_utils.h.
m_locked
template<typename data_type> bool jobs::internal::multiple_writer_single_reader_list< data_type >::iterator::m_locked = false private
If we have acquired a read lock for the list.
Definition at line 433 of file jobs_utils.h.
m_owner
template<typename data_type> multiple_writer_single_reader_list* jobs::internal::multiple_writer_single_reader_list< data_type >::iterator::m_owner = nullptr private
List being iterated over.
Definition at line 427 of file jobs_utils.h.
The documentation for this struct was generated from the following file:
C:/Projects/libjobs/inc/jobs_utils.h